### ISSUE TITLE
How do I know the number of span calls per application or agent?

### ISSUE THREAD

**Issue by shs1494** [pinpoint-apm/pinpoint#10043]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

Hello,

Is there a way to know the number of span calls in a specific application or agent during the specified time period?
If it's not available on the web, I'm wondering if there's a way to get the data by calling the API.

**Comment by emeroad** [comment]
There is no feature to obtain span count by application.

If collector's jmx option is activated, the total number of span processing can be known.
`-Dcollector.metric.jmx=true`

![image](https://github.com/pinpoint-apm/pinpoint/assets/7564547/debf4e9a-0441-483f-ae1d-775bade758d5)
