### ISSUE TITLE
 Questions about the settings of "Alarm Rules - SLOW COUNT".

### ISSUE THREAD

**Issue by GMKIM94** [pinpoint-apm/pinpoint#10060]
Hi.

Description
Can the user set a slow criterion? This feature did not exist in the past, but I wonder if it exists in the latest version.
https://github.com/pinpoint-apm/pinpoint/issues/3566

Environment
- pinpoint version : 2.4.2

**Comment by smilu97** [comment]
That feature has not been developed yet due to the difficulty of achieving compatibility with older agents. Thank you for your understanding.

**Comment by GMKIM94** [comment]
Thanks for the reply
