### ISSUE TITLE
Does the collector support multi-instance deployment?

### ISSUE THREAD

**Issue by beWalter** [pinpoint-apm/pinpoint#10087]
Dear all,Does the collector can support multi-instance deployment?
I have deployed and run three instances of the collector, and they appear to be running fine.
But  I have noticed that when viewing trace information on the web console, for the same trace path, some traces display "API-METADATA-NOT-FOUND", while others are displayed correctly. What could be the cause of this issue? Is it related to the multi-instance deployment of the collector?

the same path,some displayed correctly and some not:
![image](https://github.com/pinpoint-apm/pinpoint/assets/19700715/530adb34-3f88-4152-a74c-47440e6a3567)
![image](https://github.com/pinpoint-apm/pinpoint/assets/19700715/b4b0b75c-ac5f-48b8-ad0a-32e22a8ee102)

I'm using v2.5.0, and pinpoint cluster deployed on Kubernetes.

**Comment by emeroad** [comment]
Pinpoint supports multi-instance deployment

The above problem usually occurs in the following situations.
1. Performance issues with HBbase
2. The sql metadata table has been deleted.
