### ISSUE TITLE
Can the number of characters in the application name be more than 24?

### ISSUE THREAD

**Issue by GMKIM94** [pinpoint-apm/pinpoint#10084]
Hi.

Can the number of characters in the application name be more than 24?
https://github.com/pinpoint-apm/pinpoint/issues/9813

**Comment by smilu97** [comment]
The constants in #9813 are defined for convenience, and if you change their values, the system will not behave correctly.

Using an abbreviated application name is probably the fastest way to go for now.

**Comment by GMKIM94** [comment]
Thanks for the reply
