### ISSUE TITLE
Unknown endpoint was collected

### ISSUE THREAD

**Issue by kjb512** [pinpoint-apm/pinpoint#10101]
- [ o] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

unrelated endpoint(binance server) was collected by pinpoint-collector

<img width="811" alt="스크린샷 2023-06-29 오후 11 55 35" src="https://github.com/pinpoint-apm/pinpoint/assets/53505860/63c25d5a-e35a-40d9-91b6-9bb08f4120e0">

is It possible to collect totally different server endpoints?

**Comment by emeroad** [comment]
endpoint is collected by getServerName(), so this data is correct.

https://github.com/pinpoint-apm/pinpoint/blob/master/plugins/common-servlet/src/main/java/com/navercorp/pinpoint/plugin/common/servlet/util/HttpServletRequestAdaptor.java#L74

```java
@Override
    public String getEndPoint(HttpServletRequest request) {
        String serverName = request.getServerName();
        int serverPort = request.getServerPort();
        return HostAndPort.toHostAndPortString(serverName, serverPort);
    }


```
