### ISSUE TITLE
why AGENT_ID_MAX_LEN limit to 24

### ISSUE THREAD

**Issue by qijun4tian** [pinpoint-apm/pinpoint#10113]
07-05 14:07:13.013 [0880-thread-111] WARN  p.p.a.d.i.ApacheDubboProviderInterceptor -- BEFORE. Caused:invalid transactionId:ikecloud4-31393-20230629094146^1688002906429^31403
java.lang.IllegalArgumentException: invalid transactionId:iwecloud4-31393-20230629094146^1688002906429^31403
	at com.navercorp.pinpoint.common.profiler.util.TransactionIdUtils.parseTransactionId(TransactionIdUtils.java:123) ~[pinpoint-commons-profiler-2.5.1.jar:2.5.1]

**Comment by smilu97** [comment]
As far as I know, it is just a magic number

We now recommend using agentName instead of agentId when you need human-readable identifier for each agent. When the agentName is provided, agentId is automatically generated to be a random UUID string. (but you can also clarify both)

**Comment by qijun4tian** [comment]
> As far as I know, it is just a magic number
> 
> We now recommend using agentName instead of agentId when you need human-readable identifier for each agent. When the agentName is provided, agentId is automatically generated to be a random UUID string. (but you can also clarify both)

So, if I increase the value AGENT_ID_MAX_LEN  24 to a bigger number, will it have an impact on the existing logic of pinpoint?"

**Comment by smilu97** [comment]
Yes, changing `AGENT_ID_MAX_LEN` may lead system to behave incorrectly
