### ISSUE TITLE
Unable to View Queries in Call Tree for a Spring Boot Application

### ISSUE THREAD

**Issue by Jinwook94** [pinpoint-apm/pinpoint#10191]
## Summary
- 핀포인트 웹에서 개별 요청을 선택 후 Call Tree를 보면 쿼리가 조회되지 않습니다. Call Tree에서 쿼리까지 확인하려면 어떻게 해야하나요?
JPA 사용과 관련 있는 것 같은데 어떻게 해결해야 할지 모르겠습니다.
- When I select an individual request in Pinpoint and look at the Call Tree, the query that is sent to the actual DB (MariaDB) is not traced, but only up to TransactionAspectSupport.invokeWithinTransaction() in the SPRING_TX API. How can I see up to the query in the call tree?
It seems to be related to using JPA, but I don't know how to solve it.

## Versions
- HBase: 1.4.9
- Pinpoint Web: 2.5.2
- Pinpoint Collector: 2.5.2
- Pinpoint Agent: 2.5.2
- Spring Boot: 2.7.3
- MariaDB: 10.5.18
- org.mariadb.jdbc:mariadb-java-client:3.0.7

## Env.
![image](https://github.com/pinpoint-apm/pinpoint/assets/44575214/4239b779-fb4b-490e-b335-546578a0fa15)

## Current Outcome
- I am using Pinpoint to monitor a Spring Boot application which is using JPA(Hibernate) for MariaDB connections.
- When I select an individual request in Pinpoint and look at the Call Tree, **I don't see the actual query sent to the DB** but only up to invokeWithinTransaction() method of which belongs to SPRING_TX API.
- ![image](https://github.com/pinpoint-apm/pinpoint/assets/44575214/f68bc586-35df-408a-bdc5-578eb1346391)
- ![image](https://github.com/pinpoint-apm/pinpoint/assets/44575214/1156a6e1-5c87-4332-8db2-87ddc35a17e6)

## Expected Outcome
- SQL queries shown in the call tree ([demo](http://125.209.240.10:10123/transactionList/ApiGateway@SPRING_BOOT/5m/2023-08-03-20-42-27?dragInfo=%7B%22x1%22:1691062931746,%22x2%22:1691062943610,%22y1%22:0,%22y2%22:732,%22agentId%22:%22%22,%22dotStatus%22:%5B%22success%22,%22failed%22%5D%7D&transactionInfo=%7B%22agentId%22:%22apigw01%22,%22spanId%22:%221095514342127630416%22,%22traceId%22:%22apigw01%5E1690785844442%5E55050%22,%22collectorAcceptTime%22:1691062932742,%22elapsed%22:14%7D))
- ![image](https://github.com/pinpoint-apm/pinpoint/assets/44575214/30a16663-642e-4fe9-bd40-2ef79d029e58)
- ![image](https://github.com/pinpoint-apm/pinpoint/assets/44575214/e012cf72-2819-4637-b148-0b1152711424)

## Config file (Agent)
pinpoint-agent-2.5.2/profiles/release/**pinpoint.config**

```
#
# MARIADB
#
# Profile MariaDB
profiler.jdbc.mariadb=true
# Allow profiling of setautocommit.
profiler.jdbc.mariadb.setautocommit=true
# Allow profiling of commit.
profiler.jdbc.mariadb.commit=true
# Allow profiling of rollback.
profiler.jdbc.mariadb.rollback=true
# Trace bindvalues for MariaDB PreparedStatements (overrides profiler.jdbc.tracesqlbindvalue)
profiler.jdbc.mariadb.tracesqlbindvalue=true
```

## Similar Issue
#9703

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/tree/master/plugins/mariadb-jdbc

Could you check the driver support of Maria db?

**Comment by Jinwook94** [comment]
Thank you for your guidance in resolving the issue. After adjusting the MariaDB version, I can now see the actual query in the Call Tree.

Just to provide some additional information, I have tested multiple versions of the org.mariadb.jdbc:mariadb-java-client as follows:
org.mariadb.jdbc:mariadb-java-client version | SQL Query Shown
-- | --
3.1.4 | x
3.1.0 | x
3.0.7 | x
3.0.3 | x
2.7.9 | o
2.7.0 | o

It appears that from version 3.0.3 onwards, the SQL queries are not shown in the Call Tree. 
So i think the current [compatibility range](https://github.com/pinpoint-apm/pinpoint/tree/master/plugins/mariadb-jdbc) for org.mariadb.jdbc:mariadb-java-client need to be changed to [1.1, 2.7]

@emeroad

**Comment by enaenen** [comment]
org.mariadb.jdbc:mariadb-java-client version | SQL Query Shown
-- | --
3.1.4 | x
3.1.0 | x
3.0.7 | x
3.0.3 | x
2.7.10 | x
2.7.9 | o
2.7.0 | o



Also 2.7.10 version is not supported.

**Comment by jaehong-kim** [comment]
@Jinwook94 
#11577

Thank you.
