### ISSUE TITLE
PINPOINT 2.6.0 agent failed due to java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint#10270]
I have configured WebLogic 13 server startup file (installed on Windows) to bind PINPOINT 2.6.0 agent and when I started WebLogic server then return error as below and agent is not starting properly. We are not using Apache Skywalk in this server .

** java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter

[pinpoint.log](https://github.com/pinpoint-apm/pinpoint/files/12484229/pinpoint.log)

**Comment by emeroad** [comment]
ClassNotFoundException is a skywalking error, it has nothing to do with pinpoint.

**Comment by snmsmanager** [comment]
you are correct . We have identified that customized Skyline agent also configured with same Weblogic config. thanks
