### ISSUE TITLE
Decaton kafka consume tracing

### ISSUE THREAD

**Issue by gipyeong-lee** [pinpoint-apm/pinpoint#10285]
**Which module is your feature request related to?**
Plugin

**Is your feature request related to a problem?**
No, it just implement new feature for supporting decaton library.
decaton is kafka library.

**Describe the solution you'd like**
decaton version 6.1.0
```
public class ProcessorSubscription extends Thread implements AsyncShutdownable {
class Handler implements ConsumerHandler {
public void receive(ConsumerRecord<byte[], byte[]> record) {
}
}
}
```
- tracing nested class's method `receive`

**Describe alternatives you've considered**
- create `pinpoint-decaton-plugin`
- support other version of decaton

**Additional context**

**Comment by ga-ram** [comment]
To trace decaton v1.0.0+, please use below options (kafka plugin)
```
profiler.kafka.consumer.enable=true
profiler.kafka.consumer.entryPoint=com.linecorp.decaton.processor.runtime.ProcessorSubscription$Handler.receive
```
