### ISSUE TITLE
Why don't start-collector.cmd, start-testapp.cmd, start-web.cmd files exist?

### ISSUE THREAD

**Issue by BEADYbirds** [pinpoint-apm/pinpoint#10327]
I cloned a folder in github, installed hbase, and ran the cmd file as it was in the official document. And I put the jar file in the location. Why do I get an error saying that I couldn't connect with zookeeper? Can anyone tell me the exact installation method? And the official document says to run start-collector.cmd, start-testapp.cmd, start-web.cmd files, but I can't find them Please let me know how to find i

**Comment by ga-ram** [comment]
It seems like those documents are no longer valid.
Please refer to https://pinpoint-apm.gitbook.io/pinpoint/getting-started/quickstart.
You don't need any cmd files to run Pinpoint since v2.1.0
