### ISSUE TITLE
pinpoint-mysql  databases looks like some tables are missing

### ISSUE THREAD

**Issue by xudingjun3131** [pinpoint-apm/pinpoint#10325]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [y] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

pinpoint-mysql  databases looks like some tables are missing
like  systemMetricTag  and  uriStat 

![image](https://github.com/pinpoint-apm/pinpoint/assets/16241230/0dd1bd1e-6b7b-4116-9aad-540e8a8f5123)
![image](https://github.com/pinpoint-apm/pinpoint/assets/16241230/a888e2bc-61f3-4c9c-8e0b-a3cfdf0f50ee)

![image](https://github.com/pinpoint-apm/pinpoint/assets/16241230/8e486c1c-f4aa-4c5c-84bf-dc6c11807b25)

**Comment by minwoo-jung** [comment]
Hi @xudingjun3131 
url statistics should store data in pinot and not mysql.
To use URL statistics, you must additionally install kafka and pinot.
Please refer to the link below for related guides.
https://pinpoint-apm.gitbook.io/pinpoint/documents/uri_statistics

**Comment by xudingjun3131** [comment]
> Hi @xudingjun3131 url statistics should store data in pinot and not mysql. To use URL statistics, you must additionally install kafka and pinot. Please refer to the link below for related guides. https://pinpoint-apm.gitbook.io/pinpoint/documents/uri_statistics

I have solved it。
The docker-compose-metric.yml has some online resource like  github,I check it out offline ,it's ok。

**Comment by xudingjun3131** [comment]
I have solved it。
The docker-compose-metric.yml has some online resource like github,I check it out offline ,it's ok.
Get the github online resource first and modify Dockerfile ，it will be ok。
