### ISSUE TITLE
Accumulo backed storage

### ISSUE THREAD

**Issue by vaibhavthapliyal** [pinpoint-apm/pinpoint#1032]
Hi,
I wanted to ask if there are plans to support Accumulo as storage for pinpoint. It would be great if there is support for accumulo too.

Thanks 
Vaibhav

**Comment by Xylus** [comment]
Hi Vaibhav,

Accumulo backend would be great, but adding support for additional backend storage would take quite a bit of work (plus loads of refactoring), and is not high up on our priority list.

Hopefully, we will get there one day.
