### ISSUE TITLE
proxy pinpoint-web through nginx,websocket error has occurred

### ISSUE THREAD

**Issue by xudingjun3131** [pinpoint-apm/pinpoint#10342]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [✓] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

I proxy pinpoint-web through nginx， but it has wss error， how can i solve it ?
my nginx configure is:

upstream pp {
        server 10.12.10.9:8080;
        keepalive 300; # 这个很重要!
    }
    server {
        listen       80;
        server_name  pp.qiyuesuo.net;
        return      301 https://$server_name$request_uri;
    }

    server {
        listen       443 ssl;
        server_name  xxxxxxxxxxxx;
      ssl_certificate      /etc/nginx/ssl/cert.crt;
      ssl_certificate_key  /etc/nginx/ssl/key.key;

        location / {
            proxy_pass http://pp;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }
        location /agent {
                proxy_pass http://pp;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                #proxy_set_header Connection ""; # 这个很重要！
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

    }

The error
![image](https://github.com/pinpoint-apm/pinpoint/assets/16241230/199e67f2-93a2-4794-9209-36136010e710)

**Comment by emeroad** [comment]
Search nginx's websocket config.
