### ISSUE TITLE
Remove selected application.

### ISSUE THREAD

**Issue by wsw136** [pinpoint-apm/pinpoint#10368]
I want to remove nouse application,  but it need to input password to remove
![image](https://github.com/pinpoint-apm/pinpoint/assets/36026057/aba6b07b-40e5-466e-883c-173a61ecd90e)
password not set, i click submit can't not  remove

**Comment by harveychong** [comment]
works for me when I enter `admin`

**Comment by donghun-cho** [comment]
Did you change web properties?
if not default value is `admin` like what harveychong mentioned above
https://github.com/pinpoint-apm/pinpoint/blob/master/web/src/main/resources/pinpoint-web-root.properties#L31

**Comment by wsw136** [comment]
@donghun-cho  @harveychong   thanks

**Comment by wsw136** [comment]
thanks 













At 2023-09-25 19:29:28, "donghun-cho" ***@***.***> wrote:

Did you change web properties?
if not default value is admin like what harveychong mentioned above
https://github.com/pinpoint-apm/pinpoint/blob/master/web/src/main/resources/pinpoint-web-root.properties#L31
