### ISSUE TITLE
Support microseconds scale when measuring intervals between traces

### ISSUE THREAD

**Issue by woozu-shin** [pinpoint-apm/pinpoint#10408]
### For worldwide,

**Which module is your feature request related to?**
profiler w/ Web UI

**Is your feature request related to a problem?**
When I inspect using with call tree, missed part of callstack execution time.
It caused by very short execution time come together.
This corresponds to short execution time less than 1ms (exactly, the gap under 1ms between trace) (Fig. 1)

> Like non-alcoholic drinks.
> Although it is 0% in notation, but it is not 0% in reality.

So added all callstacks times which is not the same as response time.
Therefore, the sum of all callstack times and the response time are not the same.
As an extreme example, operated 1000 * 1 microseconds, that API request elapsed 1ms but each callstack will be recording 0ms. 
This type of tracking is outside the scope of APM, but sometimes this functionality is necessary for inspection.

**Describe the solution you'd like**
The profiler records timestamp, including microseconds, and hbase store as it is. (Fig. 2)
The pinpoint-web can select notation, or automatically rendering.

**Describe alternatives you've considered**
gRPC idl already defined timestamp by signed int 64, so there it dosen't seem to be any problem with storing microseconds.
Disadvantage is that existing data needs to be migrated.

**Additional context**

- Fig. 1
![image](https://github.com/pinpoint-apm/pinpoint/assets/93126826/e165d066-4bb4-4be4-87d1-3f19addaadb5)

- Fig. 2
![image](https://github.com/pinpoint-apm/pinpoint/assets/93126826/8c5019eb-d3a3-436c-8c81-2ada26272b75)

---
### For regional developers,

**Which module is your feature request related to?**
프로파일러 및 Web UI

**Is your feature request related to a problem?**
call tree 기능을 이용해서 request 를 inspection 할 때의 문제입니다.
매우 짧은 수행시간을 갖는 method 들은 (method gap 이 1ms 미만일 경우) call tree 상 0ms 로 표현됩니다.

특정 기능이 다량의 method call 을 갖는 경우  `response time < ∑(methods execution time)`  이게 되는데,
일반적인 오차 허용 범위를 크게 벗어납니다.
따라서 성능 최적화를 위한 인사이트를 얻는 과정에서 애로사항이 있습니다.

APM 이 자잘한 메서드 하나하나까지 검사하기 위한 수단은 아니지만, 때때로 이런 기능이 필요한 케이스가 있습니다.

**Describe the solution you'd like**
- profiler 가 microseconds 를 포함하여 timestamp 를 기록하고,
  hbase 내에서도 밀리초 timestamp 를 저장합니다.
- pinpoint web 에서는 millis / micros 를 선택할 수 있습니다.
- 전체 span data 의 마이그레이션 이 필요없는 방법으로,
   자릿수에 따라 자동 표기되는 옵션도 생각해보았으나
   장기적으로 우아하지 않을 것 같습니다.

**Describe alternatives you've considered**
gRPC idl schema 를 보면 timestamp 가 64bit 로 정의돼있어서 microseconds 를 저장하는데 무리가 없지 않을까 싶네요.
다만 gap 의 단위가 millis 로 차를 기록하고 있어서 이 부분의 해소도 필요합니다. (기존 데이터)
따라서
- 데이터 마이그레이션이 필요하거나
- type 을 기록하는 field 가 schema 에 추가되는 방법이 있을 것 같습니다.

**Additional context**
생략

감사합니다.

**Comment by emeroad** [comment]
Since APM operates in a real environment, it must use minimal system resources.
Therefore, a good compromise is needed between performance and precision, and milliseconds are a good compromise.

In this case, it would be better to use the java profile.
## java profiler 
yourkit: https://www.yourkit.com/java/profiler/features/
jprofiler: https://www.ej-technologies.com/products/jprofiler/overview.html

**Comment by woozu-shin** [comment]
I'll try it.
Thank you for your support.
