### ISSUE TITLE
Asynchronous Invocation call time is not added to api's total time shown in Res(ms)/Exec(ms) columns

### ISSUE THREAD

**Issue by mahudees** [pinpoint-apm/pinpoint#10417]
I have an api which creates async call to other functions. When tracing this api the "Exec (ms)" column shows only a fraction of time the api actually took (including the async call). For ex, in my case api took around ~9911 milli seconds, but it is reported as 141 milli second. But when we select the trace, able to see the async call and the time it took (~9911 milli secs).

So we need to select the trace and see the "Call Tree" to know the actual time it took, so it is difficult to find if the api is taking time, just by looking at api listed on top. Attached a screen shot for this.

I wrote a sample spring boot rest application and created a async call in that, but able to see the actual time (including async calls) it took in Exec(ms) column of the trace. Not sure if something is missing.

Using Pin point version 2.5.3 in both the case and config is similar for both tests.

<img width="1111" alt="Screenshot 2023-10-17 at 12 52 35 AM" src="https://github.com/pinpoint-apm/pinpoint/assets/42842581/d14a060f-00cb-4105-aaab-83686b4c4eb1">

**Comment by emeroad** [comment]
```
  client --------> server
         <--- | -- (100ms)
              | -------async----------------> ( exec 10sec)
```
Exec Time is based on the time the results were sent to the user.
If the asynchronous call behaves as above, 100ms is the correct answer.

**Comment by mahudees** [comment]
Thanks for the reply. Got it.
