### ISSUE TITLE
Custom Exceptions operate differently between versions 2.3.x and 2.5.x.

### ISSUE THREAD

**Issue by Heejong-Oh** [pinpoint-apm/pinpoint#10425]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v2.5.3

#### Describe the bug

user-defined exceptions operate differently between versions 2.3.x and 2.5.x.
User-defined exceptions were not recognized as errors in 2.3.2, but in 2.5.3 it was marked as an error, causing unsightly red dots on the scatter chart.

Could you please fix it so that user-defined exceptions are not displayed as errors like in version 2.3.2?

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran '...' with agent attached
2. '...' method invoked
3. '...' interceptor threw '...' exception

#### Screenshots

**v2.5.3**
![image](https://github.com/pinpoint-apm/pinpoint/assets/148506248/b840b0f9-bf09-4b41-944f-7ccdaad61175)

**v.2.3.2**
![image](https://github.com/pinpoint-apm/pinpoint/assets/148506248/de3d91d9-d7f6-411d-886b-0ab8b2717613)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by jaehong-kim** [comment]
@Heejong-Oh 
Please check the pinpoint.config

Spring beans method
If the setting value is true, it is tracked as an error.
~~~
profiler.spring.beans.mark.error=true
~~~

User defined ignore error
Ignore some of the errors.
~~~
###########################################################
# user defined ignore-error-handler                       #
###########################################################
# Set exception to ignore error
#
# eg) Set `com.myapplication.user.AccessDeniedException("Access is denied")` to error
#
# ${ERROR_HANDLER_ID} PATTERN = [A-Za-z0-9-_]+
#
# Match the FQCN(Fully qualified Class Name) of the exception. Separated by ","
# profiler.ignore-error-handler.${ERROR_HANDLER_ID}.class-name=com.myapplication.user.AccessDeniedException
#
# Match Exception.getMessage(), This action is performed when FQCN matching is successful.
# The match condition uses String.contains(). Separated by ","
# profiler.ignore-error-handler.${ERROR_HANDLER_ID}.exception-message@contains=Access is denied
#
# Search for chained exceptions(Exception.getCause()). (default : true)
# profiler.ignore-error-handler.${ERROR_HANDLER_ID}.nested=true
#
# Search for parent class. (default : true)
# profiler.ignore-error-handler.${ERROR_HANDLER_ID}.parent=true

profiler.ignore-error-handler.myErrorHandler.class-name=
profiler.ignore-error-handler.myErrorHandler.exception-message@contains=
# profiler.ignore-error-handler.myErrorHandler.nested=true
# profiler.ignore-error-handler.myErrorHandler.parent=true
~~~

**Comment by Heejong-Oh** [comment]
Our pinpoint.config of the pinpiont-agent

```
profiler.spring.beans.mark.error=false
```


I confirmed that I can set it so that the error is not displayed by modifying the config contents below.
However, we have too many user-defined exceptions.....
```
profiler.ignore-error-handler.PubApiExcept.class-name=net.xxxx.api.common.exception.PubApiException,net.xxxxx.api.show.exception.xxxxxNotFoundException
profiler.ignore-error-handler.PubApiExcept.exception-message@contains=Order not found,Product not found,not found xxxx
```

**Comment by jaehong-kim** [comment]
@Heejong-Oh 
It does not track exceptions as request failures.
Please check the option.
~~~
# HTTP status code with request failure.
# 1xx, 2xx, 3xx, 4xx, 5xx, 100, 101, 200, 201, ... 501, 502, 503, 504, 505
# e.g. profiler.http.status.code.errors=5xx, 401, 403
profiler.http.status.code.errors=5xx
~~~

**Comment by Heejong-Oh** [comment]
@jaehong-kim 
Our settings are the same as yours.

The response code for the request in the attached screenshot is 200.
However, due to a user-defined exception, it is displayed as an error in the scatter chart.

```
# HTTP status code with request failure.
# 1xx, 2xx, 3xx, 4xx, 5xx, 100, 101, 200, 201, ... 501, 502, 503, 504, 505
# e.g. profiler.http.status.code.errors=5xx, 401, 403
profiler.http.status.code.errors=5xx
```

**Comment by jaehong-kim** [comment]
@Heejong-Oh 
Please forward the pinpoint starting log.

**Comment by Heejong-Oh** [comment]
@jaehong-kim 

[pinpoint_start.log](https://github.com/pinpoint-apm/pinpoint/files/13057108/pinpoint_start.log)

**Comment by jaehong-kim** [comment]
@Heejong-Oh 
Show me the entire Call stack screen.
If an exception occurs outside the spring beans object, it may be recognized as a failure.
For example, if an exception occurs in a http client or jdbc, it is recognized as a failure

**Comment by Heejong-Oh** [comment]
@jaehong-kim 
I attached our entire call tree.
Please refer this attached image.
![image](https://github.com/pinpoint-apm/pinpoint/assets/148506248/331f8b3a-719d-4e5d-925a-3b9409d424f4)

**Comment by jaehong-kim** [comment]
@Heejong-Oh 
This is due to spring-tx plugins added in version 2.5.1.
![spring-tx-fail-2](https://github.com/pinpoint-apm/pinpoint/assets/10043788/7d1747b7-f202-4795-bdf0-221198b6cb2e)

Disable spring-tx plugin.
`-Dprofiler.spring.tx.enable=false`

**Comment by Heejong-Oh** [comment]
@jaehong-kim 

I changed it to the option below and confirmed that it works well.
profiler.spring.tx.enable=false

Thank you very much!
