### ISSUE TITLE
pinpoint agent is failing to save metadata

### ISSUE THREAD

**Issue by elther** [pinpoint-apm/pinpoint#10450]
agent version : 2.5.3

my service is running in a k8s. and using pinpoint for APM
a few days ago, i realized metadata was being collected differently for each agentId
some agentIds had metadata for hikariCP, while others did not have metadata for hikariCP
spring metadata also varied by agentId

To solve issue : 
1. all agents restart
2. pinpoint version up : 2.5.0 -> 2.5.3
3. ApiMetaData table clean up 

here is screen shot
![image](https://github.com/pinpoint-apm/pinpoint/assets/11730071/d72b672b-2925-416d-87ec-90b92c61f23f)
i wanted to display spring metadata, but after restarting agent, it can't load the metadata

![image](https://github.com/pinpoint-apm/pinpoint/assets/11730071/f69fc0e6-fcb7-443c-b275-6847dea9cc69)

ApiMetaData table screen shot
![image](https://github.com/pinpoint-apm/pinpoint/assets/11730071/44a966a4-2285-4c8f-9080-948d05201b9f)

does anybody has insights about this issue? 

#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

**Comment by emeroad** [comment]
1. Metadata transmission failed due to insufficient hbase performance
2. The hbase metadata table has been deleted.

Please refer to the above.

Pinpoint Docker images are not suitable for production environments.
To use pinpoint in a production environment, build a Fully-Distributed Hbase Cluster.

**Comment by elther** [comment]
thank you for answer, but i've faced another issue. 

Unable to connect to the collector when starting the pinpoint agent.
Until spring boot initializes, the agent attempts to connect with the collector three or four times. 

In my opinion, it seems that the agent is not initially connecting to the collector, which is causing it to not properly transmit metadata information

![image](https://github.com/pinpoint-apm/pinpoint/assets/11730071/d3cf20fd-b232-4e42-b409-e3c512d6d056)

**Comment by elther** [comment]
i found network issue when the container initializes 
and modified pinpoint config

profiler.transport.grpc.metadata.sender.retry.max.count=30 (default 3)
profiler.transport.grpc.metadata.sender.retry.delay.millis=10000 (default 1000)

it works

**Comment by elther** [comment]
i found network issue when the container initializes 
and modified pinpoint config

profiler.transport.grpc.metadata.sender.retry.max.count=30 (default 3)
profiler.transport.grpc.metadata.sender.retry.delay.millis=10000 (default 1000)

it works
