### ISSUE TITLE
핀포인트 hbase의 데이터에 대한 로테이션 또는 데이터 유지 기간 문의

### ISSUE THREAD

**Issue by sungiing** [pinpoint-apm/pinpoint#10459]
안녕하세요.

도커로 구성된 핀포인트 오픈소스 2.0.4 버전을 사용중입니다.
도커의 각 컨테이너에 대한 로그들에 대한 로깅드라이버 로테이션 기능은 있는 것 으로 보이나, hbase의 데이터에 대한 로테이션 기능 또는 데이터 유지기간이 있는지 있다면, 설정 방법에 대한 가이드를 문의 드립니다.

현재 hbase에 데이터가 너무 많이 쌓이는데(3 TB 를 채우는데 보통 3주 소요)
로테이션 및 데이터 보관 기간에 대한 제한이 없는 관계로 데이터를 삭제하지 못하고, DISK를 매번 비우고 있습니다.
(DISK를 비움으로 이전 데이터 조회 불가 현상)

hbase/Dockerfile 을 살펴보면, hbase에 대한 데이터 보관 주기에 대한 설정이 별도로 없는 것 같습니다.
hbase의 데이터 유지 기간과 같은 설정을 해서 데이터가 쌓이는 것을 방지하고 싶습니다.

참고로 오픈소스가 아닌, 상용으로 된 제품은 2개월에 대한 데이터 조회가 가능한 것으로 알고 있습니다.
상용으로된 제품 사용에는 위와 같은 이슈가 없는 것으로 보여 문의 드립니다.

감사합니다.

**Comment by minwoo-jung** [comment]
@sungiing Hi
Please ask questions in English so that all pinpoint users can check the contents.

**Comment by sungiing** [comment]
> @sungiing Hi Please ask questions in English so that all pinpoint users can check the contents.

hello.

I am using Pinpoint open source version 2.0.4, configured with Docker.
It appears that there is a host driver rotation function for logs for each container in Docker, but whether there is a display function or data retention period for hbase data, and a guide on how to set it up, please link.

There is currently too much data piling up in hbase (it takes 3 weeks to reference 3TB)
Since there are no restrictions on rotation or data retention period, the DISK is saved and emptied to avoid data deletion.
(Previous data inquiry status by emptying the DISK)

Looking at the hbase/Dockerfile, the configuration for data archiving for hbase is not partial.
Follow the same settings as hbase's data retention period to prevent your data from being placed and make yourself confident.

For reference, I understand that for products that are not open source and connected to a laptop, data can be viewed for 2 months.
Products used as keyboards do not appear to have the same problem.

thank you

**Comment by emeroad** [comment]
Please refer to the FAQ.
https://pinpoint-apm.gitbook.io/pinpoint/faq#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first

**Comment by sungiing** [comment]
After checking, the pinpoint/hbase/scripts/ path is not currently used in our environment.
To use major compaction, do I need to build a hbase container image and create a new one?
Alternatively, can I copy the major compaction-related files to the pinpoint/hbase/scripts/ path and use them without the need to build or create a new container image?

Is there any additional explanation of the major_compact function?

**Comment by minwoo-jung** [comment]
The first thing I would recommend is to reduce the TTL.
you can reduce the TTL or run a major compaction by connecting to the hbase server and running the command.
To connect to the server and run commands, you will need to learn about container and hbase.
