### ISSUE TITLE
How can I set the alarm for system metrics in Infrastructure

### ISSUE THREAD

**Issue by soogineer** [pinpoint-apm/pinpoint#10524]
Hi team,

Thanks for your support.
I set the alarm for error count, slow count and system cpu usage rate using rule name, but I was not able to set the alarm for system metrics in infrastructure such as cpu, memory usage percent, memory usage, disk usage and etc.

I have tried to find the way to set these, but I was not able to find the best way to set things up unfortunately. 
I wonder if there is any way to set these up or not by any chance.

It would be very thankful if there are any suggestions for that.

Thanks.

**Comment by minwoo-jung** [comment]
@soogineer 


Unfortunately, alarm settings for system metrics have not yet been developed.
We also believe that alarms for system metrics are necessary.
There is no set schedule yet for when it will be developed.

If possible, it is also a good idea to develop it yourself and contribute.

**Comment by soogineer** [comment]
Gotcha. Thanks for your help!
