### ISSUE TITLE
How can I get the TraceId in spring boot

### ISSUE THREAD

**Issue by CareyQ** [pinpoint-apm/pinpoint#10542]
How can I get the TraceId in spring boot? I looked through the history iusse and couldn't find a solution.

I'm new to pinpoint, I hope someone can help me.

**Comment by linxiaoJVM** [comment]
I guess you want to print out TraceId in the log. If that's the case, then follow these steps:
1、determine which logging framework your application is using. Currently, it supports log4j, Logback, and log4j2.
2、In the pinpoint.config file, set profiler.xxx.logging.transactioninfo=true, where xxx represents the logging framework used in your application. If you're unsure about the logging framework being used, you can set all three configurations (log4j, Logback, log4j2) to true.
3、In your program's log configuration file, modify the <pattern> </pattern> section and add TxId:%X{PtxId} SpanId:%X{PspanId}. For example, `<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - [TxId:%X{PtxId} SpanId:%X{PspanId}] - %msg%n</pattern>`.
4、Restart your application.

If you have correctly followed the above steps, you will see the output of the TraceId in the console.
