### ISSUE TITLE
Where are the following three documents?  dev-profiler.md, dev-collector.md, dev-web.md. Thanks

### ISSUE THREAD

**Issue by caicha** [pinpoint-apm/pinpoint#10563]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

**Comment by emeroad** [comment]
https://pinpoint-apm.gitbook.io/pinpoint/getting-started/installation

Please refer to gitbook.
