### ISSUE TITLE
Hello, the spanId and parentSpanId cannot be obtained in the service map. How can I query the spanId and parentSpanId in the service map through traceId?

### ISSUE THREAD

**Issue by zhangzhuzi** [pinpoint-apm/pinpoint#10580]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

**Comment by emeroad** [comment]
spanId and parentSpanId are not used as query keys.

https://pinpoint-apm.gitbook.io/pinpoint/documents/per-request_feature_guide

If you use the log plugin, you can get the txId, which you can search through.
