### ISSUE TITLE
unable to detect applicationtype in the Spring Boot 3.2.X

### ISSUE THREAD

**Issue by nooose** [pinpoint-apm/pinpoint#10615]
**Which module is your feature request related to?**
Plugin

**Is your feature request related to a problem?**
same title.
Server map displays the Java icon application

**Describe the solution you'd like**
applicationtype should be automatically detected

**Describe alternatives you've considered**
add the main classes for 3.2.X to `SpringBootDetector` class.

**Additional context**
read [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-RC1-Release-Notes) 
you can see new launcher classes

**Comment by donghun-cho** [comment]
@nooose, thank you for explaination and PR.

The main classes can be configured by editing the agent configuration. The property name is `profiler.springboot.bootstrap.main`.

The agent configuration also needs to be changed for automatic detection. Could you please add that to your PR?

**Comment by nooose** [comment]
@donghun-cho 
That's right. I didn't check that.
 I'll add more
