### ISSUE TITLE
application has registry ,but no data

### ISSUE THREAD

**Issue by testfyy** [pinpoint-apm/pinpoint#10767]
application has registry ,but no data
version :pinpoint 2.3.2
agent :java

application has registry ,but no data,collector and agent  has no error log 
pinponit-agent‘s config like this：
just modify 
profiler.transport.grpc.collector.ip
profiler.collector.ip

![image](https://github.com/pinpoint-apm/pinpoint/assets/163960310/124928e5-fbcb-4e6d-908b-be0a9b115a17)

![image](https://github.com/pinpoint-apm/pinpoint/assets/163960310/fce698e0-2d0a-4612-a16e-3a943910b7d0)

pinpoint web like this
![image](https://github.com/pinpoint-apm/pinpoint/assets/163960310/14dea84d-8a5d-41ca-9a0a-2710cb361e7a)
![image](https://github.com/pinpoint-apm/pinpoint/assets/163960310/a9dcc3d6-bf0c-40cc-a0c7-aa8fcf8129c5)

**Comment by emeroad** [comment]
https://pinpoint-apm.gitbook.io/pinpoint/faq#why-is-only-the-first-some-of-the-requests-traced

The default sampling rate is 20.
`-profiler.sampling.rate=1`
Change the sampling rate to 1.

**Comment by testfyy** [comment]
Thank you for your answer, but set profiler.sampling.rate=1,there is still no data available

collect-agent log: 
![企业微信截图_17109185505671](https://github.com/pinpoint-apm/pinpoint/assets/163960310/90c5c99c-d187-4c2e-8738-d2ae410d0310)

**Comment by linxiaoJVM** [comment]
The profiler.sampling.rate=1 configuration is disabled by default, use profiler.sampling.counting.sampling-rate=1 instead of it.

```
# if it's COUNTING(the default), then 1 out of n transactions will be sampled where n is the rate.
# eg. 1: 100%     20: 5%     50: 2%      100: 1%
profiler.sampling.counting.sampling-rate=1
# @Deprecate : Alias for profiler.sampling.counting.sampling-rate
#profiler.sampling.rate=20
```

**Comment by testfyy** [comment]
modify profiler.sampling.counting.sampling-rate=1 and  Reinstall  version 2.5.3（collector web and agent），now is ok
application java version is 
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)
