### ISSUE TITLE
How to increase the screen display limiter.

### ISSUE THREAD

**Issue by king1975** [pinpoint-apm/pinpoint#10955]
Dear all

The following error occurred when displaying the Scatter Chart.

Too many link data. Reduce the values of the Inbound/outbound or do not select the bidirectional option. **limiter=736147155/500000000**

How can I increase this "limiter" value?

Best Regards
Thank you.

**Comment by jaehong-kim** [comment]
@king1975 
pinpoint-web.properties

~~~
web.servermap.linkData.limit=500000000
~~~
