### ISSUE TITLE
How to disable pinpoint agent console stdout 

### ISSUE THREAD

**Issue by linux0x5c** [pinpoint-apm/pinpoint#11018]
pinpoint-agent version 2.3.0

I modified log level to ERROR in $PINPOINT_HOME/lib log4j.xml and $PINPOINT_HOME/profiles/release/log4j2.xml ,but don't work.  The console log 
still exist.

*******************************
05-15 14:54:53.950 INFO  PinpointBootStrap                   : pinpoint agentArgs:null
05-15 14:54:53.976 INFO  PinpointBootStrap                   : PinpointBootStrap.ClassLoader:null
05-15 14:54:53.976 INFO  PinpointBootStrap                   : ContextClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2
05-15 14:54:53.978 INFO  ClassAgentPathFinder                : agentPath:/usr/local/pinpoint-agent/pinpoint-bootstrap-2.3.0.jar
05-15 14:54:53.978 INFO  PinpointBootStrap                   : JavaAgentPath:/usr/local/pinpoint-agent/pinpoint-bootstrap-2.3.0.jar
05-15 14:54:53.979 INFO  AgentDirBaseClassPathResolver       : Agent original-path:/usr/local/pinpoint-agent
05-15 14:54:53.979 INFO  AgentDirBaseClassPathResolver       : Agent canonical-path:/usr/local/pinpoint-agent
05-15 14:54:53.980 INFO  BootDir                             : found pinpoint-commons.jar path:/usr/local/pinpoint-agent/boot/pinpoint-commons-2.3.0.jar
05-15 14:54:53.981 INFO  BootDir                             : found pinpoint-bootstrap-core.jar path:/usr/local/pinpoint-agent/boot/pinpoint-bootstrap-core-2.3.0.jar
05-15 14:54:53.982 INFO  BootDir                             : found pinpoint-annotations.jar path:/usr/local/pinpoint-agent/boot/pinpoint-annotations-2.3.0.jar
05-15 14:54:53.982 INFO  BootDir                             : found pinpoint-bootstrap-java8.jar path:/usr/local/pinpoint-agent/boot/pinpoint-bootstrap-java8-2.3.0.jar
05-15 14:54:53.983 INFO  BootDir                             : found pinpoint-bootstrap-java9.jar path:/usr/local/pinpoint-agent/boot/pinpoint-bootstrap-java9-2.3.0.jar
05-15 14:54:53.994 INFO  AgentDirBaseClassPathResolver       : Found plugins:/usr/local/pinpoint-agent/plugin/pinpoint-jdk-completable-future-plugin-2.3.0.jar
05-15 14:54:53.994 INFO  AgentDirBaseClassPathResolver       : Found plugins:/usr/local/pinpoint-agent/plugin/pinpoint-redis-plugin-2.3.0.jar
05-15 14:54:53.995 INFO  AgentDirBaseClassPathResolver       : Found plugins:/usr/local/pinpoint-agent/plugin/pinpoint-okhttp-plugin-2.3.0.jar

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/issues/8171

`-Dpinpoint.agent.bootlogger.loglevel=WARN`

Please refer to the options above.

**Comment by linux0x5c** [comment]
Thanks, I got it.
