### ISSUE TITLE
How to Disable Local File Logging for Pinpoint Agent?

### ISSUE THREAD

**Issue by lxxxxxxk** [pinpoint-apm/pinpoint#11068]
Hi,

I am using the Pinpoint Agent and have observed that it writes logs to the local file system. This could potentially lead to uncontrolled disk usage. I would like to disable local file logging for the Pinpoint Agent.

Could you please let me know what environment variables or configuration settings I need to use to achieve this?

**Comment by emeroad** [comment]
$PINPOINT_DIR/log4j2-agent.xml

Please refer to the log4j file.
