### ISSUE TITLE
WIKI url is not correct..

### ISSUE THREAD

**Issue by Tmoney2014** [pinpoint-apm/pinpoint#11073]
![image](https://github.com/pinpoint-apm/pinpoint/assets/107834618/4091568a-9352-44e6-8d66-77a8abd30a51)
where i want to go (see image)
http://helloworld.naver.com/helloworld/1194202

actual page -> https://d2.naver.com/helloworld/1194202

안녕하세요
wiki url 접속이 안되어 조금 찾아보니, 주소가 바뀐거 같습니다.
확인 부탁 드리겠습니다.
이미지의 링크를 클릭하면 http://helloworld.naver.com/helloworld/1194202 여기로 연결 되지만, 화면이 안뜨고
실제 내용을 확인할 수 있는 사이트는 https://d2.naver.com/helloworld/1194202 여기였습니다.
감사합니다.

**Comment by Tmoney2014** [comment]
shortly 
on image red line, url is link to [http://helloworld.naver.com/helloworld/1194202]
some reason , page url has been changed to [https://d2.naver.com/helloworld/1194202] (?)

**Comment by intr3p1d** [comment]
I have checked the changes you made. Thank you for the update. :+1:
