### ISSUE TITLE
Inquiry about the separated method for the Pinpoint web server

### ISSUE THREAD

**Issue by lkh2919** [pinpoint-apm/pinpoint#11172]
I am using Pinpoint v 2.5.4. 
I have set up the Pinpoint web on a server in the DMZ zone.
And plan to run the HBase and collector services on a server in the internal zone. 
There is a firewall between the Pinpoint web server and the collector & HBase server. 

Which essential ports need to be opened?

**Comment by intr3p1d** [comment]
Referring to the manual below may help you understand the architecture between web, collector, and HBase server.
https://pinpoint-apm.gitbook.io/pinpoint/v/v2.5.4/want-a-quick-tour/overview#architecture

To briefly explain the architecture of Pinpoint v2.5.4:
The structure is Agent <-> Collector <-> HBase <-> Web.

Communication between the Agent and Collector requires 3 to 4 different ports.
Collector ports such as 9991, 9992, and 9993 are required, but they can be changed through configuration.
https://pinpoint-apm.gitbook.io/pinpoint/v/v2.5.4/getting-started/installation#configuration

The web port should be opened similarly to opening the port for a Spring Boot application (e.g., `-Dserver.port=8080`).
https://pinpoint-apm.gitbook.io/pinpoint/v/v2.5.4/getting-started/installation#configuration-1

**Comment by lkh2919** [comment]
thanks for your reply :)
