### ISSUE TITLE
Add AsyncWarmup to prevent OOM on collector startup

### ISSUE THREAD

**Issue by emeroad** [pinpoint-apm/pinpoint#11190]
Add AsyncWarmup to prevent OOM on collector startup

If AsyncConnection's RegionLocator is not initialized, 
there is an issue with excessive LocateRequest requests in high workloads.

<img width="1127" alt="image" src="https://github.com/pinpoint-apm/pinpoint/assets/7564547/8646cef0-095c-4c43-a98f-81da50aea3be">

**Comment by car1000** [comment]
Help,Can you please take a look at my issue?

**Comment by emeroad** [comment]
Try analyzing the heap dump of the server where the issue is occurring to see if the situation is similar to the above.

We apologize for not being able to provide a more detailed answer.

**Comment by car1000** [comment]
End Status	Unexpected Shutdown (last checked : 2024.06.27 14:56:28 +08:00)
--------------------------------
We have this error. What could be the reason? Where do we need to look at the code?

**Comment by car1000** [comment]
Is it because the JVM CPU reaches more than 90% and the ServerMap information is not displayed? Therefore, the IP address and offline flag are displayed on the inspector, but not on the servermap.
