### ISSUE TITLE
[SolutionShare] run/debug pinpoint-web error using intellij idea community edition

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#11301]
#### What version of pinpoint are you using?
3.0.0

#### Describe your problem**
Debug/Run pinpoint web in Intellij Idea got " java.lang.NoClassDefFoundError: jakarta/servlet/ServletException" error.

#### What have you done?

![image](https://github.com/user-attachments/assets/5e459b44-7540-419d-9d04-425b24032a82)

Run/Debug Pinpoint web from Intellij Idea got the following error,

> [           main] ERROR o.s.b.SpringApplication                  -- Application run failed
> java.lang.NoClassDefFoundError: jakarta/servlet/ServletException
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory.createContext(ServletWebServerApplicationContextFactory.java:52) ~[spring-boot-3.2.4.jar:3.2.4]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory.create(ServletWebServerApplicationContextFactory.java:47) ~[spring-boot-3.2.4.jar:3.2.4]
> 	at org.springframework.boot.DefaultApplicationContextFactory.getFromSpringFactories(DefaultApplicationContextFactory.java:70) ~[spring-boot-3.2.4.jar:3.2.4]
> 	at org.springframework.boot.DefaultApplicationContextFactory.create(DefaultApplicationContextFactory.java:50) ~[spring-boot-3.2.4.jar:3.2.4]
> 	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:589) [spring-boot-3.2.4.jar:3.2.4]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) [spring-boot-3.2.4.jar:3.2.4]
> 	at com.navercorp.pinpoint.common.server.starter.BasicStarter.start(BasicStarter.java:70) [pinpoint-commons-server-3.0.0.jar:3.0.0]
> 	at com.navercorp.pinpoint.web.WebApp.main(WebApp.java:55) [classes/:?]

**Comment by yjqg6666** [comment]
The solution is:
1. in project root pom.xml, delete line  "<scope>provided</scope>" for "spring-boot-starter-tomcat"
![image](https://github.com/user-attachments/assets/3b7986e8-ad65-428e-8adc-cebc476c588f)

2. in module pinpoint-web pom.xml,  delete line  "<scope>provided</scope>" for "spring-boot-starter-tomcat"
![image](https://github.com/user-attachments/assets/2b3e29f5-75e9-43cc-8281-7899f85d1810)

**Comment by emeroad** [comment]
Fixed a Tomcat dependency issue for IntelliJ Community Edition.
