### ISSUE TITLE
pinpoint3.0.0 uses kafka to pass monitored metrics, so can stop the hbase database?

### ISSUE THREAD

**Issue by xiongxu199412** [pinpoint-apm/pinpoint#11348]
pinpoint3.0.0 uses kafka to pass monitored metrics, so can stop the hbase database?

**Comment by emeroad** [comment]
https://pinpoint-apm.gitbook.io/pinpoint/want-a-quick-tour/overview#architecture
![Architecture](https://pinpoint-apm.gitbook.io/~gitbook/image?url=https%3A%2F%2F2967689678-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252F-MgQ1Is59jDrgEN5nG-0-3931491796%252Fuploads%252Fgit-blob-fc010a909c9559db169703072bd0dccacc283078%252Fpinpoint-architecture.png%3Falt%3Dmedia&width=768&dpr=2&quality=100&sign=793ab0e2&sv=1)

We plan to use specialized storage for trace and metric.
Trace -> Apache HBase
Metric -> Apache Pinot
