### ISSUE TITLE
How to delete Application v.3.0.0?

### ISSUE THREAD

**Issue by HanChanYoung** [pinpoint-apm/pinpoint#11383]
I have a question about Pinpoint web.

In version 2.5.x, I used the admin API 
`/admin/removeApplicationName.pinpoint?applicationName=$APPLICATION_NAME&password=$PASSWORD ` to delete an application, but this API doesn't work in version 3.0.0.

When I checked the sites https://pinpoint-apm.gitbook.io/pinpoint/faq , it says the admin API returns a 404 error. 
Could you please tell me how to delete an application in 3.0.0?

![image](https://github.com/user-attachments/assets/5f02ea61-211c-4b77-a92d-8ef80d68d51f)

**Comment by emeroad** [comment]
Since 3.0.0, the `/api` prefix has been added to URL

- /api/admin/~~~

**Comment by HanChanYoung** [comment]
I Solved that isuue
`/api/admin/removeApplicationName?applicationName=$APPLICATION_NAME&password=$PASSWORD`
@emeroad Thanks for your reply! Have a nice day!
