### ISSUE TITLE
[web] config.show.*=false do not work in UI V3

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#11381]
#### What version of pinpoint are you using?
3.0.0

#### Describe the bug
config.show.systemMetric=false
config.show.urlStat=false
config.show.exceptionTrace=false

When these features are disabled (no pinot), the left submenus are  still shown. UI V2 works, but not UI V3.
![image](https://github.com/user-attachments/assets/d53fec61-8d1c-4b0e-a576-220c150064a2)

#### Expected behavior
system metrics / url stat / exception trace menus should be hidden.

**Comment by binDongKim** [comment]
This has been fixed through https://github.com/pinpoint-apm/pinpoint/commit/88f348f18cb3965fcce57e9fda0b5aba0e0efca0

**Comment by yjqg6666** [comment]
Any schedule time for the release v3.0.1 ?
