### ISSUE TITLE
Can I continue to use Pinpoint1.8.1 when I upgrade my SpringBoot2 application to SpringBoot3?

### ISSUE THREAD

**Issue by wxy0724** [pinpoint-apm/pinpoint#11443]
Can I continue to use Pinpoint1.8.1 when I upgrade my SpringBoot2 application to SpringBoot3?

**Comment by donghun-cho** [comment]
Support for Spring Boot 3 has been added recently
So it is recommended to use the latest version(2.5.4, 3.0.0)
