### ISSUE TITLE
[FR.] Inspector menu in UI v3 side-navigation can be configured hidden

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#11464]
**Which module is your feature request related to?**
UI

**Is your feature request related to a problem?**
The new inspector feature relies on Apache Pinot and if pinpoint is deployed without using *-starter-<version>-exec.jar (no Pinot involved), the new inspector is unusable and should be hidden.
![image](https://github.com/user-attachments/assets/a713fa74-3c52-4b99-801a-bde0f30f69cc)

**Describe the solution you'd like**
The new inspector menu in UI v3 can be configured hidden from the web application.
PR #11518 have been made for this issue.

**Comment by yjqg6666** [comment]
@binDongKim @emeroad The feature has been completed by PR #11518. PTAL.

**Comment by minwoo-jung** [comment]
@yjqg6666 
Hello 
First of all, I apologize for the delay in responding.

UI version 3 is based on using pinot.
For inspector, we didn't include the invisible setting because it is a necessary default menu.

If you want to see the inspector data without using pinot, we will guide you to move the screen to UI version 2 to see the inspector data.
Since pinpoint version 3.0, we are forcing to use UI version 3.0 by default.

**Comment by yjqg6666** [comment]
@minwoo-jung How about making the default config value to "true" ? It's still shown but can be configured hidden.

**Comment by minwoo-jung** [comment]
@yjqg6666 

What you're asking about is possible. But internally we distinguish between menus that must be exposed and menus that can be optionally exposed. We have decided to expose inpsector as a required menu.
So we're trying to stick to that standard.

For now, we've decided not to make it available, but we'll think about it internally and let you know if we make any changes.
It sounds like you have a lot on your mind, and I apologize for not being able to answer positively.

**Comment by yjqg6666** [comment]
OK. Since the Pinot is kinda heavy regarding deployment and maintenance, for some scenarios, we will only deploy hbase-only pinpoint. Now the UI v3 is the default, when the user visit the inspector, the errors popped up. Not good for promotion in my org, so need hidden configuration. The user can still use UI v3, if need inspection, then go to UI v2.
