### ISSUE TITLE
PINPOINT V3 user and user groups insert properly but not display in UI

### ISSUE THREAD

**Issue by pradeepgunsgmail** [pinpoint-apm/pinpoint#11496]
hi all,

I have deployed and configured pinpoint V3 with separate KAFKA cluster, PINOT cluster, MYSQL cluster and Redis. All functions are working perfectly other than User and User Group. I’m able to create users and user groups and MYSQL database also updated properly. But I’m not able to see user, user group over web UI. I can Insert through web UI but not display. Also, no user and user group mapping available. I’ve described property files and start command in below. Please help me to resolve this issue. 

*### *collector**
collector-starter-application.yml
------------------------------------
pinpoint:
  zookeeper:
    address: localhost
  metric:
    kafka:
      bootstrap:
        servers: 192.168.62.112:9092
spring:
  pinot-datasource:
    pinot:
      jdbc-url: jdbc:pinot://192.168.62.113:9001
      username: admin
      password: admin

Collector start using 
java -jar -Dspring.redis.username=default -Dspring.redis.password='' -Dspring.config.additional-location=collector-starter-application.yml pinpoint-collector-starter-3.0.0-exec.jar

**### web**
web-starter-application.yml
---------------------------

pinpoint:
  modules:
    webhook:
      web:
        webhook: true
  zookeeper:
    address: localhost
spring:
  pinot-datasource:
    pinot:
      jdbc-url: jdbc:pinot://192.168.62.113:9001
      username: admin
      password: admin
      tenantId: pinpoint
broker:
        addresses:
          - 192.168.62.113:7001
          - 192.168.62.114:7002
web start using 
java -jar -Dpinpoint.modules.webhook.web.webhook=true -Dspring.config.additional-location=web-starter-application.yml pinpoint-web-starter-3.0.1-SNAPSHOT-exec.jar

**### batch**
batch-starter-application.yml
-----------------------------
pinpoint:
  zookeeper:
    address: localhost
  metric:
    kafka:
      bootstrap:
        servers: 192.168.62.112:9092
spring:
  pinot-datasource:
    pinot:
      jdbc-url: jdbc:pinot://192.168.62.113:9001
      username: admin
      password: admin

jdbc.properties
----------------
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/pinpoint
spring.datasource.hikari.username=admin
spring.datasource.hikari.password=C0lumnStore!
spring.datasource.hikari.pool-name=HikariPool-main-dataSource-local
spring.datasource.hikari.minimum-idle=3
spring.meta-datasource.hikari.minimum-idle=3

batch start using
java -jar -Dpinpoint.zookeeper.address=localhost -javaagent:/opt/agent/pinpoint-bootstrap.jar -Dspring.config.additional-location=batch-starter-application.yml pinpoint-batch-3.0.1-SNAPSHOT-exec.jar 

![image](https://github.com/user-attachments/assets/06457314-584e-42e0-a7eb-7f82b760179e)

![image](https://github.com/user-attachments/assets/2b8853ae-4f5e-4490-b37b-62b308b5eea0)

![image](https://github.com/user-attachments/assets/3001d6a1-d1bb-47ec-b1e1-eb26a95cf64f)

![image](https://github.com/user-attachments/assets/b9c07b10-d346-4e05-b64a-46222f28c08a)

thanks,
Pradeep

**Comment by minwoo-jung** [comment]
@pradeepgunsgmail 
To summarize your question, I understand that you are asking because you have data, but the web UI does not output the data.

1. Please check the logs output by the web server first to see if there is anything unusual.
2. Also check the UI console logs to make sure there are no error logs.
