### ISSUE TITLE
The value of agentid is HOSTNAME in the pod, but the error length cannot exceed 24. How can I change it to get the value of HOSTNAME

### ISSUE THREAD

**Issue by hdsfgsgrlsgtw12** [pinpoint-apm/pinpoint#11509]
version：pinpoint-agent-3.0.0

logs：
09-20 16:27:57.237 INFO  IdValidator                         : check SystemProperties(-D) agentId:toc-task-server-699d5cd7b8-5nv55
09-20 16:27:57.238 INFO  IdValidator                         : invalid Id. SystemProperties(-D) agentId can only contain [a-zA-Z0-9], '.', '-', '_'. maxLength:24 value:toc-task-server-699d5cd7b8-5nv55

-javaagent:/usr/local/pinpoint-agent/pinpoint-bootstrap.jar
-Dpinpoint.agentId=${HOSTNAME} -Dpinpoint.applicationName=${PINPOINT_GROUP}

**Comment by yjqg6666** [comment]
-Dpinpoint.agentName=${HOSTNAME} -Dpinpoint.applicationName=${PINPOINT_GROUP}
-javaagent:/usr/local/pinpoint-agent/pinpoint-bootstrap.jar

Assign the hostname to agentName instead. AgentId would be set to a automatically generated value.

**Comment by hdsfgsgrlsgtw12** [comment]
thank you
