### ISSUE TITLE
Questions Regarding Pinpoint v3.0.0 Upgrade and Features

### ISSUE THREAD

**Issue by jaca-p** [pinpoint-apm/pinpoint#11588]
Hello,

I am currently using "Pinpoint" v2.3.3 and planning to upgrade to v3.0.0.

As I was reviewing the changes in v3.0.0, I had some questions and would appreciate your help.

1. Is the "New Inspector" mentioned in 3.0.0 the default Inspector that is separate from the Application Inspector? (I have checked on the legacy Inspector and legacy Application Inspector.)

2. In the 3.0.1 release, will the New Inspector not support Hbase and instead store all data in Pinot?

3. Is there a planned release date for the 3.0.1 update?

4. I noticed some commits related to OpenTelemetry. Will OTLP be supported?

I would like to express my gratitude for your hard work.

**Comment by emeroad** [comment]
> 1. Is the "New Inspector" mentioned in 3.0.0 the default Inspector that is separate from the Application Inspector? (I have checked on the legacy Inspector and legacy Application Inspector.)
  - New Inspecotr : pinot
    Legacy Inspector : hbase
    As shown above, the two features use different databases.
    Legacy inspector will be deprecated in a future release.
> 2. In the 3.0.1 release, will the New Inspector not support Hbase and instead store all data in Pinot?
  - ![Architecture](https://pinpoint-apm.gitbook.io/~gitbook/image?url=https%3A%2F%2F2967689678-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252F-MgQ1Is59jDrgEN5nG-0-3931491796%252Fuploads%252Fgit-blob-fc010a909c9559db169703072bd0dccacc283078%252Fpinpoint-architecture.png%3Falt%3Dmedia&width=768&dpr=4&quality=100&sign=793ab0e2&sv=1)
  Pinpoint plans to use a mix of the two databases as shown above.
     Trace : Apache hbase
      Metric : Apache pinot
> 3. Is there a planned release date for the 3.0.1 update?
  - It will be released this month.
> 4. I noticed some commits related to OpenTelemetry. Will OTLP be supported?
  - We will support OTEL metrics in pinpoint 3.1.0.
