### ISSUE TITLE
Wondering if Pinpoint Agent 2.5.4 supports Vert.x version 4.2.5.

### ISSUE THREAD

**Issue by lkh2919** [pinpoint-apm/pinpoint#11662]
I am Wondering if Pinpoint Agent 2.5.4 supports Vert.x version 4.2.5.

In the comments of the github source code of the 2.5.4 agent plugin, the range is up to 4.2.2, 

but I wonder if version 4.2.5 is not supported.

Because the README file says that version 4.X is supported.

**Comment by jaehong-kim** [comment]
The pinpoint agent 2.5.4 version supports vert.x 4.2.5 version.
It also supports versions from pinpoint agent 3.0 to vert.x 4.5 and later.
