### ISSUE TITLE
web chat 404

### ISSUE THREAD

**Issue by srchen1987** [pinpoint-apm/pinpoint#11698]
jdk21

pinpoint v3.0.1

웹에서 오류가 발생했습니다. 캡처는 다음과 같습니다.
모두 404

![A85FB665D7BFC17288033C82A57783EE](https://github.com/user-attachments/assets/aeafa582-88cc-4266-9d7f-cb921e6d955a)

**Comment by minwoo-jung** [comment]
Hello @srchen1987 
Please refer to the guide article below to enable the feature.
https://pinpoint-apm.gitbook.io/pinpoint/documents/new-inspector

**Comment by srchen1987** [comment]
> Hello @srchen1987 Please refer to the guide article below to enable the feature. https://pinpoint-apm.gitbook.io/pinpoint/documents/new-inspector

txh
