### ISSUE TITLE
Is It Possible to Use Pinpoint Agent Data Externally?

### ISSUE THREAD

**Issue by 1sonjm** [pinpoint-apm/pinpoint#11744]
Hello,

I am currently using Pinpoint 2.5.3 with HBase 1.2.7 to monitor agent data.

To check if the agent's status data can be further processed and utilized, I tried examining the data using Apache Drill. However, it seems decryption is required.

Is it possible to use the data collected by Pinpoint agents externally?

**Comment by emeroad** [comment]
All data is binary encoded, so decoding is required to read the data.
See the Dao class
