### ISSUE TITLE
Support a collector API (and maybe an agent) for Node.js

### ISSUE THREAD

**Issue by chalford** [pinpoint-apm/pinpoint#1759]
This product looks great!

Our organisation has a very diverse set of languages in use, and I'm wondering if there are any plans to support a collector API for Node.js (for manually instrumenting where required), and potentially a Node.js agent, similar to New Relic's: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/new-relic-nodejs

**Comment by nstopkimsk** [comment]
we really want to support other platforms including node.js, php ,  .NET, and so on.
but we are small team and need open source contributors.

**Comment by pparth** [comment]
+1 to this.

**Comment by RVN-BR** [comment]
+1

**Comment by hulutter** [comment]
+1

**Comment by peaksnail** [comment]
I have released the poinpoint node agent on github  https://github.com/peaksnail/pinpoint-node-agent
feel free to let me know it works for you

**Comment by nstopkimsk** [comment]
@peaksnail great !!  Pinpoint team will introduce third party agents including your node.

**Comment by iwin4aids** [comment]
collector api should be considered as well, base on this , contributors can develop no-java platform agent

**Comment by shaggybb** [comment]
+1

**Comment by g0ne150** [comment]
Any good news?

**Comment by wsxkzs** [comment]
+1

**Comment by stunstunstun** [comment]
+1

**Comment by gentlejo** [comment]
+1

**Comment by Emrys5** [comment]
+10086

**Comment by immusk** [comment]
any update on this
Do we have any pinpoint agent that supports Nodejs?
