### ISSUE TITLE
Add RocketMQ plugin

### ISSUE THREAD

**Issue by stanvl** [pinpoint-apm/pinpoint#1942]
RocketMQ is a fast, reliable, scalable, easy to use message oriented middleware breeding from alibaba massive messaging business.

**Comment by Xylus** [comment]
Hi stanvi,
We have an on-going PR for adding RocketMQ plugin (#1783)
Please do check it out~

**Comment by koo-taejin** [comment]
This issue is resolved via #7529 PR.
