### ISSUE TITLE
Pinpoint for mule

### ISSUE THREAD

**Issue by cpresario** [pinpoint-apm/pinpoint#3425]
#### Description
Hi!,

Does Pinpoint work with mule? I added an agent to mule arguments, but Pinpoint shows nothing. Do I need a custom agent?

Hope you can help me.

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @cpresario 
We don't support mule currently so I think that's why your not getting any traces.
Unfortunately, none of us are really familiar with mule so it'd be great if you could create a plugin for mule and throw us a PR if you'd like.
