### ISSUE TITLE
Does it support play framework 2.x ? 

### ISSUE THREAD

**Issue by panqiushi** [pinpoint-apm/pinpoint#355]
I give -javaagent: option in app startup, but didn't receive any data. I directly use the pinpoint/quickstart/agent/target/pinpoint-agent/pinpoint-bootstrap-1.0.5-SNAPSHOT.jar  and also give the agentId and applicationName. Did I do some thing wrong?

**Comment by nstopkimsk** [comment]
Sadly not yet support play framework. 
Pinpoint team will release plugin system and guide documents for contributors to implement easily plugins that  they want to profile.  Pinpoint team really want to be contributed for not supported things.
If there is no contributors, pinpoint team will support play framework. But the priority is not high.

**Comment by panqiushi** [comment]
Thanks for replay!

/BR

**Comment by DavenAaron** [comment]
Does it support play framework 2.x ?  now
