### ISSUE TITLE
when resin3.x  wile be surported?

### ISSUE THREAD

**Issue by linuxmyjob** [pinpoint-apm/pinpoint#3668]
when resin3.x  wile be surported?
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @linuxmyjob 
There's no plan to support resin 3.x currently.
It'll be great if you could add it's support to the resin plugin and throw us a pull request.
