### ISSUE TITLE
could pinpoint support dynamic modify configuration，something like sampler enable/sampling rate

### ISSUE THREAD

**Issue by snakedragon** [pinpoint-apm/pinpoint#3774]
I would like to implement a online apm using pinpoint, we have a requirement of dynamic modification of sampling and sampling rate,  do we have this feature already?

**Comment by koo-taejin** [comment]
hi snakedragon

Pinpoint does not support to change sampling rate .
Implementing this feature is not difficult.
However, we are approaching carefully because of the performance impact of the profiler, how to execute it, and permissions issues.

In conclusion, we have no plans to provide this yet.

Thank you.

**Comment by snakedragon** [comment]
could you tell me how to implement this feature in short words?
could we maintain a singleton pinpoint-config instance, and all sample rating is conducted from it? so when the pinpoint.config instance's sampling rating changed, all sampling rating is changed accordingly?

**Comment by snakedragon** [comment]
thanks for your replay,  by the way.

**Comment by koo-taejin** [comment]
1. create DynamicSampler (allows to change the samplingRate field.(non final field) )
2. create commandService for to change Sampling rate
3. create restapi for to sampling rate commandservice
The above things is the simple way I think,

If support function, (more should be considered. (the performance impact of the profiler, how to execute it, and permissions issues.))

**Comment by yhy-git** [comment]
Is this problem solved?What can be explained in detail?for example,which class?
