### ISSUE TITLE
1.7.2 web datetime picker UI dislocation

### ISSUE THREAD

**Issue by gaoyf** [pinpoint-apm/pinpoint#3982]
Hi , as title, see the screenshot:
![image](https://user-images.githubusercontent.com/10137071/38291925-5b6cb24a-3814-11e8-931b-3e1bcb357d61.png)

I change width from 342px to 386px, it's OK! , see the screenshot:
![image](https://user-images.githubusercontent.com/10137071/38292117-1e91d598-3815-11e8-8de1-62794cd94079.png)

My browser is Google Chrome  65.0.3325.181（32 bit）.
IF you cannot reproduce this bug please ignore this feedback (*^_^*).

**Comment by denzelsN** [comment]
@gaoyf 
Hi. What is your OS?

**Comment by gaoyf** [comment]
My OS is win10 pro, version is bellow:
Version: 1607
OS Version: 14393.2125
