### ISSUE TITLE
Pinpoint Apdex Scores??

### ISSUE THREAD

**Issue by ing-arriola** [pinpoint-apm/pinpoint#4044]
#### Description

I have previously used two tools for APM, one called "Applications Manager" and another called "Retrace" and I think Pinpoint has better features than both; with only one detail that both tools show something called the APDEX Score which is according to both mention in their official documentation an industry standard to measure the "level of customer satisfaction". I do not know if Pinpoint is able to show this parameter or if there are plans for it to be incorporated?
I include a link with documentation about it.

http://apdex.org/overview.html

#### Environment

* Pinpoint version:1.8.0 SNAPSHOT
* OS, WAS, affected library, etc:Ubuntu Server 16.04 LTS

**Comment by Xylus** [comment]
Hi @ing-arriola 
Thank you sharing this.
We currently do not have any plans to incorporate it any time soon.

However this looks like something we can consider once we have more data aggregation (such as response time / request count by URLs etc) implemented,
Thanks again.

**Comment by ing-arriola** [comment]
Hi @Xylus 
thanks for your answer, it would be great if Pinpoint could show you APDEX Score. =D

**Comment by woutersamaey** [comment]
We’re 2 years later. Do we have Apdex now? I personally like this metric as it is something that can easily be shared with management.

**Comment by emeroad** [comment]
We have plans to support apdex scores

Apdex score can be calculated based on histogram.
- https://en.wikipedia.org/wiki/Apdex

![image](https://user-images.githubusercontent.com/7564547/84739802-3f264400-afe7-11ea-9833-0838c6baf47d.png)

![image](https://user-images.githubusercontent.com/7564547/84739945-798fe100-afe7-11ea-9f75-da3741be26d9.png)
eg)
SatisfiedCount : 729,516  * 1
ToleratingCount : 1,856 * 0.5 = 928
TotalSamples : 732,357
Appdex score : 0.997 <- (729,516 + 928) / 732,357

**Comment by yjqg6666** [comment]
@emeroad Where would the scores be shown? I have not found any changes on UI side.
