### ISSUE TITLE
after selected right pop menu "Link Routing" on servermap, the servermap has nothing change and throw js error in console of browser

### ISSUE THREAD

**Issue by bigsnapdragon** [pinpoint-apm/pinpoint#4334]
**What version of pinpoint are you using?**
v1.7.2 
browser: used chrome 

**Describe the bug**
after selected right pop menu "Link Routing" on servermap, the servermap has nothing change and throw js error in console of browser

**What did you do to trigger the bug?**
Steps to reproduce, for example:
1. selected right pop menu "Link Routing" on servermap
2. the servermap has nothing changed
3. throw js error in console of browser

**Screenshots**
![qq 20180704161250](https://user-images.githubusercontent.com/17841615/42266246-70e978c0-7fa8-11e8-8d99-fe7b82a5ea36.png)
![qq 20180704163718](https://user-images.githubusercontent.com/17841615/42266283-8c330402-7fa8-11e8-82e6-8df72d5213da.png)

**Comment by denzelsN** [comment]
hi @bigsnapdragon 
Thank you. your bug reporting.
I will check that.
