### ISSUE TITLE
How can I get response status in Tomcat Plugin

### ISSUE THREAD

**Issue by thisisgpy** [pinpoint-apm/pinpoint#4435]
I have try to do followings:

[Tomcat Plugin] StandardHostValveInvokeInterceptor#after()

`HttpServletResponse response = (HttpServletResponse) args[1];`

But I can not invoke `getStatus()`, because HttpServletResponse not support. Now I want to know wether the request is success, so How can I get response status ?

**Comment by jaehong-kim** [comment]
@ganpengyu 
Please refer to the code below.
https://github.com/naver/pinpoint/blob/992ae5f6a1a84645c78df44623859ae6adec68f3/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java#L114
