### ISSUE TITLE
Is there a way to see directly when service is down?

### ISSUE THREAD

**Issue by stoneLee81** [pinpoint-apm/pinpoint#4539]
<img width="462" alt="d9d7249d-970e-4149-9f0a-05fc2a8029ee" src="https://user-images.githubusercontent.com/18001708/44516799-9bc0bc80-a6f8-11e8-9a85-de9aaae91369.png">

For instance, the soa_em deployed on 2 machines, when one service is down for testing, Is there a way to know when one machine service is down and notify me, or I can know directly which service of machine is down through this webui?

**Comment by stoneLee81** [comment]
Is there a way to count down the soaem num from 2 to be 1 when the instance service is down? When that instance is up, then add num from 1 to 2. That will be easy to know through this webui.

**Comment by Xylus** [comment]
@stoneLee81 
If the instance does not have receive/send any requests in the time period used to query the server map, AND the instance is currently not running, it is removed from the count.
I believe the number of instances for the node in your server map is staying at 2 because it has received or sent requests during the server map time period.

**Comment by stoneLee81** [comment]
But the truth is that the spring boot admin shows that instance is down, and the process didn't exist in centos sys, and the count is still 2
<img width="1070" alt="a1d96dcb-afa3-4a18-8230-07362bcb3cc1" src="https://user-images.githubusercontent.com/18001708/44523973-78087100-a70e-11e8-8fcd-74a16f67e19c.png">
<img width="665" alt="a3e6f246-479d-4c2d-a468-e9b9c1d7d913" src="https://user-images.githubusercontent.com/18001708/44524002-8d7d9b00-a70e-11e8-9d85-0983b8704a21.png">

**Comment by stoneLee81** [comment]
<img width="454" alt="d11f4c4c-6c1c-4db5-9a8b-aa14ce353636" src="https://user-images.githubusercontent.com/18001708/44524047-ab4b0000-a70e-11e8-9bec-63658e2e69d6.png">

**Comment by stoneLee81** [comment]
any suggestions?

**Comment by Xylus** [comment]
Did *soabiz13* have any requests during the time period used for querying the server map?

**Comment by Xylus** [comment]
Either way, you can check if an instance is down in real time by clicking on the "REAL TIME" button like you have done 2 posts above.

**Comment by stoneLee81** [comment]
For testing, I killed that soabiz13 process by command, and in the webui I clicked 'REAL TIME' button, still show 2 posts above.

**Comment by Xylus** [comment]
Yes, and that is correct given *soabiz13* had requests during the time period for the server map query.
The number shown in the node doesn't show how many instances are running **right now**. It is the number of instances that had requests during the time period of the server map (regardless of whether it's running right now or not). plus the number of currently running instances that did not have any requests during the time period.
