### ISSUE TITLE
Load module failed with pp-web v1.8.0 in Chrome

### ISSUE THREAD

**Issue by jujis008** [pinpoint-apm/pinpoint#4864]
**What version of pinpoint are you using?**
release pinpoint-web v1.8.0.

**Describe the bug**
Well, I'm facing the problem when initializing the index page, it tell me that 
`angular-lib.min.js?v=1536900095837:formatted:13 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.18/$injector/modulerr?p0=pinpointApp&p1=Error%3A%20%5Bng%3Aareq%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.18%2Fng%2Fareq%3Fp0%3Dfn%26p1%3Dnot%2520a%2520function%252C%2520got%2520string%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A6%3A450%0A%20%20%20%20at%20Cb%20(http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A19%3A68)%0A%20%20%20%20at%20Ta%20(http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A19%3A155)%0A%20%20%20%20at%20sc%20(http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A32%3A351)%0A%20%20%20%20at%20Object.%24provide.(anonymous%20function)%20%5Bas%20factory%5D%20(%3Canonymous%3E%3A702%3A26)%0A%20%20%20%20at%20c.a%20%5Bas%20register%5D%20(http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A124%3A225)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A33%3A326%0A%20%20%20%20at%20Array.forEach%20(%3Canonymous%3E)%0A%20%20%20%20at%20q%20(http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A7%3A280)%0A%20%20%20%20at%20e%20(http%3A%2F%2Flocalhost%3A28081%2Flib%2Fjs%2Fangular-lib.min.js%3Fv%3D1536900095837%3A33%3A139)
    at angular-lib.min.js?v=1536900095837:formatted:13
    at angular-lib.min.js?v=1536900095837:formatted:845
    at Array.forEach (<anonymous>)
    at q (angular-lib.min.js?v=1536900095837:formatted:29)
    at e (angular-lib.min.js?v=1536900095837:formatted:826)
    at ec (angular-lib.min.js?v=1536900095837:formatted:939)
    at c (angular-lib.min.js?v=1536900095837:formatted:347)
    at dc (angular-lib.min.js?v=1536900095837:formatted:359)
    at Wc (angular-lib.min.js?v=1536900095837:formatted:332)
    at HTMLDocument.<anonymous> (angular-lib.min.js?v=1536900095837:formatted:6531)`
so I follow the link which tell me 
`Error: $injector:modulerr
Module Error
Failed to instantiate module pinpointApp due to:
Error: [ng:areq] http://errors.angularjs.org/1.2.18/ng/areq?p0=fn&p1=not%2...
    at http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:6:450
    at Cb (http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:19:68)
    at Ta (http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:19:155)
    at sc (http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:32:351)
    at Object.$provide.(anonymous function) [as factory] (:702:26)
    at c.a [as register] (http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:124:225)
    at http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:33:326
    at Array.forEach ()
    at q (http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:7:280)
    at e (http://localhost:28081/lib/js/angular-lib.min.js?v=1536900095837:33:139
Description
This error occurs when a module fails to load due to some exception. The error message above should provide additional context.

In AngularJS 1.2.0 and later, ngRoute has been moved to its own module. If you are getting this error after upgrading to 1.2.x, be sure that you've installed ngRoute.`

**What did you do to trigger the bug?**
simple to trigger, open main page.
**NOTE:** only happens in **CHROME v69.0.3497.100**
I don't know if it has been fixed this one, if it does please close the issue immediately. Thank you

Regards,
Wilson

**Comment by denzelsN** [comment]
HI @jujis008 
I downloaded the [1.8.0](https://github.com/naver/pinpoint/releases/download/1.8.0/pinpoint-web-1.8.0.war) file, installed and run it and it works fine. 
How did you install and run it?

**Comment by jujis008** [comment]
I just follow the normal steps, download tomcat and extract war file into webapps/ROOT directory. Agent files referenced by my app tomcat, everything works good in Firefox and Safari. Only chrome fails to loading main page and caught errors in console Dev Tool. Here my env configs:
OS: Mac osx
JDK: v1.8
tomcat: v7.0
Hbase: v2.1.1
pp-col & pp-web & agent: v1.8.0
Chrome: v69.0.3497.100
Firefox: v51.0.1 (64-bit)

Thank you.
Regards
Wilson

**Comment by denzelsN** [comment]
@jujis008  
If you're getting errors only with chrome, try deleting the chrome extension. Sometimes an extension causes an error.

**Comment by jujis008** [comment]
@denzelsN thanks for reminder, I'll try and give feedback here.

**Comment by jujis008** [comment]
@denzelsN Great thanks.
 As I remove the AngularJS inspector plugin it works now.
