### ISSUE TITLE
LoadBalance between pinpoint-collector cluster via nginx

### ISSUE THREAD

**Issue by spenxu** [pinpoint-apm/pinpoint#5931]
Hi, pinpoint team : 
I encountered problems when using pinpoint-collector clusters via nginx. we deployed two instances of pinpoint-collector . and implements loadbalance via nginx. our config as below:

agent-side(we use domain instead of ip):
`profiler.collector.ip=collectors.xxx.com`

nginx config:
```
upstream tcp_upstreams {
    server ip01:9994;
    server ip02:9994;
}

server {
    listen 9995 udp;
    proxy_pass 9995_udp_upstreams;
    proxy_timeout 1s;
    proxy_responses 1;
}

server {
    listen 9996 udp;
    proxy_pass 9996_udp_upstreams;
    proxy_timeout 1s;
    proxy_responses 1;
}

server {
    listen 9994;
    proxy_pass tcp_upstreams;
    proxy_timeout 1s;
}
```
and now ,we remove the two collector server instance to another two boxes. and the new ip is ip03,and ip04.so we change nginx config as below:

```
upstream tcp_upstreams {
    server ip03:9994;
    server ip04:9994;
}

server {
    listen 9995 udp;
    proxy_pass 9995_udp_upstreams;
    proxy_timeout 1s;
    proxy_responses 1;
}

server {
    listen 9996 udp;
    proxy_pass 9996_udp_upstreams;
    proxy_timeout 1s;
    proxy_responses 1;
}

server {
    listen 9994;
    proxy_pass tcp_upstreams;
    proxy_timeout 1s;
}
```

The problem is : the agent‘s requests is actually attached to the new collector instance ,but the new collector server cannot parse the requests correctly! do you have any ideas?

<img width="1403" alt="图片" src="https://user-images.githubusercontent.com/29301435/63908265-26956f00-ca51-11e9-9a11-e8c22ff23c10.png">

**Comment by superbool** [comment]
Same problem. How to set collector loadbalance.

**Comment by yjqg6666** [comment]
@superbool You may checkout these links: 
https://gist.github.com/nginx-gists/87ed942d4ee9f7e7ebb2ccf757ed90be
https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-3-publishing-grpc-services/
https://github.com/kubernetes/ingress-nginx/issues/5609
http://nginx.org/en/docs/http/ngx_http_grpc_module.html

**Comment by yjqg6666** [comment]
@superbool  My working config:


proxy-grpc.http (included in nginx http section)

> upstream ppc-grpc-base-9991 {
>     server collector1:9991 max_fails=10 fail_timeout=30s;
>     server collector2:9991 max_fails=10 fail_timeout=20s;
> }
> 
> upstream ppc-grpc-stat-9992 {
>     server collector1:9992 max_fails=10 fail_timeout=30s;
>     server collector2:9992 max_fails=10 fail_timeout=20s;
> }
> 
> upstream ppc-grpc-span-9993 {
>     server collector1:9993 max_fails=10 fail_timeout=30s;
>     server collector2:9993 max_fails=10 fail_timeout=20s;
> }
> 
> server {
>     listen 0.0.0.0:9991 http2;
>     access_log /var/log/ppc-gbase-access.log grpc_json;
>     \# reference: http://nginx.org/en/docs/http/ngx_http_grpc_module.html
>     include snippets/grpc-pass.conf;
>     include snippets/grpc-error.conf;
>     location / {
>         grpc_pass grpc://ppc-grpc-base-9991;
>     }
> }
> 
> server {
>     listen 0.0.0.0:9992 http2;
>     access_log /var/log/ppc-gstat-access.log grpc_json;
> 
>     include snippets/grpc-pass.conf;
>     include snippets/grpc-error.conf;
> 
>     location / {
>         grpc_pass grpc://ppc-grpc-stat-9992;
>     }
> }
> 
> server {
>     listen 0.0.0.0:9993 http2;
>     access_log /var/log/ppc-gspan-access.log grpc_json;
>     \# reference: http://nginx.org/en/docs/http/ngx_http_grpc_module.html
>     include snippets/grpc-pass.conf;
>     include snippets/grpc-error.conf;
>     location / {
>         grpc_pass grpc://ppc-grpc-span-9993;
>     }
> }

proxy-thrift.stream  (included in nginx stream section)

> upstream ppc-thrift-base-9994 {
>     server collector1:9994 max_fails=10 fail_timeout=30s;
>     server collector2:9994 max_fails=10 fail_timeout=20s;
> }
> 
> upstream ppc-thrift-stat-9995 {
>     server collector1:9995 max_fails=10 fail_timeout=30s;
>     server collector2:9995 max_fails=10 fail_timeout=20s;
> }
> 
> upstream ppc-thrift-span-9996 {
>     server collector1:9996 max_fails=10 fail_timeout=30s;
>     server collector2:9996 max_fails=10 fail_timeout=20s;
> }
> 
> server {
>     listen 0.0.0.0:9994;
>     access_log /var/log/ppc-thrift-base-access.log ppc;
>     proxy_pass ppc-thrift-base-9994;
>     proxy_timeout 10s;
>     proxy_connect_timeout 2s;
> }
> server {
>     listen 0.0.0.0:9995;
>     access_log /var/log/ppc-thrift-stat-access.log ppc;
>     proxy_pass ppc-thrift-stat-9995;
>     proxy_timeout 10s;
>     proxy_connect_timeout 2s;
> }
> server {
>     listen 0.0.0.0:9996;
>     access_log /var/log/ppc-thrift-span-access.log ppc;
>     proxy_pass ppc-thrift-span-9996;
>     proxy_timeout 10s;
>     proxy_connect_timeout 2s;
> }
> 
> 

nginx.conf (only important part)

> 
> http {
> ...
>         include /etc/nginx/conf.d/*.conf;
>         include /etc/nginx/sites-enabled/*.http;
> }
> 
> stream {
>     log_format ppc '$remote_addr [$time_local] '
>                  '$protocol $status $bytes_sent $bytes_received '
>                  '$session_time "$upstream_addr" '
>                  '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';
>     include /etc/nginx/sites-enabled/*.stream;
> }

snippets/grpc-pass.conf

> 
> \# grpc_bind $remote_addr transparent;  \#enable this option make IT not working
> grpc_connect_timeout 10s;
> grpc_buffer_size 8k;
> grpc_next_upstream_timeout 3;
> grpc_next_upstream_tries 1;
> grpc_read_timeout 60s;
> grpc_send_timeout 60s;
> grpc_socket_keepalive on;

snippets/grpc-error.conf

> 
> \# \#\#
> \# Ref: https://github.com/kubernetes/ingress-nginx/issues/5609
> \# \#\#
> 
> \# Standard HTTP-to-gRPC status code mappings
> \# Ref: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md
> \#
> error_page 400 = @grpc_internal;
> error_page 401 = @grpc_unauthenticated;
> error_page 403 = @grpc_permission_denied;
> error_page 404 = @grpc_unimplemented;
> error_page 429 = @grpc_unavailable;
> error_page 502 = @grpc_unavailable;
> error_page 503 = @grpc_unavailable;
> error_page 504 = @grpc_unavailable;
> \# NGINX-to-gRPC status code mappings
> \# Ref: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
> \#
> error_page 405 = @grpc_internal; # Method not allowed
> error_page 408 = @grpc_deadline_exceeded; # Request timeout
> error_page 413 = @grpc_resource_exhausted; # Payload too large
> error_page 414 = @grpc_resource_exhausted; # Request URI too large
> error_page 415 = @grpc_internal; # Unsupported media type;
> error_page 426 = @grpc_internal; # HTTP request was sent to HTTPS port
> error_page 495 = @grpc_unauthenticated; # Client certificate authentication error
> error_page 496 = @grpc_unauthenticated; # Client certificate not presented
> error_page 497 = @grpc_internal; # HTTP request was sent to mutual TLS port
> error_page 500 = @grpc_internal; # Server error
> error_page 501 = @grpc_internal; # Not implemented
> \# gRPC error responses
> \# Ref: https://github.com/grpc/grpc-go/blob/master/codes/codes.go
> \#
> location @grpc_deadline_exceeded {
>     add_header grpc-status 4;
>     add_header grpc-message 'deadline exceeded';
>     return 204;
> }
> location @grpc_permission_denied {
>     add_header grpc-status 7;
>     add_header grpc-message 'permission denied';
>     return 204;
> }
> location @grpc_resource_exhausted {
>     add_header grpc-status 8;
>     add_header grpc-message 'resource exhausted';
>     return 204;
> }
> location @grpc_unimplemented {
>     add_header grpc-status 12;
>     add_header grpc-message unimplemented;
>     return 204;
> }
> location @grpc_internal {
>     add_header grpc-status 13;
>     add_header grpc-message 'internal error';
>     return 204;
> }
> location @grpc_unavailable {
>     add_header grpc-status 14;
>     add_header grpc-message unavailable;
>     return 204;
> }
> location @grpc_unauthenticated {
>     add_header grpc-status 16;
>     add_header grpc-message unauthenticated;
>     return 204;
> }
> 
> default_type application/grpc;   # Ensure gRPC for all error responses
