### ISSUE TITLE
profiler.sampling.rate restricts rate options

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#6617]
**Which module is your feature request related to?**
agent

**Is your feature request related to a problem?**
The current supported sampling rate can only be 100%(n=1), 50%(n=2), 33%(n=3), 25%(n=4) and some other rates which are less and less.  If i wanna the sampling rate to be 80%, it can not be supported. 

**Describe the solution you'd like**
The sampling rate can be n out of 100.  It is 50% when n is 50.
https://github.com/naver/pinpoint/blob/2cc86076ff58f2a2bb9273fb99c4fd3410e1e60e/profiler/src/main/java/com/navercorp/pinpoint/profiler/sampler/SamplingRateSampler.java#L42-L46   
the _isSampling_ method may need a new algorithm.

**Comment by yjqg6666** [comment]
Made a new PR #7998 for this issue.

**Comment by emeroad** [comment]
Now supports percentage for sampling.

profiler.sampling.percent.sampling-rate=100  //  100%
profiler.sampling.percent.sampling-rate=50  //  50%
profiler.sampling.percent.sampling-rate=0.1  // 0.1%
profiler.sampling.percent.sampling-rate=0.01  // 0.01%

```
# support 2 types, COUNTING(default) and PERCENT.
# If this value set to COUNTING(default), sampling rate is 1/n.
# If this value set to PERCENT, sampling rate is n%.
profiler.sampling.type=COUNTING

# depend on profiler.samplging.rate.type,

# if it's COUNTING(the default), then 1 out of n transactions will be sampled where n is the rate.
# eg. 1: 100%      20: 5%       100:1%
profiler.sampling.counting.sampling-rate=1
# @Deprecate : Alias for profiler.sampling.counting.sampling-rate
profiler.sampling.rate=

# if it's PERCENT, then first x transactions out of y transactions will be sampled.
# Support from 100% to 0.01%
# eg. 100: 100%    50: 50%    0.01: 0.01%
profiler.sampling.percent.sampling-rate=100
```
