### ISSUE TITLE
일정 시간이 지나면 모니터링이 중지되는 상태에 관하여 ...

### ISSUE THREAD

**Issue by leejinseok** [pinpoint-apm/pinpoint#7014]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

![image](https://user-images.githubusercontent.com/7136340/87411115-320a6e00-c602-11ea-9dc7-ef4ef7ee4e70.png)

보시는 바와 같이 처음에는 모니터링이 잘 되어서 그래프에 녹색 데이터들이 채워져서 나오다가 일정 시간이 지나면 녹색 차트가 끊기면서 위와같이 나옵니다. 어떤 문제일까요?

**Comment by binDongKim** [comment]
I'll look into it. Please rewrite it in English for the community.

**Comment by binDongKim** [comment]
It's resolved by https://github.com/pinpoint-apm/pinpoint/pull/7373
