### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by seocho2360** [pinpoint-apm/pinpoint#7093]
#### What version of pinpoint are you using?
- pinpoint ver : v2.0.3
- pinpoint-server : java Home 8 (installed java 6,7,8,9)
- agent-server : java 7 (installed java 7)

#### Describe your problem**
A clear and concise description of what is not working.
i was installed pinpoint v1.7.3. but pinpoint-web doesn't show nothing with app data.
I thought it was because of using netty. So I updated the pinpoint version 2.0.3
then the set option sampliong.rate to 1 and netty plugin true from pinpoint.config and With iptables option, 9994~9996 tcp and udp are all open.
but is still was no data.
help me please..

#### Screenshots
<img width="844" alt="pinpoint_inspector" src="https://user-images.githubusercontent.com/69448843/89847247-73b91500-dbbe-11ea-9a43-a0bfa4671ed9.PNG">
<img width="958" alt="pinpoint_main" src="https://user-images.githubusercontent.com/69448843/89847250-74ea4200-dbbe-11ea-8c76-fa1094a2c6b2.PNG">

#### Logs
[agent-pinpoint.log](https://github.com/naver/pinpoint/files/5054277/agent-pinpoint.log)
[agentServer-pinpoint.log](https://github.com/naver/pinpoint/files/5054278/agentServer-pinpoint.log)
[quickstart.collector.log](https://github.com/naver/pinpoint/files/5054279/quickstart.collector.log)
[quickstart.web.log](https://github.com/naver/pinpoint/files/5054280/quickstart.web.log)

#### Additional context
- pinpoint-agent configuration is below
![image](https://user-images.githubusercontent.com/69448843/89986690-de01b080-dcb7-11ea-8bf5-539ed7eca260.png)

**Comment by seocho2360** [comment]
help me please. as soon as possible T.T

**Comment by seocho2360** [comment]
@koo-taejin  

I installed pinpoint while watching your youtube.
Can you help me to fix the above error?

**Comment by koo-taejin** [comment]
hi @seocho2360 

Netty plugin only supported on client side, and remote trace is not supported by default.
The reason for this is that netty doesn't have own protocol, because netty is network library. 
So it is impossible to support all remote traces like other rpc plugins.

Remote trace is supported based on codec, and currently only http codec is supported.

I recommend you check the environment by checking that part.

※ Additionally, I don't have my youtube that how to install pinpoint. 

thanks :)

**Comment by seocho2360** [comment]
> 안녕하세요 @ seocho2360
> 
> Netty 플러그인은 클라이언트 측에서만 지원되며 원격 추적은 기본적으로 지원되지 않습니다.
> 그 이유는 netty가 네트워크 라이브러리이기 때문에 netty에는 자체 프로토콜이 없기 때문입니다.
> 따라서 다른 rpc 플러그인처럼 모든 원격 추적을 지원하는 것은 불가능합니다.
> 
> 코덱 기반 원격 추적이 지원되며 현재 http 코덱 만 지원됩니다.
> 
> 그 부분을 확인하여 환경을 확인하는 것이 좋습니다.
> 
> ※ 또한, 설치 방법에 대한 유튜브가 없습니다.
> 
> 감사 :)

**Comment by koo-taejin** [comment]
Please refer to our FAQ section.(https://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help)

:)

**Comment by seocho2360** [comment]
@koo-taejin 


Could you please briefly explain the setting method?
The examples in pinpoint.config are difficult to understand.

**Comment by koo-taejin** [comment]
You can trace your own method by using  below configuration.
```
// in pinpoint.config
# Needs to be a comma separated list of fully qualified method names. Wild card not supported.
profiler.entrypoint=
# Ex: foo.bar.MyClass.myMethod, foo.bar.MyClass.anotherMethod
```

**Comment by caicha** [comment]
> hi @seocho2360
> 
> Netty plugin only supported on client side, and remote trace is not supported by default.
> The reason for this is that netty doesn't have own protocol, because netty is network library.
> So it is impossible to support all remote traces like other rpc plugins.
> 
> Remote trace is supported based on codec, and currently only http codec is supported.
> 
> I recommend you check the environment by checking that part.
> 
> ※ Additionally, I don't have my youtube that how to install pinpoint.
> 
> thanks :)

hi，one of my application is based on netty,Work as  server. when  i send request to the netty server, could not monitor any data, dose pinpoint supported it? thanks

**Comment by seocho2360** [comment]
> 아래 구성을 사용하여 자신의 방법을 추적 할 수 있습니다.
> 
> ```
> // in pinpoint.config
> # Needs to be a comma separated list of fully qualified method names. Wild card not supported.
> profiler.entrypoint=
> # Ex: foo.bar.MyClass.myMethod, foo.bar.MyClass.anotherMethod
> ```
+




Is it not necessary to change the setting value of Netty in pinpoint.config?

# Netty

###########################################################

# recommend netty plugin disable, when using VERTX.

profiler.netty=false

profiler.netty.http=false

# use channel.close()

profiler.netty.channel.close=true
###########################################################
