### ISSUE TITLE
[Idea] Add some agent lifecycle extension points.

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7127]
**Which module is your feature request related to?**
agent

**Is your feature request related to a problem?**
support  agent lifecycle extension points for different stages, eg. prepare stage, start stage(pre-start/start/post-start), stop stage(pre-stop/stop/post-stop). 
If the feature is provides, in the prepare stage, the user/developer can develop their own config logic like (fetching/)setting applicationName/agentId/profile ratio per application and in the stop stage may unregister agentId from some external source.

**Describe the solution you'd like**
1. Add a ServiceLoader and a prepare stage to Agent Interface.
2. the prepare should be called before com.navercorp.pinpoint.bootstrap.PinpointStarter#start and some thing in starter could be moved to prepare stage.
3. add pre-/post- calls inside start/stop methods of DefaultAgent.

**Comment by emeroad** [comment]
It's a good idea.

Google guice can load modules dynamically.
I think it would be nice to use this function.
https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModuleFactory.java

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultModuleFactoryResolver.java

You can dynamically change the module factory with `profiler.guice.module.factory` key.

**Comment by yjqg6666** [comment]
Thanks a lot for the hint. I will try it.
