### ISSUE TITLE
add webhook of alarm in pinpoint-web

### ISSUE THREAD

**Issue by imbf** [pinpoint-apm/pinpoint#7142]
**Which module is your feature request related to?**
web

**Is your feature request related to a problem?**
Yes, I want to be informed about many rules related to a specific application from slack or jira ...

**Describe the solution you'd like**
I wish that pinpoint-web support alarm webhook feature.

if alarm event is occured that rules exceed threshold, pinpoint-web send http post request with json body to receiver server.

POST request body should have the value of pinpointurl, batchEnv, sequenceCount, applicationId, Threshold, checkerName, checkerValue, checkerName, etc.

If possible, It would be a good idea to create an example of a receiver server that connects various platforms(slack, jira, etc).

**I am going to develop this feature, If you have any comments on this feature, please give it to me.**

**Comment by imbf** [comment]
> **Which module is your feature request related to?**
> web
> 
> **Is your feature request related to a problem?**
> Yes, I want to be informed about many rules related to a specific application from slack or jira ...
> 
> **Describe the solution you'd like**
> I wish that pinpoint-web support alarm webhook feature.
> if alarm event is occured that rules exceed threshold, pinpoint-web send http post request with json body to receiver server.
> POST request body should have the value of pinpointurl, batchEnv, sequenceCount, applicationId, Threshold, checkerName, checkerValue, checkerName, etc.
> If possible, It would be a good idea to create an example of a receiver server that connects various platforms(slack, jira, etc).
> 
> I am going to develop this feature, If you have any comments on this feature, please give it to me.

**Comment by imbf** [comment]
this issue relates with #6388

**Comment by imbf** [comment]
Since the batch logic in web has been separated into module, this feature will be contributed to that module

**Comment by CristianeBorges** [comment]
Good afternoon, everyone. I need a step-by-step guide to include a Pinpoint alert in MS Teams, through Workflows > Post to a chat when a webhook request is received. I have already inserted the Webbhook and created a test alert, but the workflow has not yet been sent to MS Teams.

**Comment by ga-ram** [comment]
@CristianeBorges you have to implement a webhook receiver to convert Pinpoint webhook alarm data into MS Teams webhook format. For example for slack notification there's a sample project [here](https://github.com/doll6777/slack-receiver). It would be nice if you can contribute MS Teams webhook receiver :)
