### ISSUE TITLE
Support very simple authentication on Web

### ISSUE THREAD

**Issue by koo-taejin** [pinpoint-apm/pinpoint#7205]
#### description 
Pinpoint provides very simple authentication using Spring Profile.

* Activation
When starting the web, the following Profile should be declared.
```
-Plocal,basicAuth,-Prelease,basicAuth 
```

* Configuration 
Declares user:password in pinpoint-web.properties as follows.
(You can declare multiple people using,.)
```
# in pinpoint-web.properties
web.security.auth.user=alice:foo, bob:bar
web.security.auth.admin=eve:baz
```

* Role
 User : Can use whole function except for admin rest api 
 Admin : Can use whole function

* When accessing Pinpoint without login
![login](https://user-images.githubusercontent.com/10057874/91950494-5bf72b80-ed3b-11ea-8d64-cc76edd3e1aa.jpg)

* When accessing admin rest api without admin role 
![에러](https://user-images.githubusercontent.com/10057874/91950536-5f8ab280-ed3b-11ea-976b-970ebceaec7b.jpg)

#### Additional info 
After have completed this feature, I have plan to remove AdminAuthInterceptor class.

**Comment by unc1** [comment]
Could we please see an example of using -Plocal,basicLogin,-Prelease,basicLogin to load the web jar? That would be very helpful. I am not sure how to use the above configs in:

java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-web-boot-2.3.0.jar

Thank you.

**Comment by koo-taejin** [comment]
Hi @unc1.

You could use this via folling format. 

```
java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-web-boot-2.3.0.jar (-Plocal,basicLogin | -Prelease,basicLogin)
```

In general, profile settings (-P) should be included at the last position. 

If you use pinpoint at dev environemnt, then using local profile is recommended.
If not, then using release profile is recommended.

Thanks :)

**Comment by koo-taejin** [comment]
@unc1 

I gave you incorrect information. You can do it like below.
```
java -jar -Dpinpoint.zookeeper.address=localhost -Dspring.profiles.active=local,basicLogin pinpoint-web-boot-2.3.0.jar 
```

Thanks :)

**Comment by koo-taejin** [comment]
@unc1 

This function does not interwork between groups. We don't plan to support it at the moment.

Thanks :)

**Comment by unc1** [comment]
Hi,
So in this example:


web.security.auth.user=alice:foo, bob:bar

alice is the user 
foo is the password ???
Thanks.

**Comment by koo-taejin** [comment]
@unc1 

Yes, you are right. 

alice is user and foo is password. 

Thanks :)

**Comment by m-bilalqayoom** [comment]
@koo-taejin 
Hi, do we have logout button in application?
if yes how can we enable it or use?
thanks
