### ISSUE TITLE
[Feature request] side-bar-container alongside main server-map can be folded upwardly/rightwardly

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7211]
**Which module is your feature request related to?**
UI

**Is your feature request related to a problem?**
If the side-bar area can be hidden, the the whole main server map area could be larger for a better view, esp. when more than one inbound/outbounds are chosen.

**Comment by yjqg6666** [comment]
![image](https://user-images.githubusercontent.com/1879641/92071483-6409a680-ede1-11ea-9198-51fe89874016.png)

**Comment by binDongKim** [comment]
I agree. Maybe we could add a button at the middle-top of the left edge of the side-bar which will spread and fold the side-bar depending on the event.

**Comment by yjqg6666** [comment]
@binDongKim I made a PR #7582 for it. PTAL.
