### ISSUE TITLE
[suggestion/idea] support lite mode

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7257]
**Which module is your feature request related to?**
Plugin

**Is your feature request related to a problem?**
If a request do not need to profile as per the sampling ratio, then check for lite-mode profiling which only enable server/rpc client profiling as per the lite-mode sampling ratio, if not then no profiling(DisableTrace) for the request.  If supported, for a large-scale site, we could set a low sampling ratio for full-mode profiling and a high sampling ratio for lite-mode profiling and eventually most of the requests will have trace ids.

**Describe the solution you'd like**
1. add a sampling mode header.
2. add a property for the Trace object to identify mode.
3. Trace.canSampled() need to check service type for each plugin.

Anything else should i do/consider? TIA.

**Comment by emeroad** [comment]
It seems to be similar to enabling only rpc plugin in profile.
e.g)
`-Dpinpoint.profiler.profiles.active=lite-mode-profile`

**Comment by yjqg6666** [comment]
There are some differences. 
Let's say that the configs in my profile are profiler.sampling.rate=10 profiler.sampling.lite.rate=2. We have 100 requests. Then
in our current version 10 requests would be profiled and 90 requests would be ignored. If lite mode supported it could be that
10 requests profiled(all enabled plugins) and 45 (ie. (100 - 10) /2 ) requests profiled(all enabled server/rpc client plugins) and the left 45 requests ignored. If profiler.sampling.rate=10 and profiler.sampling.lite.rate=1, then 10 requests profiled in full mode, 90 requests profiled in lite mode and all the requests would have their trace ids.

**Comment by yjqg6666** [comment]
@emeroad I plan to use [the reserved header](https://github.com/naver/pinpoint/issues/5262) "Pinpoint-Flags" to pass the mode. Use the first bit of the short value, 0 for full mode due to backward-compatibility(current default value is 0), 1 for lite-mode. Any advice? TIA.
