### ISSUE TITLE
Have trouble when I start pinpoint-collector

### ISSUE THREAD

**Issue by mlzxdzl** [pinpoint-apm/pinpoint#7311]
When I try to start pinpoint-collector-boot-2.1.0.jar use command "java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.1.0.jar",it have an error "Web server failed to start. Port 8081 was already in use".
How can I change 8081 to another port? Because I use 8081 in another service.

**Comment by RoySRose** [comment]
Hello, @mlzxdzl 

It's spring boot, try using SPRING_PROFILES_ACTIVE env variable.
Hope you can share your results with the community.

**Comment by mlzxdzl** [comment]
@RoySRose I use --server.port to change the port,the command like "java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.1.0.jar --server.port=8083".  It can start normally,I am testing if it can be used normally.

**Comment by emeroad** [comment]
This article will be helpful.

How to Change the Default Port in Spring Boot
https://www.baeldung.com/spring-boot-change-port
