### ISSUE TITLE
How do I run an application that uses the pinpoint agent to load Java classes?

### ISSUE THREAD

**Issue by Royal-Chokobi** [pinpoint-apm/pinpoint#7312]
How do I start an application that uses the pinpoint agent to load Java classes?

a desktop development environment
-> JDK 1.8
-> The Socket-Protocol application is only a class file and a jar file used.
-> Pinpoint 2.1.0 (collector, web, agent)

for example
```linux
$java -server -javaagent:pinpoint-agent-2.1.0.jar -Dpinpoint.agentId=$AgentId -Dpinpoint.applicationNane=$AppName -classpath $CLASSPATH 

```

Normal execution is possible, but if I check it, it can't be trace.
Maybe it's a natural result..!!

If so, could you tell me how to use the pinpoint agent to trace it?

Thank you :)

**Comment by RoySRose** [comment]
Hello, @Royal-Chokobi 

Maybe this may help you. 
https://naver.github.io/pinpoint/2.1.0/faq.html#my-custom-jar-application-is-not-being-traced-help

**Comment by Royal-Chokobi** [comment]
Hi, @RoySRose 

Solved the problem!
 
Thank you!!! 👍 


> Hello, @Royal-Chokobi
> 
> Maybe this may help you.
> https://naver.github.io/pinpoint/2.1.0/faq.html#my-custom-jar-application-is-not-being-traced-help
