### ISSUE TITLE
Role Based User Access

### ISSUE THREAD

**Issue by unc1** [pinpoint-apm/pinpoint#7314]
Hello,
Is there or will there be role based user access? Would this allow restrictions to certain hosts vs. all of them? Ideally I would like to have the admin group and then basic users. Is this possible and or coming in future releases? This product looks like it would fit my needs, but one main thing is having end users with the ability to log into the collector to view things about their monitored applications. Thanks.

T

**Comment by minwoo-jung** [comment]
Hello @unc1 
Unfortunately, pinpoint provides Authentication but not Authorization(role based).

**Comment by unc1** [comment]
Thank you and I hope in future release this may be a feature.

T
