### ISSUE TITLE
sed: can't create temp file '/pinpoint-agent/pinpoint.configXXXXXX': Permission denied

### ISSUE THREAD

**Issue by Benzion18** [pinpoint-apm/pinpoint#7329]
Hi,

We have a pod container with image pinpointdocker/pinpoint-agent:2.0.4
It worked OK before, but now we get this in the container log. Pls advise:

**+ sed -i '/profiler.transport.module=/ s/=.*/=GRPC/' /pinpoint-agent/pinpoint.config
sed: can't create temp file '/pinpoint-agent/pinpoint.configXXXXXX': Permission denied**

**Comment by RoySRose** [comment]
@Benzion18 

There wasn't any change in the image of v2.0.4 for few months.
By the look of the log, you should check the permission of the file in the container.
Also, any contribution of the docker image is welcome. 
[pinpoint-docker repo](https://github.com/pinpoint-apm/pinpoint-docker)

**Comment by Benzion18** [comment]
I investigated it and found that the problem is with **OpenShift 4**. Because **use of / ( root FS) is blocked completely now**. Meaning all "sed" commands that are running inside your pinpoint-agent image will fail with "Permission denied". One of the solutions may be to use **/tmp/**pinpoint-agent directory instead of /pinpoint-agent. How can we solve this issue?

**Comment by RoySRose** [comment]
@Benzion18 
Well the easiest way is to rebuild the docker image with the components or structure that you need.
