### ISSUE TITLE
[BUG] Alarm threshold is not changed.

### ISSUE THREAD

**Issue by dave-ha** [pinpoint-apm/pinpoint#7345]
Hello,
I am currently using Pinpoint 2.0.2.

While using alarm function, I updated the number of threshold from 5 to 25. However, I am still getting an alert for 5, the old threshold.
I have restarted pinpoint as well. However, I am still getting an alert of 5 threshold instead of 25.
Would you please let me know what is going on? How is it supposed to work?

I feel like this is a bug, and the new threshold has not been applied correctly.

Please let me know what I should do if this is not a bug.

Thank you.

**Comment by minwoo-jung** [comment]
Hello @dave-ha 
Perhaps there is no problem with the logic.
It is better to change the log level of the pinpoint-web project to debug and check the log.
