### ISSUE TITLE
DubboProviderInterceptor:77  invocation.getInvoker() possibly NULL

### ISSUE THREAD

**Issue by RookieZQF** [pinpoint-apm/pinpoint#7347]
master.

#### Describe the bug
DubboProviderInterceptor:77  invocation.getInvoker() possibly NULL

use
Invoker invoker = (Invoker) target;
replace invocation.getInvoker() can fix this

**Comment by RoySRose** [comment]
> replace invocation.getInvoker() can fix this

You can make a PR for it~

**Comment by RookieZQF** [comment]
Oh, thanks

**Comment by emeroad** [comment]
Thank you for your contribution.
