### ISSUE TITLE
export call tree details to Excel?

### ISSUE THREAD

**Issue by seocho2360** [pinpoint-apm/pinpoint#7350]
1. Response time scatter chart can be exported as an image, is there any function to export call tree details to Excel?

2. When the alarm function is clicked, Exception occurred while trying to CRUD user Group information occurs. I know the reason because mysql has not been configured or installed.

Do you have any manuals related to mysql setup or installation?
If yes, please attach it.

**Comment by RoySRose** [comment]
@seocho2360 
1. Currently, No
2. please search for past issues before you ask, usually, there already is an answer. #7349

**Comment by seocho2360** [comment]
@RoySRose 
Do you have a "function to export call tree details to Excel" development plan?

I have an additional question, but pinpoint agent related logs do not occur in pinpoint-web.log and pinpoint-collector.log.

is this right?
If it is wrong, please let me know which log is occurring.

**Comment by RoySRose** [comment]
@seocho2360 
> Do you have a "function to export call tree details to Excel" development plan?

Currently no. If you'd like to make a PR for it. The team will be happy to review it.

> I have an additional question, but pinpoint agent related logs do not occur in pinpoint-web.log and pinpoint-collector.log.
is this right?
If it is wrong, please let me know which log is occurring.

pinpoint agent related logs are accumulated where pinpoint-agent bootstrap is placed.

**Comment by seocho2360** [comment]
@RoySRose 

If so, can you tell me what data is recorded in pinpoint-web.log and pinpoint-collector.log?
Currently, there is no information related to the agent of the attached file on my server.
Please check the attached log file

In quickstart.web.log, only the IP of the pinpoint server can be checked. ip was arbitrarily modified to x.x.x.x.

[quickstart.collector.log](https://github.com/pinpoint-apm/pinpoint/files/5436730/quickstart.collector.log)

[quickstart.web.log](https://github.com/pinpoint-apm/pinpoint/files/5436729/quickstart.web.log)

**Comment by RoySRose** [comment]
> If so, can you tell me what data is recorded in pinpoint-web.log and pinpoint-collector.log? 
I don't know what you're expecting. I can't list the recorded data for web and the collector logs. It can differ by the log level and would contain too many info, I can't list them all here. You should look for what you need.

agent log would be under `logs` directory where you located pinpoint-bootstrap jar file is located.

If you're looking for the logs related to mysql. It will be under pinpoint-web.log

This is so far I can tell you. Rest of them I think you can find it on your own by looking at the codes
