### ISSUE TITLE
I want to every user call to be shown in scatter chart(as a dot). What should I do?

### ISSUE THREAD

**Issue by lss9209** [pinpoint-apm/pinpoint#7364]
우선 웹과 컬렉터를 띄워서 제가 에이전트만 JVM으로 주면서 스프링 부트로 만든 jar 파일을 띄우면 핀포인트 웹이 잘 인식합니다. 이후 그 jar로 띄운 서버에서 무슨 행위를 하면 밑에 엑티브리퀘스트는 행위를 할때마다(스레드가 돌때마다) 잘 반응해요. 그런데 스캐터차트는 제가 jar파일을 실행시킨 직후 첫 행위만 점을 찍습니다. 
가령 저의 첫 행위가 회원등록하는 거였으면 회원등록을 누르면 그 행위는 점을 찍어서 콜트리로 분석까지 가능합니다. 그런데 그 다음 다시 회원등록을 누를때는 그 행위를 스캐터차트가 인식하지 못합니다(새로운 점을 찍지 않습니다!). 물론 그외 다른 행위를 할때도 스캐터차트가 점을 찍어주지 않습니다. 아예 jar실행을 중지시키고 다시 로드하면 마찬가지로 다시 로드된 jar의 첫행위만 스캐터 차트가 점을 찍습니다.
제가 원하는 거는 한 유저가 서버에 접속해서 어떤 행위를 할때마다 즉, 그 유저에 의해 어떤 메소드들이 호출될때마다 그걸 다 일일히 스캐터 차트에 점으로 찍어내고 싶습니다.
제가 추가적으로 실행해야할 설정같은게 있을까요..? 해결책을 찾고 싶습니당!!!
참고로 저는 핀포인트-도커로 2.1.0버전의 각종 웹 컬렉터를 띄웠고. 핀포인트에이전트는 따로 2.1.0버전을 받아서 인텔리제이툴을 통해 JVM argument 값을 줘서 attach 시켰습니다.
I've made web and collector done. and they well recognize my app! and The web also show active request well whenever an user make a method in the server I load in *.jar form with agent attached by JVM argument. but the problem is that the scatter chart make a point(and call tree analysis is possible for the dot) on the graph only once when a user call method in the server first time. and after the call, every call the user make is not recognized by scatter chart(It doesn't make a point). and if I turn off the server and reload the jar file. it is also same(the first method is only recognized but not every after ones). and now I want every method a user call is recognized by scatter chart What should i do it. is there any configuration I should do berfore? 
Notice, I've used pinpoint-docker 2.1.0 ver and pinpoint agent 2.1.0 ver(which is not included in docker, I've downloaded it seperately) and I've attached it to my app using JVM argument Setting in Intelli J

**Comment by minwoo-jung** [comment]
Hi @lss9209 
Please translate the title and the comments in English to share the issue with the community

**Comment by lss9209** [comment]
ok wait!

**Comment by lss9209** [comment]
I've solved the problem the key is setting profiler.sampling.rate=1 in your agent's pinpoint.config (the default was 20)

**Comment by minwoo-jung** [comment]
Glad to find the cause yourself!
