### ISSUE TITLE
pinning-2.0.2 data is not collected

### ISSUE THREAD

**Issue by gaofeng36599** [pinpoint-apm/pinpoint#7368]
I use 2.0.2 for pinpoint web and pinpoint collector. Because it is compatible with pinpoint-agent-1.8.1, I did not upgrade the agent, and the data can be collected normally. Today, when I use pinpoint-agent-2.0.2, the data can not be collected normally. What is the possible reason?

**Comment by emeroad** [comment]
https://pinpoint-apm.github.io/pinpoint/installation.html#configuration

Transport changed to grpc from pinpoint 2.0.0
Check your network ports.

**Comment by gaofeng36599** [comment]
I can pass telnet 9991 (grpc) and telnet 9994 (THRIFT). I have tested both modes and still can't work.All my environments are running on one machine, so there should be no network restrictions

**Comment by gaofeng36599** [comment]
9992 9993 is also available

**Comment by xmherz** [comment]
I have this problem, too

**Comment by gaofeng36599** [comment]
My problem has been solved

The default change collection rate is 1, change profiles / release / pinpoint- env.config in profiler.sampling.rate=1
