### ISSUE TITLE
Change permain to agentmain 

### ISSUE THREAD

**Issue by yimingtech** [pinpoint-apm/pinpoint#7374]
We have many applications, it is not practical to use agent, can you change it into attach mode

**Comment by koo-taejin** [comment]
hi @yimingtech 

Using `agentmain` method has a smaller function and range than using `premain` method.
For above reason, it is impossible to change for now.  
If you are going to make it and provide it to Pinpoint, then it will be really helpful for Pinpoint. 

thanks :)
