### ISSUE TITLE
Auto generate AgentId

### ISSUE THREAD

**Issue by emeroad** [pinpoint-apm/pinpoint#7381]
AgentID is no longer a requirement.

If AgentID is not present, the agent automatically generates it.

Agent log
```
11-05 17:22:13.251 INFO  AgentIdResolver                     : Failed to resolve AgentId(-Dpinpoint.agentId)
11-05 17:22:13.409 INFO  AgentIdResolver                     : 'BYDnVJbPR6ODxGK61qTT1A' AgentId is automatically generated
11-05 17:22:13.409 INFO  IdValidator                         : check SystemProperties(-D) applicationName:emeroad-app
11-05 17:22:13.410 INFO  AgentIdResolver                     : SystemProperties(-D) emeroad-app=emeroad-app
```
![image](https://user-images.githubusercontent.com/7564547/98226904-01c45200-1f9a-11eb-85f3-1647bab6057b.png)
![image](https://user-images.githubusercontent.com/7564547/98227024-1f91b700-1f9a-11eb-8ece-610bbf922f4c.png)

**Comment by emeroad** [comment]
Due to this change, agentId has a problem that is not human friendly.
To solve this problem, we will add a human friendly agentName field.

## agentName 
- Not unique
   - AgentName is a view-only field and is not used as a primary key
- Size limit: 254 or 255
- display pattern : agentName (agentId)
   -Dpinpoint.agentName=MyBlogService.front.001 -Dpinpoint.agentId=BYDnVJbPR6ODxGK61qTT1A
     MyBlogService.front.001(BYDnVJbPR6ODxGK61qTT1A)

**Comment by yjqg6666** [comment]
How about adding a configuration agentId.pattern=%hostname%-%ip%  (support %hostname%, %ip%, %uuid%). The end user can decide.

**Comment by emeroad** [comment]
It's good. I have the same idea.

```
-DagentName=${hostname}-${ip}-${uuid}
```

The bracket(${...}) should have been shell friendly.
I don't know which one is good.

**Comment by yjqg6666** [comment]
IMHO, configuration by config file is preferred. We have to configure JVM if the property is used.

**Comment by yjqg6666** [comment]
Usually the JVM configuration is configured by the Operator/Sysadmin and the agent configuration can be configured by the developers themselves.

**Comment by yjqg6666** [comment]
It would be also great that the applicationName and agentId can be configured by environment variable. 
Read the environment variables ${env.APPLICATION_NAME} and ${env.AGENT_ID}, in this case only javagent:/path/to/agent-without-version.jar is needed and is constant. This is what i'm currently using for k8s env.

**Comment by yjqg6666** [comment]
Agreed. The bracket(${...}) is preferred over %..%.

**Comment by NishantRajak** [comment]
Hi @emeroad,
Thanks for all your great work. 
Recently we are working on cloud environment where pod names are very lengthy. If we are running multiple replica of same pod it is very tough to manage and identify the pods by its name.

1-Is there any chance that the 24 characters limit of agentId can manage or extend? 
2-If agent Id automatically pick hostname/pod ?
3- If same process having multiple JVM agentId start indexing e.g. AgentID_1, AgentId_2.

Please respond. Thanks in advance.

Regards,
Nishant

**Comment by yjqg6666** [comment]
@emeroad Will the agentName be shown on the Web page, either transaction info page or inspector page?

**Comment by emeroad** [comment]
@yjqg6666 
```
format : AgentName(AgentId)
```
Perhaps it should be displayed in above format, 
and both pages should be displayed identically.

Currently this is just an idea, it is not developed at all.
If there is a better way, please suggest.

**Comment by yjqg6666** [comment]
@emeroad What about adding the optional agentName to the agentInfo and sending to the collector ? would it be backward-compatible? For the thrift transport, the field could be declared optional.

**Comment by emeroad** [comment]
Thrift is planned to be deprecated. There is no need to guarantee backwards compatibility.

In the case of grpc, it would be convenient to use headers.
