### ISSUE TITLE
pinpoint agent 1.6.2 is not work on weblogic12c: pinpoint-bootstrap-x.x.x(-SNAPSHOT).jar not found.

### ISSUE THREAD

**Issue by zyxchaos** [pinpoint-apm/pinpoint#7384]
The start log report:
2020-11-05 17:00:36 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) pinpoint agentArgs:
2020-11-05 17:00:36 [WARN ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) pinpoint-bootstrap-x.x.x(-SNAPSHOT).jar not found.
2020-11-05 17:00:36 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) Agent Directory Verify fail. skipping agent loading.
*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
the startWeblogic.sh add:
SAVE_JAVA_OPTIONS="${JAVA_OPTIONS} -javaagent:/bossapp/webapp/cmccapm/pinpoint-bootstrap-1.6.2.jar -DCMCCAPM.agentId=lzwaopen2api02v -DCMCCAPM.applicationName=aopen2_api -DCMCCAPM.systemId=aopen2"

the agent path is right:
[webapp@lzwaopen2api01v 17:12:27 ~/cmccapm]$ll /bossapp/webapp/cmccapm/pinpoint-bootstrap-1.6.2.jar
-rw-r----- 1 webapp app 33838 Jul  3  2018 /bossapp/webapp/cmccapm/pinpoint-bootstrap-1.6.2.jar

**Comment by zyxchaos** [comment]
In start log, get the right configuration:
####<2020-11-5 ????02ê±19·?35,614?? CST> <Info> <Management> <lzwaopen2api01v> <> <[ACTIVE] ExecuteThread: '8' for queue: 'weblogic.kernel.Default (self-tuning)'> <> <> <> <1604557175614> <[severity-value: 64] [partition-id: 0] [partition-name: DOMAIN] > <BEA-141280> <Detected NON-BLOCKING java entropy configuration. This setting will provide the best performance on machines with few sources of entropy, but is less secure than a blocking entropy configuration.> 
####<2020-11-5 ????02ê±19·?35,619?? CST> <Info> <Management> <lzwaopen2api01v> <> <[ACTIVE] ExecuteThread: '8' for queue: 'weblogic.kernel.Default (self-tuning)'> <> <> <> <1604557175619> <[severity-value: 64] [partition-id: 0] [partition-name: DOMAIN] > <BEA-141187> <Java system properties are defined as follows: 
CMCCAPM.agentId = lzwapi01v
CMCCAPM.applicationName = aopen2_api
CMCCAPM.systemId = aopen2
awt.toolkit = sun.awt.X11.XToolkit
bes.log.debug = true
bes.log.dir = /bossapp/webapp/apidomain/local/
dbname = oracle

**Comment by minwoo-jung** [comment]
Hello @zyxchaos 
Pinpoint 1.6.2 version does not support weblogic plugin.
https://github.com/pinpoint-apm/pinpoint/tree/1.6.2#supported-modules
