### ISSUE TITLE
v2.1.0 use war package 

### ISSUE THREAD

**Issue by tobewithyou1996** [pinpoint-apm/pinpoint#7387]
I pull the 2.1 code and then use the war package for deployment. However, it is abnormal to put the war package in Tomcat after I build the war package. Can you tell me what happened?  Display resource not found。

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/releases/tag/v2.1.0

The web and collector have been changed to spring-boot.
WAR is no longer supported.
