### ISSUE TITLE
 What is the difference between installing jar and qucikstart?

### ISSUE THREAD

**Issue by seocho2360** [pinpoint-apm/pinpoint#7388]
I have referenced the documentation below, but I don't know a big difference.
Please let me know if there is any difference other than simply installing and using it quickly.

https://pinpoint-apm.github.io/pinpoint/installation.html

**Comment by RoySRose** [comment]
Hello, @seocho2360 

A quickstart was mainly used in the past for the users who wanted to simply try out Pinpoint. Since installing the whole pinpoint components took very long. 

Nowadays, we've added [live demo](http://125.209.240.10:10123/main) as much as docker (https://github.com/pinpoint-apm/pinpoint-docker) for the users to try out Pinpoint in few seconds. So Quickstart has kind of lost its meaning of existence.

**Comment by seocho2360** [comment]
@RoySRose 

Do you have a guide for docker?

Also, shouldn't we use quickstart to connect with real servers? Are there any drawbacks compared to the whole pinpoint?


Thank you

**Comment by RoySRose** [comment]
@seocho2360 
guide for docker is at the docker repo.

>Also, shouldn't we use quickstart to connect with real servers? Are there any drawbacks compared to the whole pinpoint?
What do you mean by `real servers`? If you are referring to pinpoint-agent attached to real server applications to monitor, then yes, you can you the something like quickstart script.
But if you planning to use the script itself, then you will end up monitoring the testapp inside the quickstart module, which I assume is not what you want (assuming by `real server`)

**Comment by seocho2360** [comment]
@RoySRose 

As you said, the real server is trying to link with the PINPOINT server to the real server application to be monitored.

As a disadvantage, I understood that the testapp will be monitored, but will it be a problem that will be solved if the testapp itself is not run with quickstart?

**Comment by RoySRose** [comment]
@seocho2360  
I don't fully understand what you're trying to achieve by using quickstart.

Let's say you've set up the whole Pinpoint environment (web, collector, hbase, etc.)
Then you will try to attach pinpoint-agent to your application which you want to monitor.
For `quickstart` pinpoint-agent is attached to a sample application.
If you'd like to replace the sample app with yours. It will work.

**Comment by seocho2360** [comment]
@RoySRose 

By installing the PINPOINT server separately, I tried to run the web, collector, and hbase with quickstart, and install the agent in the running server to connect.

**Comment by RoySRose** [comment]
@seocho2360 

>By installing the PINPOINT server separately, I tried to run the web, collector, and hbase with quickstart, and install the agent in the running server to connect.

I don't see any problem with the module settings. It would work with the right configurations.

**Comment by seocho2360** [comment]
@RoySRose 


I tested the same as you said, but I have never used whole pinpoint, so I wanted to check if there were any functional differences...

May I understand that there is no functional difference?

**Comment by RoySRose** [comment]
I didn't really look into the quickstart recently. But so far I know, no, there won't be.

**Comment by seocho2360** [comment]
@RoySRose 


It's annoying, but can you check it out...?

Thank you.

**Comment by RoySRose** [comment]
No, I won't be checking it out. Have other things with more priority.
You can check it yourself, it's open-source. And you need to fully understand the scripts if you're going to use it in your production anyway. 
The community will appreciate your feedback on it. 
Also any PR is welcome to upgrade or any ideas on the quickstart itself

**Comment by seocho2360** [comment]
@RoySRose 

Yes sir.
Thank you for your support.

**Comment by seocho2360** [comment]
@RoySRose 

Please contact us in a long time.
I am using a pinpoint with quickstart. Is there a way to connect to hbase?
Thank you.

**Comment by RoySRose** [comment]
@seocho2360 

what do you mean by connecting to hbase?
If you want to extract the data. There is no feature for it in Pinpoint for now.

**Comment by seocho2360** [comment]
@RoySRose 

For hbase connection, we ask if it is possible to perform query work by accessing ssh.
I want to check the information in the DB.

Also, in the case of pinpoint-web, I think it is WAS. Can I think of pinpoint-collector as a web container? if not,
Is there any applicable among the types of was, web application, and web service?

Thank you.

**Comment by seocho2360** [comment]
@RoySRose 
An example of hbase connection is shown below.
Connect to ssh and ask if it is possible to execute the command below in the console.

Example) mysql -h host name -u ID -p

**Comment by seocho2360** [comment]
@RoySRose 


I downloaded pinpoint 2.0.4 through git. Can I check the apache-tomcat version included in 2.0.4 and the version information of hbase?

When running through quickstart, tomcat is 8.5.28 and hbase is 1.0.3 with ps -ef command.

**Comment by RoySRose** [comment]
@seocho2360 
Here is the architecture of Pinpoint. https://pinpoint-apm.github.io/pinpoint/2.2.0/overview.html
Also you can check other info from the homepage.
DB is hbase. I think you can find your way from there.
Also pinpoint web, collector is spring boot app. I think you can find your tomcat issue from there.

**Comment by seocho2360** [comment]
@RoySRose 

It looks different from the version information in pom.xml and the version information of the driven pinpoint process. Which one is correct?

**Comment by RoySRose** [comment]
what do you mean by..
It looks different from the version information in pom.xml and the version information of the driven pinpoint process. Which one is correct?

spring-core version must be specified in pom.xml. If it's not there, look for it in the parent pom

**Comment by seocho2360** [comment]
@RoySRose 

where is parent pom? 
I looked at the pom.xml inside the pinpoint directory.

**Comment by RoySRose** [comment]
I think you can find it yourself since it's not about Pinpoint. It's about maven.

**Comment by seocho2360** [comment]
@RoySRose 

Hello, Roy rose.

I want to delete the testapp details from the application name in pinpoint-web.
I saw a guide in #1963 to delete by calling /admin/removeAgentId.pinpoint.

Can you figure out how to call it?

**Comment by seocho2360** [comment]
@RoySRose 

I found a way. thanks

**Comment by seocho2360** [comment]
@RoySRose 
Hello, I will contact you after a long time.

I know that the data displayed on PINPOINT WEB shows the information stored in hbase. I am using PINPOINT with quickstart. Is there any way to check the information of hbase?

In addition, is the data information shown in PINPOINT-WEB encrypted?
ex) sha 256, MD5 ....

**Comment by seocho2360** [comment]
@RoySRose , @koo-taejin 



Good morning,
I have an additional question in the following matters. Can you tell me where the data information displayed on the pinpoint web driven by quickstart was recorded as a log?

In the quickstart/logs part, there is only the time that was driven by quickstart, and there is no data information displayed on the web.


> @seocho2360
> 
> > By installing the PINPOINT server separately, I tried to run the web, collector, and hbase with quickstart, and install the agent in the running server to connect.
> 
> I don't see any problem with the module settings. It would work with the right configurations.

**Comment by koo-taejin** [comment]
hi @seocho2360 

If you use quickstart that changed to spring boot, you could find logs folder at location that you executed quickstart.

thanks

**Comment by seocho2360** [comment]
@koo-taejin 


In the log folder in the location where quickstart was executed, quickstart.collector.log and quickstart.web.log are not accumulating data seen on the actual web.

Is the path below what you said? Would you need a setting to accumulate logs?
$pinpoint_home/quickstart/logs

**Comment by koo-taejin** [comment]
![a](https://user-images.githubusercontent.com/10057874/106076659-57506b00-6153-11eb-937d-67adb705ad94.png)

**Comment by seocho2360** [comment]
@koo-taejin 
Could you please give me the full path?
Please use the pwd command.

**Comment by koo-taejin** [comment]
@seocho2360 
The full path is not important, so the logs folder will be created in the location where you execute it.
And I could not tell you full path because of  company security.

**Comment by seocho2360** [comment]
Isn't created in the location pinpoint/quickstart/logs?

**Comment by koo-taejin** [comment]
> @koo-taejin
> Isn't created in the location pinpoint/quickstart/logs?

the logs folder will be created in the location where you execute it.

**Comment by seocho2360** [comment]
@koo-taejin 

Am I misunderstanding the expression that it was executed..?
Data does not accumulate in the log directory under quickstart because it was driven by quickstart.

**Comment by seocho2360** [comment]
@koo-taejin 

I know hbase is a database that stores analysis information and data collected through Pinpoint Collector. Can you tell where the data in hbase is accumulated? Data can be seen on the web, but there is no trace in the hbase log.

**Comment by koo-taejin** [comment]
@seocho2360 
Please refer to the hbase schema information.
https://github.com/pinpoint-apm/pinpoint/tree/master/hbase/hbase-schema-definition
