### ISSUE TITLE
2.1.0 collector does not collect

### ISSUE THREAD

**Issue by encrylife** [pinpoint-apm/pinpoint#7390]
I request 1000 times,but the web only list  five.what's happen. run it with the doc and only replace the jar,no error and no data ,the other requests had gone way? the port is still listen and hbase work well

**Comment by dv-morais** [comment]
its your agent...

change this value in pinpoint-env.config inside the profiles/release folder

from:
profiler.sampling.rate=20

to
profiler.sampling.rate=1

or call it directly from your run command

java -Dprofiler.sampling.rate=1 -jar balbalblaba.jar

or add it in the environment variables JAVA_OPTS or CATALINA_OPTS

JAVA_OPTS=$JAVA_OPTS -Dprofiler.sampling.rate=1

**Comment by encrylife** [comment]
thanks
