### ISSUE TITLE
how can I add CAS(Central Authentication Service) in pinpoint web

### ISSUE THREAD

**Issue by LightCastlePro** [pinpoint-apm/pinpoint#7396]
I want add cas in  pinpoint web, how can I modify code.
thanks.

**Comment by minwoo-jung** [comment]
@LightCastlePro 
There is no logic in pinpoint for authentication by interworking with the cas server.
However, it doesn't seem impossible if you modify the code yourself.

**Comment by LightCastlePro** [comment]
> @LightCastlePro
> There is no logic in pinpoint for authentication by interworking with the cas server.
> However, it doesn't seem impossible if you modify the code yourself.

thank you. I resolved this issue by using cas-proxy. thank you .
