### ISSUE TITLE
simple way to configure alarm

### ISSUE THREAD

**Issue by mlzxdzl** [pinpoint-apm/pinpoint#7443]
Hi 
    I am an It operation and maintenance personnel，I don't know how to program in Java。 So it is difficult for me to configure alarm according to the document.  
    Is it possible to have a simple way to configure alarm ?

**Comment by RoySRose** [comment]
@mlzxdzl 

[This document](https://pinpoint-apm.github.io/pinpoint/alarm.html) is the closest on that you can get
