### ISSUE TITLE
How to convert pinpoint data captured in EST time zone to IST timezone

### ISSUE THREAD

**Issue by ChaudhariPrasad** [pinpoint-apm/pinpoint#7453]
How to convert pinpoint data captured in EST time zone to IST timezone.
Lets say have a data captured in EST time frames but when seen in IST time, it wont show any data captured.

**Comment by ChaudhariPrasad** [comment]
I am looking for UI option that helps to see data by changing the timezones.

**Comment by RoySRose** [comment]
@binDongKim is there any issue on this?

**Comment by emeroad** [comment]
http://$PINPOINT_WEB/config/general
> Setting->General->TimeZone 

Please change the above settings.
