### ISSUE TITLE
Unable to configure PinPoint Agent

### ISSUE THREAD

**Issue by ChakraverthyK** [pinpoint-apm/pinpoint#7459]
#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v2.0.3.

#### Describe your problem**
I have configured Pinpoint and able to get metrics for apps when started via Tomcat (using .war). But we have an application which has custom java classes, and they have also used Tomcat. But they don't start Tomcat through startup.bat. So, my question is how can we configure agent in these kind of java applications where we don't have .war files?

**Comment by RoySRose** [comment]
Attaching pinpoint-agent to a java application doesn't matter whether it's war or jar or whatever.
You just need to pass the necessary JVM arguments at the start-up of your application.

**Comment by ChakraverthyK** [comment]
Thanks, will give a try and update

**Comment by ChakraverthyK** [comment]
I have tried couple of things but didn't work:
1. Tried to insert agent config in wt.properties
2. Tried to insert in catalina.bat
3. Tried in startup.bat
4. wttomcat_start.bat

Please suggest
