### ISSUE TITLE
Cleanup Inactive Agents restricted to 30 days

### ISSUE THREAD

**Issue by praveen12bnitt** [pinpoint-apm/pinpoint#7478]
We run our production workload on docker containers and we also create a lot of them depending on the load on the system. Due to this, we create a lot of pinpoint agents for a single application. To give you an idea, we create close to 5k agents in 10 days easily.  With this kind of setup, our ServerMap page takes a lot of time. Initially its fast, but as we get more and more agents, it slows down.

We wanted to enable the cleanup CleanupInactiveAgentsTasklet so that pinpoint web can cleanup these inactive agents more aggressively. Functionally it works. It goes and cleanups up inactive agents. However the `cleanupInactiveAgentsDurationDays` can only be 30 days or more.

com.navercorp.pinpoint.web.batch.BatchConfiguration
```
@PostConstruct
    public void setup() {
        beforeLog();

        if (enableCleanupInactiveAgents == false) {
            cleanupInactiveAgentsDurationDays = DEFAULT_CLEANUP_INACTIVE_AGENTS_DURATION_DAYS;
            cleanupInactiveAgentsCron = DISABLED_CLEANUP_INACTIVE_AGENTS_CRON;
        } else {
            if (cleanupInactiveAgentsDurationDays < 30) {
                throw new IllegalArgumentException("'cleanupInactiveAgentsDuration' must be 'cleanupInactiveAgentsDuration >= 30'");
            }
        }

        afterLog();
    }
```

Because we have a lot of inactive agents, we wanted cleanup our inactive agents more aggressively. We are planning to keep it to 7 days. Any agents that is not active for more then 7 days, we want to get rid of them. 

Is there a reason for setting this to 30? If not, can i submit a PR which will make this configurable? I will default it to 30, but if a customer wants it to run it more aggressively, they can set it to a much lower value.

**Comment by koo-taejin** [comment]
hi @praveen12bnitt 
I am sorry for the late reply.

I am gonna change to minimum value as 7day.
If the operator decides it's okay to erase it, it doesn't seem like a problem.

thanks :)

**Comment by praveen12bnitt** [comment]
Great! Thanks

**Comment by koo-taejin** [comment]
It is merged 

thanks for your suggestion :)
