### ISSUE TITLE
How to add permissions to the application list of pinpoint

### ISSUE THREAD

**Issue by YuppiesYue** [pinpoint-apm/pinpoint#7481]
How to add permissions to the application list of pinpoint？
Because the data is secure
we need auth . not everybody can see the data, 
maybe we need a function like login or something。
Look forward to your reply！

**Comment by koo-taejin** [comment]
hi @YuppiesYue 
Unfortunately, pinpoint does not provide Authorization for now.
And we don't have any plan about this. 
Only way to use this function is that you have to make this function. 
thanks :)
