### ISSUE TITLE
snmptrap information

### ISSUE THREAD

**Issue by AFeiei** [pinpoint-apm/pinpoint#7484]
Hello, the application listens on the local udp 5100 port and the network device sends an alert message to the port via snmptrap, can I monitor the traffic in this case?

**Comment by AFeiei** [comment]
the application is springboot application

**Comment by emeroad** [comment]
I didn't understand your question exactly, 
but please see below to monitor user api.
https://pinpoint-apm.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help

**Comment by AFeiei** [comment]
> I didn't understand your question exactly,
> but please see below to monitor user api.
> https://pinpoint-apm.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help

The springboot program listens on a local port and the switch or server sends an alert to the port using the snmp protocol. pinpoint can monitor such alerts?
