### ISSUE TITLE
 Channelz monitoring API for collector

### ISSUE THREAD

**Issue by emeroad** [pinpoint-apm/pinpoint#7486]
Add an API to collector to observe grpc status.

#7375

## Channelz metric query api
-  ServerTransport socket status
   http://$PINPOINT_COLLECTOR/channelz/html/findSocket?remoteAddress=127.0.0.1&localPort=9993
   remoteAddress : Agent IP
   localPort : Listen port of collector

![image](https://user-images.githubusercontent.com/7564547/101583592-255a3c80-3a1f-11eb-8351-1df0b3b6f0af.png)

**Comment by erinyees** [comment]
@emeroad 
Hello, I have a question. 
You added API data sheet but I don't know how to read(analyze) it. 
Is there example how to analyze API data sheet? Should I know gRPC to understand API data sheet?
I want to know how to apply it on code.

**Comment by emeroad** [comment]
Yes, you need to know the inside of the grpc.
Please refer to this URL.
https://grpc.io/blog/a-short-introduction-to-channelz/
