### ISSUE TITLE
Transaction: save to file, show exceptions. Instrumentation

### ISSUE THREAD

**Issue by Benzion18** [pinpoint-apm/pinpoint#7506]
Hi,

1. How can I save pinpoint transaction to file?
2. My transaction is marked with flame sign, meaning it has exceptions. How can I see in pinpoint what exactly exception was there?
3. What classes does Pinpoint instrument? How can I manage it, like adding classes/packages to be instrumented?

**Comment by RoySRose** [comment]
@Benzion18 

1. How can I save pinpoint transaction to file?
    - Currently, there is no extracting data function in open source
2. My transaction is marked with flame sign, meaning it has exceptions. How can I see in pinpoint what exactly exception was there?
    - Select the red dots on the scatter chart(top right corner of the first page)
3. What classes does Pinpoint instrument? How can I manage it, like adding classes/packages to be instrumented?
    - Actually, Pinpoint automatically takes care of this. Check the homepage for the list
