### ISSUE TITLE
gson.profiler.enable=false doesn't work

### ISSUE THREAD

**Issue by zhuangjinjin** [pinpoint-apm/pinpoint#7514]
#### What version of pinpoint are you using?
master/v2.0.x/v2.1.x etc.

#### Describe the bug
When I setting gson.profiler.enable=false in pinpoint.config, but it doesn't work, it always collect. 
I saw the code of GsonPlugin.java
```java
public class GsonPlugin implements ProfilerPlugin, TransformTemplateAware {
    // ...
   @Override
    public void setup(ProfilerPluginSetupContext context) {
        GsonConfig config = new GsonConfig(context.getConfig());
        if (!config.isProfile()) {
            logger.info("{} disabled", this.getClass().getSimpleName()); // lost return
        }
        logger.info("{} config:{}", this.getClass().getSimpleName(), config);
        transformTemplate.transform("com.google.gson.Gson", GsonTransform.class);
     }
```
![image](https://user-images.githubusercontent.com/3142281/103091198-5eed9300-462e-11eb-8b63-5db4386c95ba.png)

#### Expected behavior
I don't want to collect gson trace info when I setting `gson.profiler.enable=false` in pinpoint.config

**Comment by koo-taejin** [comment]
@zhuangjinjin 
Yes, you are right. It look like bugs. 
Please send your PR. 
I am going to merge it 

thanks 👍
