### ISSUE TITLE
How to monitor django deployed by uwsgi+nginx？

### ISSUE THREAD

**Issue by 373836411** [pinpoint-apm/pinpoint#7520]
I can monitor the project started with the httpserver that comes with django, but when I deploy the project with nginx+uwsgi, I encountered a permission problem, but I don't know how to solve it. The error message is as follows:

*******MyMiddleware request******
[pinpoint] [52739] [52739]#0 pinpoint_start start
[pinpoint] [52739] [52739]#128 add clue key:appname value:10.28.0.100-Django-8888
[pinpoint] [52739] [52739]#128 add clue key:appid value:APM-0100280001008888
[pinpoint] [52739] [52739]#128 add clue key:name value:BaseDjangoRequest request
[pinpoint] [52739] [52739]#128 add clue key:uri value:/favicon.ico
[pinpoint] [52739] [52739]#128 add clue key:client value:10.19.197.133
[pinpoint] [52739] [52739]#128 add clue key:server value:10.28.0.100
[pinpoint] [52739] [52739]#128 add clue key:stp value:1700
[pinpoint] [52739] [52739]pre_init_shared_object: open address with:Permission denied 

uwsgi: /tmp/pip-install-gzeq51ez/pinpointpy_84ec1378330b4d799049fa3092f41d5d/common/src/Cache/SharedObj.c:196: fetch_shared_obj_addr: Assertion `object.region' failed.**

Can anyone help me? thank you very much!

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint-c-agent
Could you ask a question here?

**Comment by 373836411** [comment]
okay! https://github.com/pinpoint-apm/pinpoint-c-agent/issues/282
