### ISSUE TITLE
How to add alarm in batch?

### ISSUE THREAD

**Issue by liucx1201** [pinpoint-apm/pinpoint#7523]
We can only add alarm separately for each service on monitoring, which is very tedious. How to implement template alarm monitoring in batch

**Comment by RoySRose** [comment]
Here is a guide on `how to set alarm`.
https://pinpoint-apm.github.io/pinpoint/2.2.0/alarm.html

Also there is ongoing PR by @imbf (such as #7163) that you can consider.
