### ISSUE TITLE
how can I use my jar package in Version-2.2.0

### ISSUE THREAD

**Issue by LightCastlePro** [pinpoint-apm/pinpoint#7525]
collector, web
before version 2.0.x, we can use our own Plug-ins ,just put Plug-ins in ROOT/WEB-INF/lib.
In version 2.2.0, how can I use my own Plug-ins.
Thanks

**Comment by emeroad** [comment]
Pinpoint collector and web are packaged as spring-boot,
so you can use spring-boot feature as it is.
https://stackoverflow.com/questions/39716796/spring-boot-executable-jar-with-classpath

**Comment by LightCastlePro** [comment]
Let me try and try and try . thank you.
