### ISSUE TITLE
HttpClient4 plugin's BasicFutureMethodInterceptor failed to record exception detatils when intercepting method `org.apache.http.concurrent.BasicFuture#failed`

### ISSUE THREAD

**Issue by tankilo** [pinpoint-apm/pinpoint#7527]
#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master

#### Describe the bug
HttpClient4 plugin's BasicFutureMethodInterceptor failed to record exception detatils when intercepting method `org.apache.http.concurrent.BasicFuture#failed`

![image](https://user-images.githubusercontent.com/10413284/103470276-b36ddc80-4dab-11eb-96a9-ce5e16ce0fb0.png)

#### What did you do to trigger the bug?

Run the demo code with pinpoint agent.
Of course ,i didn't run any server on endpoint `http://127.0.0.1:9200`.

```
public class TestHttpClient {
    public static void main(String[] args){

        RequestConfig requestConfig = RequestConfig.custom()
            .setConnectTimeout(50000)
            .setSocketTimeout(50000)
            .setConnectionRequestTimeout(1000)
            .build();

        IOReactorConfig ioReactorConfig = IOReactorConfig.custom().
            setIoThreadCount(Runtime.getRuntime().availableProcessors())
            .setSoKeepAlive(true)
            .build();

        ConnectingIOReactor ioReactor=null;
        try {
            ioReactor = new DefaultConnectingIOReactor(ioReactorConfig);
        } catch (IOReactorException e) {
            e.printStackTrace();
        }
        PoolingNHttpClientConnectionManager connManager = new PoolingNHttpClientConnectionManager(ioReactor);
        connManager.setMaxTotal(100);
        connManager.setDefaultMaxPerRoute(100);


        final CloseableHttpAsyncClient client = HttpAsyncClients.custom().
            setConnectionManager(connManager)
            .setDefaultRequestConfig(requestConfig)
            .build();

        String url = "http://127.0.0.1:9200/_bulk";
        HttpPost httpPost = new HttpPost(url);
        StringEntity entity = null;
        try {
            String a = "{ \"index\": { \"_index\": \"test\", \"_type\": \"test\"} }\n" +
                "{\"name\": \"上海\",\"age\":33}\n";
            entity = new StringEntity(a);
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        httpPost.setEntity(entity);

//start
        client.start();

//异步请求
        client.execute(httpPost, new Back());

        while(true){
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    static class Back implements FutureCallback<HttpResponse>{

        private long start = System.currentTimeMillis();
        Back(){
        }

        public void completed(HttpResponse httpResponse) {
            try {
                System.out.println("cost is:"+(System.currentTimeMillis()-start)+":"+EntityUtils.toString(httpResponse.getEntity()));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        public void failed(Exception e) {
            System.err.println(" cost is:"+(System.currentTimeMillis()-start)+":"+e);
        }

        public void cancelled() {

        }
    }
}
```

#### Expected behavior
![image](https://user-images.githubusercontent.com/10413284/103470263-70136e00-4dab-11eb-8ccb-ffde5563c651.png)

Exception details should be recorded
#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by tankilo** [comment]
I will post a PR to fix it.

**Comment by tankilo** [comment]
@emeroad Do you think this is a bug?

**Comment by emeroad** [comment]
@tankilo 
Thanks for your contribution.

I fully agree with your opinion.
I really like this PR. :+1:
