### ISSUE TITLE
Check Pinpoint Agent memory/cpu 

### ISSUE THREAD

**Issue by VidushaZ** [pinpoint-apm/pinpoint#7542]
Hi Pinpoint team,

Is it possible to get memory/cpu used by the agent itself? I have this application takes memory and I want to confirm the agent is not taking much memory/cpu. 

Thank You!

**Comment by emeroad** [comment]
No, there is no such feature.
Use JConsole instead of pinpiont agent.

**Comment by VidushaZ** [comment]
All right! Thanx I will check that out

**Comment by demon98-bai** [comment]
I have a question. After springboot is connected to the agent, why are the corresponding server CPU and JDBC very high?

**Comment by demon98-bai** [comment]
The server CPU is also high
