### ISSUE TITLE
HandlerManager for the gRPC handlers

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7574]
#### What version of pinpoint are you using?
master/v2.2.1

#### Describe the bug
HandlerManager in collector can enable/disable the access to HBase. This feature only available for the thrift handlers, not available for the gRPC handlers.

#### Expected behavior
When enabled/disabled the handlers via jmx/REST api, the gRPC handlers should be affected.

#### Related issue
 issue #2687

**Comment by yjqg6666** [comment]
The related sources for the thrift handler are
https://github.com/pinpoint-apm/pinpoint/blob/master/collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/DelegateDispatchHandler.java#L52-L55  and  https://github.com/pinpoint-apm/pinpoint/blob/master/collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/DelegateDispatchHandler.java#L78-L84 .

**Comment by koo-taejin** [comment]
hi @yjqg6666 

Do you have plan to do it? 
If you are going to do it, then I am going to await it.

If not I am going to do this issue. 

Please tell me what you have plan, then I choose whether I do this job  or not.

thanks :)

**Comment by yjqg6666** [comment]
I am not familiar with the gRPC part and would like to wait for the official support.

**Comment by koo-taejin** [comment]
@yjqg6666 
Ok, I am going to handle it.  :)

**Comment by yjqg6666** [comment]
@koo-taejin You are right. I rechecked it by running the collector.
![image](https://user-images.githubusercontent.com/1879641/107198824-8f4b8e00-6a30-11eb-801f-3762b75080c1.png)


I checked using 'find usage' of  HandlerManager and jump to the wrong conclusion. 
![image](https://user-images.githubusercontent.com/1879641/107199269-2ca6c200-6a31-11eb-8a40-3c0561b7b38d.png)


Please ignore the issue.
