### ISSUE TITLE
JBoss plugin with JBoss 7 and OpenJDK 11

### ISSUE THREAD

**Issue by davide-parini** [pinpoint-apm/pinpoint#7627]
We are upgrading some of our Pinpoint-monitored application servers from JBoss 6.1 with Oracke JDK 1.8 to JBoss 7.3 with OpenJDK 11. We are using Pinpoint 2.0.4 collector, web and agent. Monitoring seems almost ok, but something is not working with (i think) the JBoss plugin. It seems that connections to external systems and to databases are now all "unknown".
![image](https://user-images.githubusercontent.com/38081480/107041146-6d4bd480-67c0-11eb-99ff-318d26aebb1b.png)
Another strange behavior is that the traces seem to be caught by Undertow plugin instead of JBoss plugin.
![image](https://user-images.githubusercontent.com/38081480/107041274-9a988280-67c0-11eb-8c6f-20ac10c8d39b.png)
I tried disabling Undertow plugin, but this leads to requests not being traced at all.

My question is: is JBoss 7 supported? If it is, since which Pinpoint version?

Thank you for your amazing work.

**Comment by emeroad** [comment]
Usually unknown database problems are caused by jdbc url pasing failure.

Take a look at JdbcUrlParser.
eg)
https://github.com/pinpoint-apm/pinpoint/blob/master/plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlJdbcUrlParser.java

**Comment by davide-parini** [comment]
Hi @emeroad,

The jdbc url should not be a problem. With our migration from EAP 6.1 to 7.3 we didn't changed jdbc urls, and they were properly monitored on JBoss 6.1 + Pinpoint 2.0.1.

I think the real problem is that JBoss 7 is not instrumented as it should be. Maybe this is because its servlet engine changed from Tomcat to Undertow. Do you think this may be the case?

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/issues/7666
New version of JDBC driver issue
