### ISSUE TITLE
I found a bug in  DefaultProfilerConfig.java  

### ISSUE THREAD

**Issue by snaigle** [pinpoint-apm/pinpoint#7628]
problem:  pinpoint.config's properties ``` profiler.include``` not work

so I review the code ,and find something maybe wrong 

#### What version of pinpoint are you using?
master

``` java
   //. file:  https://github.com/pinpoint-apm/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  // position line 365 to 375
    @Value("${profiler.include}")
    void setProfilableClassFilter(String profilableClass) {
        // TODO have to remove
        // profile package included in order to test "call stack view".
        // this config must not be used in service environment because the size of  profiling information will get heavy.
        // We may need to change this configuration to regular expression.
        if (profilableClass != null && profilableClass.isEmpty()) {
            this.profilableClassFilter = new ProfilableClassFilter(profilableClass);
        } else {
            this.profilableClassFilter = new SkipFilter<String>();
        }
    }
```
```      if (profilableClass != null && profilableClass.isEmpty()) { ```   this line
the condition maybe is ```profilableClass != null && !profilableClass.isEmpty() ```, or this will not work forever

thank a lot

**Comment by RoySRose** [comment]
Yes. It looks like it's a bug. Any suggestions?

**Comment by snaigle** [comment]
> Yes. It looks like it's a bug. Any suggestions?

please fix it like this: ```profilableClass != null && !profilableClass.isEmpty() ```
I already tested in local env 
Also need I create a pr for this?
