### ISSUE TITLE
pinpoint localhost web ui url information

### ISSUE THREAD

**Issue by fthgul** [pinpoint-apm/pinpoint#7629]
Hi,

I installed and run everything smoothly like the following:
![image](https://user-images.githubusercontent.com/23243836/107150660-efc6c680-696f-11eb-94d4-4a80076855db.png)

But how can reach the web ui url's for docker installation. I can't anywhere the url information about the web ui. What I want that is the url information to reach  the web ui like the following:
localhost:**whichport** ==> url iformation, please  ?
![image](https://user-images.githubusercontent.com/23243836/107150763-8b583700-6970-11eb-8adb-9da466967d9c.png)

**Comment by RoySRose** [comment]
Please read the readme in the [pinpoint-docker repo](https://github.com/pinpoint-apm/pinpoint-docker).
