### ISSUE TITLE
Pinpoint SDK for asynchronous operation

### ISSUE THREAD

**Issue by emeroad** [pinpoint-apm/pinpoint#7654]
https://github.com/pinpoint-apm/pinpoint/pull/7649
@zhangyinhao1234 
Thank you for your contribution.

This approach is simple and very effective.

## ​​#7649 design
1. SDK provides Runnable and Executor classes
  - Now the target class to instrument is determined by the SDK
2. Async plug-in instrument the SDK class.

## ~~My design~~
1. Agent provides API for async operation.
2. SDK uses the agent's API to measure performance.

**Weakness**
- API should be provided through Boostrap-classloader. Its development is very complicated.
- Difficulty maintaining compatibility between SDK and agent API.

**Comment by emeroad** [comment]
@zhangyinhao1234
Your PR disappeared as I pushed my rebase revision to the master branch.
It's my mistake. I have not found the cause of this problem. I'm really sorry.

I made a new branch and restored it.

**Comment by zhangyinhao1234** [comment]
I'm glad my design was adopted
