### ISSUE TITLE
pinpoint 2.2.1 topology not working

### ISSUE THREAD

**Issue by vic-kjs** [pinpoint-apm/pinpoint#7693]
#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

It is normal in 2.0.4, but does not work in 2.2.1.
Are there any settings to fix it?
Or will it be solved by changing to a different version?

Hadoop ver- 3.1.3
Zookeeper ver- 3.4.14
Hbase ver- 2.1.8

Below is the topology of the same service.
2.0.4
![image](https://user-images.githubusercontent.com/69237192/108809127-855a8b00-75eb-11eb-8769-505becf70f36.png)

2.2.1
![image](https://user-images.githubusercontent.com/69237192/108809182-9b684b80-75eb-11eb-9e0f-e5500e72d122.png)

**Comment by emeroad** [comment]
The hbase client 1.x is not compatible with hbase 2.x
- The default value of hbase client is 1.x.

refer to ; https://pinpoint-apm.github.io/pinpoint/hbaseupgrade.html#do-you-like-to-use-hbase-2x-for-pinpoint

**Comment by vic-kjs** [comment]
We checked the normal operation with the contents given by the guide. Thank you.

**Comment by emeroad** [comment]
You're welcome. 
Your error report is very detailed and well organized, 
so I could easily identify the problem. 
Thank you.

In addition, the latest version of hbase-client is recommended if possible.
https://mvnrepository.com/artifact/org.apache.hbase/hbase-client
