### ISSUE TITLE
How to debug pinpoint-agent step by step

### ISSUE THREAD

**Issue by jejayhe** [pinpoint-apm/pinpoint#7718]
I wrote a custom plugin.
Pinpoint-collector is logging "Failed to insert statistics. Cause:SpanEvent has invalid format.(application:SS_AEServer/tmscloud[TOMCAT], spanEventApplication:null[TMSCLOUD])"
I can debug run pinpoint-collector and poinpoint-web. (in pinpoint project)

I am trying to debug pinpoint-agent step by step.
I'm running tomcat, added -javaagent option to tomcat.
How can I debug pinpoint-agent step by step.
I'm using intellij-idea. run tomcat locally. the project is a spring-boot-test project. (in test project)
I don't know how to incorporate the code from pinpoint.

I tried adding my little project into pinpoint project side by side. But fail to run it.
maybe due to some dependency collision

**Comment by emeroad** [comment]
Just add the agent option when starting the application.

## Sping-boot example
1. Add the agent option to vm options.
eg)
![image](https://user-images.githubusercontent.com/7564547/110595941-05731a00-81c2-11eb-8eec-01ea9c850c3f.png)

2. Click the debug button.
![image](https://user-images.githubusercontent.com/7564547/110596290-7286af80-81c2-11eb-9170-4ad82d66583d.png)

**Comment by jejayhe** [comment]
Thanks. I was thinking about how to debug step by step while refering to pinpoint source code.
Yesterday I failed to start the springboot project inside the pinpoint project.
I have an idea that I can start this springboot application somewhere. And open pinpoint project and use remote debugging to connect to the app.But I haven't tried it.

**Comment by emeroad** [comment]
Your opinion is perfectly correct.
If you want to reference the pinpoint source from another project, you can use remote debuging.
