### ISSUE TITLE
Pinpoint APM Support

### ISSUE THREAD

**Issue by mdnowshath** [pinpoint-apm/pinpoint#7732]
Hello,

We are planning to implement PINPOINT APM solution. We require product support for pinpoint APM solution. Can any one please guide us, contact details, email address to get the enterprise product support.

Regards
Nowshath 

#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

**Comment by RoySRose** [comment]
Hello, @mdnowshath 

There isn't any enterprise product support for Pinpoint or have any plans on it.

**Comment by mdnowshath** [comment]
yes we have plan to implement pinpoint apm solution in our organization. if some technical/implementation issue will happen, we need support for this product. otherwise we will not implement this product with out product support

**Comment by RoySRose** [comment]
@mdnowshath 

My reply wasn't a question. Pinpoint is an open-source project. I think the only place you can get support is the community, and maybe you can hire someone who can dig into the project by the code level.
