### ISSUE TITLE
Thread plugin can't support different package name as same package length

### ISSUE THREAD

**Issue by brito-wang** [pinpoint-apm/pinpoint#7756]
if config thread match package like blow code, the "com.jia" package can't support thread plugin.
eg: profiler.thread.match.package=com.bai,com.jia

Problem code：
MatchableTransformerRegistry.java

`
// sorted by package name length.
        this.packageNameBasedIndex = new TreeMap<String, Set<IndexValue>>(new Comparator<String>() {
            @Override
            public int compare(String key1, String key2) {
               // should change this logic
                return IntegerUtils.compare(key1.length(), key2.length());
            }
        });
`

**Comment by jaehong-kim** [comment]
@brito-wang 
Thanks for reporting the bug.

**Comment by jaehong-kim** [comment]
Applied to version 2.3.0-SNAPSHOT.
