### ISSUE TITLE
Corrupted span event corrupted event

### ISSUE THREAD

**Issue by LynHB** [pinpoint-apm/pinpoint#7757]
#### What version of pinpoint are you using?
master/v1.8.x

#### Describe the bug
I have 200 applications ,but  "bcs-business-model-service" and "bcs-app" prefix   application   traces always corrupted,the web ui show "Corrupted(lost packet - invalid sequence)",logs see below

#### Expected behavior
has a whole trace 

#### Screenshots
![trace](https://user-images.githubusercontent.com/26018195/112581475-70168d80-8e31-11eb-85b5-92dd202eb7e7.png)

#### Logs
2021-03-25 12:21:13 [WARN ](c.n.p.w.c.s.SpanAligner            ) Corrupted span event corrupted event. depth=2, cursor={depth=0, child=false, sibling=false, value={spanBo=SpanBo{version=0, agentId='bcs-business-model-service-10.187.19.115', applicationId='bcs-business-model-service', agentStartTime=1616047425155, transactionId=TransactionId{agentId='bcs-app-service-10.187.4.63', agentStartTime=1616074277997, transactionSequence=321029}, spanId=1877487379574928099, parentSpanId=9074999459306037540, parentApplicationId='null', parentApplicationServiceType=0, startTime=1616550980613, elapsed=979, rpc='/v0.1/models/forms/batch', serviceType=1010, endPoint='bcs-business-model-service-sandbox.sdp.101.com:443', apiId=2, ....

### additional
whole logs in appendix
I am package web and collector in one tomcat and don't distinguish them logs，so logs contain web and collectors warn info.
[https://github.com/LynHB/ProjectA/blob/master/log/catalina.out.20210326](url)

Thanks !

**Comment by emeroad** [comment]
Please check the below.

1. UDP packet is lost. 
   UDP packets may be lost depending on network conditions

2. UDP max packetsize overflow.
    The maximum size of UDP payload is 65,527 bytes.
    If there is too much span to be transmitted, transmission may fail
    
    Reduce buffersize value.
    pinpoint.config
    ```
    # How many spans to store if buffering enabled.
   profiler.io.buffering.buffersize=20
    ```

**Comment by LynHB** [comment]
this application‘s trace almost every has corrupted,other application won't,
so i think is not udp packet lost and my pinpoint config profiler.io.buffering.buffersize is 20, i need reduce this value?

**Comment by LynHB** [comment]
> Please check the below.
> 
> 1. UDP packet is lost.
>    UDP packets may be lost depending on network conditions
> 2. UDP max packetsize overflow.
>    The maximum size of UDP payload is 65,527 bytes.
>    If there is too much span to be transmitted, transmission may fail
>    Reduce buffersize value.
>    pinpoint.config
>    ```
>    # How many spans to store if buffering enabled.
>    profiler.io.buffering.buffersize=20
>    ```

this application‘s trace almost every has corrupted,other application won't,
so i think is not udp packet lost and my pinpoint config profiler.io.buffering.buffersize is 20, i need reduce this value?

**Comment by zhuyin741** [comment]
I have the same problem as yours. Please ask, is your problem progressing now?

**Comment by LynHB** [comment]
> I have the same problem as yours. Please ask, is your problem progressing now?
@zhuyin741  It basically solved.
    Exclude some visible problems (exceptions reported in the log,such as exceeding the maximum on the client side and unavailable region on the hbase),which are releated to my network traffic.In current company's pinpoint serve to more than 2000 java applications, tens of thousands of tomcat and jar, occur traffic congestion and more than 1% packages loss on the network layer.Currently, UDP transmission is used, and UDP has a feature of unreliability,and limitatio of MTU of the link layer(when a packet exceeds 1500 bytes, the packet will be cut and temporarily stored in the network card buffer, and the buffer has a size limit. If it exceeds the size, the old data will be cleaned up),so when the UDP exceeds 1500 bytes, the packet loss situation will deteriorate rapidly. The purpose here is very clear: **to limit the size of a single packet**, place it as follows

- profiler.io.buffering.buffersize=5 or even 1
- Reduce the size of a single span, and modify how many characters the source code exceeds to intercept (compare the production and  test environment, the production loses packets, the test does not lose packets, and locate the specific method to test the size of a single packet. There must be a parameter that is too long. Modify the corresponding interceptor method, and how many characters exceed are intercepted)
