### ISSUE TITLE
[performance] reduce applications.pinpoint request from web UI

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7795]
**Which module is your feature request related to?**
UI

**Is your feature request related to a problem?**
In almost every pinpoint page, it will (almost) always request the applications.pinpoint api event the the result may not be used, esp. in the tx list page and the tx mixed view page. Is there any reason to do this? If omitted, some hbase overhead may be reduced. 
**Describe the solution you'd like**
It a page do no need all the application list data, do NOT make the request.

**Comment by binDongKim** [comment]
This is done by https://github.com/pinpoint-apm/pinpoint/pull/8059
