### ISSUE TITLE
CLI for Pinpoint

### ISSUE THREAD

**Issue by JayeshMuley** [pinpoint-apm/pinpoint#7834]
Hello, 

I am new using Pinpoint, What is the CLI for Pinpoint so that I can query and fetch the data on command line. 
Or any Document related to CLI or API , kindly forward the link. 

Thanks and Regards,
Jayesh Muley

**Comment by koo-taejin** [comment]
hi @JayeshMuley 

Unfortunately, Pinpoint does not have such function as CLI. 
Pinpoint has Http API, but this is not recommended to use because it could change without announcement.

thanks :)
