### ISSUE TITLE
export/maintain protobuf to an individual project for multi language support

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7851]
**Which module is your feature request related to?**
transport/serde: gRPC

** Purpose
The cloud infrastructure can easily integrate the go module to interact with the collector.

** Changes should be made
1. add the "option go_package" to the protobuf definitions. See PR #7852.
2. put https://github.com/yjqg6666/gopinpoint under pinpoint-apm namespace by forking. (v2.2.2 is ready for use)
3. sync the proto changes to gopinpoint project and re-protoc to generate code and tagging (Long-term maintenance).

**Comment by emeroad** [comment]
Since all languages share protobuf-IDL, it would be good to separate IDL into individual projects.

First of all, how about separating protobuf-IDL into sub-module as below.
```
pinpoint-apm
|-- pinpoint 
|   |-- pinpoint-gprc-idl ---| (sub-module)
|                            |
|-- pinpoint-grpc-idl    <---|
|   |-- src/main/proto
|                |- *.proto
|   |-- pom.xml  (java build file)
|   |-- grpc-build-file 
|   |-- c-build-file
```
However, I am not sure how to compile each language in the idl project.

**Comment by yjqg6666** [comment]
> All languages share protobuf-IDL, it would be good to separate IDL into individual projects.
Agreed.

**Comment by emeroad** [comment]
The build settings were removed from idl project because each project has different build methods.
- language version, compiler version, lib version, etc.

The idl-project contains only pure idl, and the build method should be set in individual projects.

**Comment by yjqg6666** [comment]
How about including the v2.2.2 version of idl into the pinpoint-grpc-idl and tagging it?

**Comment by emeroad** [comment]
I know that 2.3.0 and 2.2.2 are completely compatible.
Could you tell me why you need 2.2.2?

**Comment by yjqg6666** [comment]
It's better to depend on a released version (specified point of history) other than the master.

**Comment by emeroad** [comment]
2.2.2 has already been released and cannot be modified.
The current master branch requires idl-snapshot version for 2.3.0.

I think it's a problem with Versioning.

I'm going to mark the version with git tag.
Do you have a better idea?
- Version file??

**Comment by yjqg6666** [comment]
I mean taggin on grpc-idl project.

1. add v2.2.2 protos: 

> git checkout v2.2.2 && cd /grpc/src/main/proto && cp -Rv *.proto /path/to/pinpoint-grpc-idl/proto/v1 && git add . && git commit && git tag v2.2.2 && git push grpc_idl_remote v2.2.2

2. add the current master protos:
> git checkout master && cd /grpc/src/main/proto && cp -Rv *.proto /path/to/pinpoint-grpc-idl/proto/v1 && git add . && git commit  && git push grpc_idl_remote master

**Comment by emeroad** [comment]
Okay. Please make a PR for 2.2.2

**Comment by yjqg6666** [comment]
https://github.com/yjqg6666/gopinpoint has been replace with submodule pointing to pinpoint-apm/pinpoint-grpc-idl. It could be forked under namespace pinpoint-apm.
