### ISSUE TITLE
Pinpoint grpc module netty channel executionerror occur is ok?

### ISSUE THREAD

**Issue by cw-juyeonyu** [pinpoint-apm/pinpoint#7857]
I use pinpoint 2.2.2.

Today I find agent log message like below.

INFO  c.n.p.g.c.ChannelzUtils
-- ExecutionError 5-Socket-7 io.netty.channel.ChannelException: getsockopt() failed: Protocol not available

is this no problem? only information?

OS is centos 6.

**Comment by emeroad** [comment]
It's an information message.
If the agent calls getsockopt() when the socket is closed, a problem may occur.
