### ISSUE TITLE
[Live Demo] Shopping Api metadata not found issue

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7861]
Check one transaction detail page, ex [this one](http://125.209.240.10:10123/transactionDetail/apigw01%5E1606810576744%5E54254023/1620806186384/apigw01/-3794068978691195073). You will get API-METADATA-NOT-FOUND for the instance shopping.api01 of application Shopping-Api. 

The api metadata has not been saved, a re-deployment for the app may be needed.

**Comment by yjqg6666** [comment]
The same to Shopping-Order and Shopping-Payment.

**Comment by koo-taejin** [comment]
hi @yjqg6666 

This had resolved via restarting service. 
Thanks for letting me know about this.

After release 2.3.0, I am going to update all module to v2.3.0. 

thanks :)
