### ISSUE TITLE
[suggestion] upload release class jar & sources jar to Maven central repo

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#7863]
**Which module is your feature request related to?**
All, deployment related

**Is your feature request related to a problem?**
If the release class & sources jars were uploaded to maven central repository, the java developers can add provided dependencies to their project, learn& debug the pinpoint and plugins. No need to build the pinpoint project by themselves locally.

** solutions
./mvnw clean source:jar install deploy -Prelease

**Comment by emeroad** [comment]
I'm working on it.
https://issues.sonatype.org/browse/OSSRH-66408

The pinpoint snapshot has been deployed on the sonatype repo.
https://oss.sonatype.org/content/repositories/snapshots/com/navercorp/pinpoint/
