### ISSUE TITLE
Enable/Disable pinpoint agent in java using env varibale

### ISSUE THREAD

**Issue by theLazyCat775** [pinpoint-apm/pinpoint#7868]
Is there any env variable to enable/disable pinpoint agent in java?

For example in node, you can disable the agent by setting "PINPOINT_ENABLE=False".

**Comment by itnikita** [comment]
I set up pinpoint agent like this:
 JAVA_OPTS= ”-javaagent:/usr/local/pinpoint-agent/pinpoint-bootstrap.jar -Dpinpoint.agentId=MyIP -Dpinpoint.applicationName=MyAPPName"
i think you can disable this line to disable pinpoint agent.hopes help.

BTW,do you mean in docker?

**Comment by emeroad** [comment]
Resolved in https://github.com/pinpoint-apm/pinpoint/pull/7880

**Comment by theLazyCat775** [comment]
Thank you @emeroad , @yjqg6666 .
This is exactly what i was looking for.

@itnikita in k8s cluster.
