### ISSUE TITLE
about pinpoint-root.config -> profiler.sampling.rate=1

### ISSUE THREAD

**Issue by 1025044866xxy** [pinpoint-apm/pinpoint#7873]
in version 2.2.2, I see default sampling.rate = 1 but the reality is that 20 requests produce 1 data like this。

![DD3900D48E61F0E808B51BEECEF8342C](https://user-images.githubusercontent.com/49869116/118476253-d936c500-b73f-11eb-871b-7280f246373f.jpg)
![0C2C28F43017914A2C7E6F7E6D3B0023](https://user-images.githubusercontent.com/49869116/118476276-e0f66980-b73f-11eb-9da1-764923dba2df.jpg)
you can see many U.N Transactions

**Comment by dv-morais** [comment]
> in version 2.2.2, I see default sampling.rate = 1 but the reality is that 20 requests produce 1 data like this。
> 
> ![DD3900D48E61F0E808B51BEECEF8342C](https://user-images.githubusercontent.com/49869116/118476253-d936c500-b73f-11eb-871b-7280f246373f.jpg)
> ![0C2C28F43017914A2C7E6F7E6D3B0023](https://user-images.githubusercontent.com/49869116/118476276-e0f66980-b73f-11eb-9da1-764923dba2df.jpg)
> you can see many U.N Transactions

In reality there are two ways to change this parameter... 

1. Call the parameter directly while executing your java
example: -Dprofiler.sampling.rate=1

2. Edit the /agentdirectory/profiles/release/pinpoint.config with the parameter you wrote.


hope that I helped.

**Comment by 1025044866xxy** [comment]
thank you, I use first way can get all data.
