### ISSUE TITLE
Connection pool graph not working on JBOSS

### ISSUE THREAD

**Issue by dv-morais** [pinpoint-apm/pinpoint#7882]
Hello everyone

I had configured an agent to monitor a application running on a JBOSS, the agent worked but the connection pool graph is not working... as the screenshot below:

![image](https://user-images.githubusercontent.com/57958197/119047045-c7e5f680-b993-11eb-8b4e-2059b358b1cd.png)

is there anything extra that I need to configure for this metric to appear in graphics?

thanks everyone.

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#supported-modules
Please check out supported modules

**Comment by dv-morais** [comment]
Well... question answered.

Thanks.
