### ISSUE TITLE
The obtained sql statement shows the missing closing parenthesis

### ISSUE THREAD

**Issue by crabapplevip** [pinpoint-apm/pinpoint#7883]
####Describe the error
When pinpoint obtains and parses sql, it may lose the closing parenthesis when it encounters'', for example:

```
select u.user_no as userNo,ifnull(s.equipment,'') as equipment,ifnull(s.gender, '0') as gender from user u left join supply s on u.user_no = s.user_no where u.user_no =?
```

Will lose the closing parenthesis at ifnull(s.equipment,'') as equipment=>
```
select u.user_no as userNo,ifnull(s.equipment,'' as equipment,ifnull(s.gender, '0') as gender from user u left join supply s on u.user_no = s.user_no where u.user_no = ?
```

####What did you do to trigger the error?
Encountered a special business scenario, so a similar sql triggered scenario was simulated

pinpoint-agent-2.2.2.jar
pinpoint-collector-boot-2.2.2.jar
pinpoint-web-boot-2.2.2.jar
The simulated application is just a simple web query

Problematic sql(MySQL)
```
select
    u.user_no as userNo,
    ifnull(s.equipment,'') as equipment,
    ifnull(s.gender, '0') as gender
from
    user u
    left join supply s on u.user_no = s.user_no
where u.user_no = ?


select 
    u.user_no as userNo,
    ifnull(s.equipment,'0') as equipment,
    ifnull(s.gender, '') as gender 
from 
    user u 
    left join supply s on u.user_no = s.user_no 
where u.user_no = ?
```
Even a function is set to ", but the closing parenthesis is not lost
```
select 
    u.user_no as userNo,
    ifnull(s.equipment,'') as equipment,
    ifnull(s.gender, '') as gender 
from 
    user u 
    left join supply s on u.user_no = s.user_no 
where u.user_no = ?
```

####Expected behavior
When I debugged this, I didn’t lose the closing parenthesis anymore.
DefaultSqlParser.java see screenshot

After simulating several situations without losing the right parenthesis, maybe my sql is relatively simple, so the problem cannot be fully verified at present
####Screenshot
Simulated application
![image](https://user-images.githubusercontent.com/58198956/119109492-cbd94d80-ba53-11eb-9ffa-bc87b3c2ae4d.png)

issue
![image](https://user-images.githubusercontent.com/58198956/119104288-adbd1e80-ba4e-11eb-8d47-9661264a0b10.png)

after edited
![image](https://user-images.githubusercontent.com/58198956/119104162-849c8e00-ba4e-11eb-9c7e-45278fd0d82d.png)

####Log
not nedd log.
The sql obtained by the program is provided above
![image](https://user-images.githubusercontent.com/58198956/119106218-b0207800-ba50-11eb-84eb-7cced510bbc5.png)

####Other context
Tables built at will, just to simulate business scenarios where problems are encountered
```
-- auto-generated definition
create table supply
(
    uuid      varchar(64) not null
        primary key,
    user_no   char(18)    null,
    equipment char        null,
    gender    char        null
);


-- auto-generated definition
create table user
(
    uuid      varchar(64) not null
        primary key,
    name      varchar(12) null,
    age       int         null,
    user_desc char        null,
    habit     char        null,
    user_no   char(18)    null
);
```

Part of the SQL test after the modification to ‘i++’ did not lose the closing parenthesis, and the content in ‘’ is normal
```
select u.user_no as userNo,ifnull(s.equipment,'test_str') as equipment,ifnull(s.gender, '0') as gender from user u left join supply s on u.user_no = s.user_no where u.user_no != ''


select concat('hello,',u.name, ?)as hello, u.user_no as userNo from user u where 1 = 1 and u.user_no = '10010'


select concat('hello,',u.name, ' ')as hello, u.user_no as userNo from user u where 1 = 1 and u.user_no != ''


select concat('hello,',u.name, 'zhangsan')as hello, u.user_no as userNo from user u where 1 = 1 and u.user_no != '' and u.age > 20


select concat('pinpoint,',u.name, (select s.user_no from user s where s.user_no = '8888'))as hello, u.user_no as userNo from user u where 1 = 1 and u.habit != '2768' and u.age > 20

```

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/issues/6622

**Comment by jaehong-kim** [comment]
Thank you for your contribution.
