### ISSUE TITLE
Question about `spring-async-plugin`

### ISSUE THREAD

**Issue by hoverwinter** [pinpoint-apm/pinpoint#7885]
In spring 5.x, `@Async` methods are submitted with lambda. `com.navercorp.pinpoint.plugin.spring.async.SpringAsyncConfig#DEFAULT_ASYNC_TASK`:

![image](https://user-images.githubusercontent.com/7020808/119345954-25e44800-bccc-11eb-8c68-82fd21ffdf69.png)

And the plugin intercepts it with `DefaultClassNameMatcher`, which use `equals` of String. But the actual name of the lambda is like:

`org/springframework/aop/interceptor/AsyncExecutionInterceptor$$Lambda$672`

where the number `672` in the name is the global counter value of `java.lang.invoke.InnerClassLambdaMetafactory#counter` .

SO, how can it be matched ?

**Comment by hoverwinter** [comment]
More generally, lambda is not like anonymous inner class, which the name suffix number is the counter of  the enclosing class. When there are many lambda functions, such as Reactor, how to distinguish lambda functions in the same class?

**Comment by jaehong-kim** [comment]
@hoverwinter 
It seems to be a bug.
Thanks for reporting.
