### ISSUE TITLE
Is there any plans to deverlop an agent for lua ？

### ISSUE THREAD

**Issue by ONG-YA** [pinpoint-apm/pinpoint#7910]
**Which module is your feature request related to?**
Plugin/UI etc

**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
agent for lua 

**Describe alternatives you've considered**

**Additional context**
Is there any plans to deverlop an agent for lua ？

**Comment by emeroad** [comment]
Unfortunately we have no plans.
