### ISSUE TITLE
generate pinpoint agentId in kubernetes

### ISSUE THREAD

**Issue by 1314cc** [pinpoint-apm/pinpoint#7940]
Hello，I have a Kubernetes cluster and have run some applications, and the pinpoint collector and web application are not installed in the Kubernetes cluster.

Now my application agentId is determined by POD IP and release time, similar to $(POD_IP)_$(DEPLOY_TIME), which can form the correct agentID. Each time the POD is scheduled and restarted, a different AgentId will be generated. .

More and more AgentIDs affect observation. How to deal with this problem

**Comment by emeroad** [comment]
Please check the features below.

https://github.com/pinpoint-apm/pinpoint/releases/tag/v2.2.0
Added automatic agentId generation in 2.2.0

https://github.com/pinpoint-apm/pinpoint/issues/7788
And in 2.3.0, the agentName specification was added.
You can assign a POD ID to agentName.

**Comment by catherine703** [comment]
@1314cc 请问一下，你在k8s集群里面是怎么部署pinpoint的呢？

**Comment by 1314cc** [comment]
我们pinpoint是部署在k8s集群外部 @catherine703

**Comment by catherine703** [comment]
我们现在有一个问题，就是grpc接口都没有采集到，http接口的可以i正常采集，请问是什么问题呢？


在 2021年7月13日 ***@***.***> 写道：


我们pinpoint是部署在k8s集群外部 @catherine703
