### ISSUE TITLE
Webhook does not appear in alarm settings.

### ISSUE THREAD

**Issue by silverbellKim** [pinpoint-apm/pinpoint#7944]
#### What version of pinpoint are you using?
master/v2.2.2

#### Describe your problem**
I have set as follows to use webhook for alarm, but
Unlike the pinpoint document, the webhook does not appear when setting the alarm rule.
webhook_enable=true
webhook.receiver.url=http://xxxxxxxxx

I am running pinpoint web service using released binary, 
and additional setting values are set in the config/web.properties file and are being used. 
The above two setting values are also added to the same file and run.

**Comment by minwoo-jung** [comment]
The webhook function is not provided in version 2.2.2. It will be provided from version 2.3.0. 
For reference, version 2.3.0 will be released soon.

You can see that the code has been committed after the 2.2.2 version is released.
https://github.com/pinpoint-apm/pinpoint/commits/master?after=74bd062b1587ab031cd1689380612fcdd7b7f02c+244&branch=master
