### ISSUE TITLE
When I used pinpoint to monitor my system, an exception occurred（Too many open files）.We found that as the system runs, more and more duplicate xxx-plugin.jar are loaded, about 60,000+ times.how to solve this problem？

### ISSUE THREAD

**Issue by lobsterHe** [pinpoint-apm/pinpoint#7961]
#### Prerequisites
Please check the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://pinpoint-apm.github.io/pinpoint/faq.html), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran '...' with agent attached
2. '...' method invoked
3. '...' interceptor threw '...' exception

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by emeroad** [comment]
1.7.x is no longer supported. Please upgrade to the latest version.

Are you using hotdeploy?
Pinpoint does not guarantee stability on hotdeploy

**Comment by lobsterHe** [comment]
Just send http request by resttemplate。I found that using springboot1.4.x will report this error，but usr springboot2.x.x not will.

**Comment by lobsterHe** [comment]
we find is resttemplate bug,it is not pinpoint problem,thanks.
