### ISSUE TITLE
profiler.plugin.disable is unavailable

### ISSUE THREAD

**Issue by jiahaowong** [pinpoint-apm/pinpoint#7970]
What version of pinpoint are you using?
v2.2.2

Describe the bug
I'd like to disable pinpoint-jdk-http-plugin, I editor pinpoint.config and restart my service but it's not work.
After debug I found there are wrong method name 'getDisabledPlugins' in Class DefaultProfilerConfig.
If I modify method name from 'getDisabledPlugins' to 'setDisabledPlugins', it works.

What did you do to trigger the bug?
Steps to reproduce, for example:
1. modify %pinpoint-agent folder%/profiles/release/pinpoint.config, 
2. edit  'profiler.plugin.disable=com.navercorp.pinpoint:pinpoint-jdk-http-plugin' 
3. restart my service
4. check log file, disabledPlugins=[]

Logs
06-22 23:07:47.047 [           main] INFO  c.n.p.p.DefaultAgent                     -- DefaultProfilerConfig{profileEnable='true', activeProfile=release, logDirMaxBackupSize=5, profileInstrumentEngine='ASM', instrumentMatcherEnable=true, interceptorRegistrySize=8192, staticResourceCleanup=false, traceAgentActiveThread=true, traceAgentDataSource=true, dataSourceTraceLimitSize=20, deadlockMonitorEnable=true, deadlockMonitorInterval=60000, callStackMaxDepth=64, jdbcSqlCacheSize=1024, traceSqlBindValue=true, maxSqlBindValueSize=1024, samplingEnable=true, samplingRate=1, samplingNewThroughput=0, samplingContinueThroughput=0, ioBufferingEnable=true, ioBufferingBufferSize=20, profileJvmVendorName='null', profileOsName='', profileJvmStatCollectIntervalMs=5000, profileJvmStatBatchSendCount=6, profilerJvmStatCollectDetailedMetrics=false, profilableClassFilter=ProfilableClassFilter{profileInclude=[], profileIncludeSub=[]}, agentInfoSendRetryInterval=300000, applicationServerType='null', applicationTypeDetectOrder=[], pluginLoadOrder=[], disabledPlugins=[], propagateInterceptorException=false, supportLambdaExpressions=true, proxyHttpHeaderEnable=true, httpStatusCodeErrors=HttpStatusCodeErrors{errors=[5xx]}, injectionModuleFactoryClazzName='null', applicationNamespace='', customMetricEnable=false', customMetricLimitSize=10', uriStatEnable=false', getCompletedUriStatDataLimitSize=3}

**Comment by emeroad** [comment]
thank you for reporting

This bug was fixed in 2.3.0.
https://github.com/pinpoint-apm/pinpoint/pull/7939
