### ISSUE TITLE
Does Pinpoint support Couchbase

### ISSUE THREAD

**Issue by mathisharp** [pinpoint-apm/pinpoint#7981]
Hi Team
    
     Could you please confirm whether Pinpoint does support tracing for Couchbase. 
     Couchbase is not traced and even i don't see (+question mark) icon on the screen indicates a service that 
     Pinpoint does not recognize .

Any direction in this regard would be highly appreciated.

**Comment by RoySRose** [comment]
@mathisharp 
There is the list of supported modules in the [homepage](https://pinpoint-apm.github.io/pinpoint/main.html)
If it's not there, it's currently not tracable. However you can always contribute a couchbase-plugin and share with the world~ :)
