### ISSUE TITLE
"NOT FOUND" is displayed in Active Request

### ISSUE THREAD

**Issue by ujlub** [pinpoint-apm/pinpoint#7993]
#### What version of pinpoint are you using?
v2.2.2

#### Describe your problem**
After upgrading to version 2.2.2,
"NOT FOUND" is displayed in Active Request at the bottom of the screen.

I set it  in the agent configuration file as below.
profiler.tcpdatasender.command.accept.enable true
profiler.pinpoint.activethread true

And
I also have the same problem on the DEMO site(http://125.209.240.10:10123/main/realtime/ApiGateway@SPRING_BOOT).

#### Screenshots
![pinpoint 문의](https://user-images.githubusercontent.com/44011902/123892219-1fb14d80-d995-11eb-9654-fb1f89e3d203.png)

**Comment by koo-taejin** [comment]
hi @ujlub 

I am going to see if demo site has some problem. 
Thank you for the information.

Thanks :)

**Comment by koo-taejin** [comment]
@ujlub 

First of all, the demo site is became to normal.
The problem with the demo site was the connection between Curator and Zookeeper.

There are many different ways this issue can occur, so I can not be certain that the cause of the demo site is the same as yours.

1.  Curator and Zookeeper connection problem
2. Dead connection problem between collector and agent
3. etc ...

I haved tried to keep solving these problems. 
https://github.com/pinpoint-apm/pinpoint/issues/7959
https://github.com/pinpoint-apm/pinpoint/issues/7753
https://github.com/pinpoint-apm/pinpoint/issues/7543

Most of the problems will work normally when the collector and web are restarted.

If you tell me in more detail about your situation, I could analyze what is the your problem. 

Thanks :)

**Comment by ujlub** [comment]
After restarting the web, it works normally.
Thanks!
