### ISSUE TITLE
PINPOINT Server Error (Http failure during parsing bind.pipoint) in Call Stack view

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint#8072]
Hello,

We are getting PINPOINT Server Error as below while try to show bind SQL parameters in Call Stack view.

Below is our environment details. 

**PINPOINT Collector: 2.3.0
PINPOINT Web: 2.3.0
PINPOINT Agents: 2.0.0 / 2.2.2/ 2.3.0
HBase: 2.0.2
Client Databases: - Oracle / MySQL** 

![image](https://user-images.githubusercontent.com/5483940/126904845-d07ba906-fc16-4432-a593-893eb23dd92e.png)

thanks

**Comment by emeroad** [comment]
Could you provide more detailed information?
eg) stack trace, sql

**Comment by vic-kjs** [comment]
Hello,
I am also experiencing the same problem after the 2.3.2 update.
This is normal in version 2.2.2.
PINPOINT Collector: 2.3.2
PINPOINT Web: 2.3.2
PINPOINT Agents: 2.2.2 / 2.3.2
HBase: 2.1.8
Client Databases: - MySQL

**Comment by jinwook1** [comment]
I have same issue after upgrade to 2.3.2. (2.2.2 was ok)
It looks like POST to '/bind.pinpoint' returns form data body.
But it's response header content-type is application/json, so JSON.parse error occurred.

PINPOINT Collector: 2.3.2
PINPOINT Web: 2.3.2
PINPOINT Agents: 2.2.2 / 2.3.2

**Comment by vic-kjs** [comment]
[This is part of the error log.]

12-31 09:53:13.013 [o-8080-exec-167] WARN  c.n.p.w.c.ControllerExceptionHandler     -- Failed to execute controller methods. 
message:Request method 'GET' not supported, request:RequestInfo{method='GET', url='http://xxx.xxx.xxx:8080/bind.pinpoint', 
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported

**Comment by minwoo-jung** [comment]
You can find the cause by looking at the server's log.
If you share the log, we will analyze the problem together.

**Comment by emeroad** [comment]
`bind.pinpoint` only allows POST request.
However, there is a problem that the UI requests to GET.

**Comment by jinwook1** [comment]
@minwoo-jung 
We rollback server to 2.2.2 and I did not store the error message.
If I got the error again, I'll post the error message.

**Comment by minwoo-jung** [comment]
@jinwook1
There will be no error messages on the server. We have perfectly found the cause of the problem.
so there is no need to send us a message.
Thanks again for sharing. :)
