### ISSUE TITLE
when build source code show up  com.navercorp.pinpoint.grpc.trace  non-existent

### ISSUE THREAD

**Issue by ZhanChaoHan** [pinpoint-apm/pinpoint#8085]
when i excute command 'mvnw install -pl web -am -Dmaven.test.skip=true'   Execute to  pinpoint-profiler part  can not find 
com.navercorp.pinpoint.grpc.trace Is the source code missing？？

**Comment by ZhanChaoHan** [comment]
pinpoint version 2.3.0

**Comment by ZhanChaoHan** [comment]
The packaged source code is missing files

**Comment by LynHB** [comment]
how do you resolve?
