### ISSUE TITLE
[FR.] send caller application info regardless of sampling rate

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#8169]
**Which module is your feature request related to?**
agent

**Is your feature request related to a problem?**
When a request is not sampled, we can still capture(tcpdump)/record the request header Pinpoint-pAppName to know who is calling my app. If both applications have different sampling rate, the caller may be identified by "User", if we send the caller application info and use the recording request header feature, then we could know who is calling from a call tree.

A PR #8170 is made to resolve this issue.

**Comment by emeroad** [comment]
If the trace is not sampled, it's an optimization that removes unnecessary information, so it's not a bug.

I agree with your pr.
It seems appropriate to add a new option.

**Comment by yjqg6666** [comment]
It's not a bug but a feature(FR.=Feature Request). A configuration was added later and this feature is disabled by default, not breaking existing behavior.

**Comment by yjqg6666** [comment]
Closed. Related to #8557. Use a new configurable header to pass caller application name.
