### ISSUE TITLE
[FR.] support agent boot logger level config

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#8171]
**Which module is your feature request related to?**
Agent

**Is your feature request related to a problem?**
Too much logs are produced while bootstrapping and boot log level can not be configured. Some logs can be debug, only enabled when needed for debugging.
Can be configured by pinpoint.agent.bootlogger.loglevel.

**Comment by emeroad** [comment]
Thank you for your contribution.
