### ISSUE TITLE
Migrate to the official Pinpoint website gitbook platform

### ISSUE THREAD

**Issue by feelform** [pinpoint-apm/pinpoint#8188]
## github.com/pinpoint-apm/pinpoint
*  changes from `pinpoint-apm.github.io/pinpoint/` to `pinpoint-apm.gitbook.io/pinpoint/`
* removals for deployment GitHub.io scripts(deployGitPage.sh) and GitHub actions(homepage.yml)
* The page of the `Latest updates on Pinpoint` in `README.md` link is no longer maintained. so I have deleted it.
* When the PR is rebase, the wiki link at pinpoint-apm/pinpoint will also be modified.

**Comment by yjqg6666** [comment]
@feelform 
Could the building restricted to pinpoint-apm/pinpoint, excluding forks?

![image](https://user-images.githubusercontent.com/1879641/132277170-e3469af7-dbd1-49ed-83d3-41726e78818a.png)
