### ISSUE TITLE
netty-plugin doesn't work

### ISSUE THREAD

**Issue by Juninko** [pinpoint-apm/pinpoint#8199]
Hi Team,
I use pinpoint version : 2.3.0
I have bean checked netty version , pinpoint support > 4.1 , and I use 4.1.27.Final
netty config is open:
profiler.netty=true
profiler.netty.http=true
profiler.netty.http.param=true
profiler.netty.channel.close=true

call Channel:
gateway(zuul-netty) -- > serverA(springboot-tomcat) --> serverB(springboot-tomcat)

# There is no data of gateway,only serverA -- > serverB 
the server map of gateway:
![image](https://user-images.githubusercontent.com/27288713/132200375-2ad341f1-91b2-4e05-99e3-76bf9034f846.png)

the server map of serverA:
![image](https://user-images.githubusercontent.com/27288713/132201738-32e7d1da-9abc-4ca1-bb71-4315d5b4b9a0.png)
![image](https://user-images.githubusercontent.com/27288713/132201549-7509a8e4-23a2-4cc5-9df3-8b4e10fbbef8.png)

# then I modify source code：
![image](https://user-images.githubusercontent.com/27288713/132197443-99c60b27-217d-4431-8395-888b238739d2.png)

the server map of gateway:
![image](https://user-images.githubusercontent.com/27288713/132198026-01ee5640-4d05-43f4-8e62-75165ae998cb.png)

the server map of serverA:
![image](https://user-images.githubusercontent.com/27288713/132201976-bcfb8ab8-91f2-4c76-9fe3-fe1042d04c96.png)
![image](https://user-images.githubusercontent.com/27288713/132202182-254d18bd-4d0c-41ea-bbeb-6e790ad1649a.png)

# I check your source code , in this class HttpEncoderInterceptor , is the tarce begin in this method? It doesn't work
![image](https://user-images.githubusercontent.com/27288713/132199200-0acae61f-f002-4236-b103-49aa0d95c0c3.png)

## please help me T_T

**Comment by koo-taejin** [comment]
Hi @Juninko 

I am going to check it.

Thanks  :)

**Comment by koo-taejin** [comment]
@Juninko 

All tracing have to have EntryPoint. 
EntryPoint is start of tracing.

Image that you posted looks that it does not have EntryPoint. 
Please check the EntryPoint first and then try again.

Thanks :)

**Comment by Juninko** [comment]
@koo-taejin 
In the last picture that I posted，
final AsyncContext asyncContext = getAsyncContext(args[1]);
        if (asyncContext == null) {
            logger.info("AsyncContext not found");
            return;
        }
'asyncContext' always null;

this method have Not Executed:
// entry scope.
entryAsyncTraceScope(trace);

Is the EntryPoint here?

**Comment by koo-taejin** [comment]
@Juninko 

It could be occured because the AsyncContext is not created because it is not executed in EntryPoint.
Would you like to search the issue for EntryPoint?

**Comment by Juninko** [comment]
@koo-taejin Ok , I will check the issue for EntryPoint. thanks :)

**Comment by Juninko** [comment]
@koo-taejin Hi，
According to your advice , I set this property from pinpoint.config, and it work.
profiler.entrypoint=com.netflix.zuul.filters.endpoint.ProxyEndpoint.apply

thanks again :)
