### ISSUE TITLE
Marking Transaction as Fail in 4XX status (pinpoint version 1.8.4)

### ISSUE THREAD

**Issue by hkhong91** [pinpoint-apm/pinpoint#8211]
**What version of pinpoint are you using?**

1.8.4

**Describe your problem**

API에서 SQLException이 발생하면 트랜잭션을 실패로 표시하고 에러 카운트를 증가시킵니다. (in Spring Boot)
Exception으로 캐치하고 커스텀한 MyException을 발생시켜서 상태 코드를 4XX로 응답하였습니다.
이 경우에 트랜잭션을 실패로 표시하지 않고, 에러 카운트도 증가하지 않는 것은 불가능한가요?

If the API throws an SQLException, it marks the transaction as failed and increments the error count. (in Spring Boot)
Catch it as an Exception and throw a custom MyException, responding with a status code of 4XX.
Is it impossible in this case not to mark the transaction as failed and not to increment the error count?

**What have you done?**

```
profiler.http.status.code.errors=5xx
profiler.spring.beans.mark.error=false
```
```
try {
  couponRepository.save(coupon);
} catch (Exception exception) {
  log.error(exception.getMessage(), exception);
  throw new CouponException();
}
```
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'ABC' for key 'PRIMARY'
Wrapped by: org.hibernate.exception.ConstraintViolationException: could not execute statement
Wrapped by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

![image](https://user-images.githubusercontent.com/53270060/132430931-6bbe346d-4342-4b0f-a357-f1d198e6ede8.png)

![image](https://user-images.githubusercontent.com/53270060/132430977-34537fec-d354-4477-bec2-c25a909353b8.png)

**Comment by emeroad** [comment]
Unfortunately, this feature is not supported.

**Comment by hkhong91** [comment]
Thank you for the answer.
