### ISSUE TITLE
[FR.] change logger pattern automatically for per-request logging (configurable)

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#8222]
**Which module is your feature request related to?**
agent

**Is your feature request related to a problem?**
Related to [per-request logger feature ](https://github.com/pinpoint-apm/pinpoint/blob/master/doc/per-request_feature_guide.md). This feature need changing logger patterns of every applications.

**Describe the solution you'd like**
Intercept log pattern and change the pattern according to configurations( where to insert into the pattern, what to insert into the pattern) only if a enable config for this feature is enabled.

A PR #8228 was made.

**Comment by emeroad** [comment]
@yjqg6666 
Thank you for your contribution
