### ISSUE TITLE
log4j2 plugin-it only tested log4j2 of version 2.12.1

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#8246]
#### What version of pinpoint are you using?
master

#### Describe the bug
![2021-09-17_16-37](https://user-images.githubusercontent.com/1879641/133752237-c3a8c02c-a527-440a-8e22-ec3639a5a65c.png)

The tested version should be 2.0.2 but 2.12.1 was used.

The PR #8247 could fix it.

**Comment by emeroad** [comment]
@yjqg6666 
Thank you for your contribution
