### ISSUE TITLE
Setting Agent Name in Java args doesn't seem to work

### ISSUE THREAD

**Issue by unc1** [pinpoint-apm/pinpoint#8248]
Hi,
I have configured the agent on my Tomcat application, and set the agentName in the Tomcat java options. However, it doesn't seem to show up in Pinpoint, I still see the application ID identifier.  In any of the places where agentName should show up, it's blank. I checked the logs and it shows up as 'null'. I do have a need to have separate agents names as I have multiple tomcat instances running on each of my hosts. 

Here is my Java opts config.

-Dpinpoint.agentName=hostname:port

Is there anything I am missing in my configuration? Thanks.

What is interesting is that I checked the logs on the agent and found it doesn't send the agentName, even though it's configured and received via the  Java ops.

Here are the lines from the logs.

[           main] INFO  c.n.p.p.u.SystemPropertyDumper           -- - pinpoint.agentName=hostname:port
 [           main] INFO  c.n.p.p.DefaultAgent    -- - pinpoint.agentName=hostname:port

And here it's ''.
 [nfoSender-Timer] INFO  c.n.p.p.AgentInfoSender                  -- Sending AgentInfo AgentInfo{agentInformation=DefaultAgentInformation{agentId='_M_-D68XR1WGcD8gzQjLuA', agentName='',

**Comment by yjqg6666** [comment]
@unc1 The agent name you provided is in incorrect format. The pattern  "[a-zA-Z0-9\\._\\-]+" is checked. Replace ":" with any of ".", "_" or "-". In your agent log you could find a log reporting incorrect format.

**Comment by unc1** [comment]
Thank you! That fixed the issue!
