### ISSUE TITLE
Ambiguous ClusterPoint

### ISSUE THREAD

**Issue by davide-parini** [pinpoint-apm/pinpoint#8282]
Hello, we are running:
- Pinpoint 2.0.4 agent on JBoss 7 with OpenJDK 11.
- Pinpoint 2.0.4 collector and web.

During the weekend some networking issues caused communication problems between agents and collector. When the networking issue has been resolved, many of our Pinpoint-monitored applications were in this state:
![image](https://user-images.githubusercontent.com/38081480/135244262-5827a006-9e68-46e8-a5d3-0f9ceababd8b.png)
What looks strange to me is that some of our applications were running more than one Pinpoint-monitored JVM **on the same host**, having some of the JVMs experiencing the error while others not.

It seems like, for some reason, the collector has been able to get back on track only some of the agents after the networking failure.

Agent logs are clean: after the errors reported during the networking issues, no `ERROR` or `WARN` entries.
Collector logs, instead, report this problem upon opening MyApp on Pinpoint web:
```
2021-09-29 11:31:32 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Ambiguous ClusterPoint MyApp, host.name, 1630670645783 (Valid Agent list=[com.navercorp.pinpoint.collector.cluster.GrpcAgentConnection@66649590, com.navercorp.pinpoint.collector.cluster.GrpcAgentConnection@66649590]).
2021-09-29 11:31:32 [WARN ](c.n.p.c.c.ClusterPointRouter       ) handleStreamRouteCreate failed. command:TCmdActiveThreadCount(), routeResult:NOT_FOUND
```
`MyApp` and `host.name` are replacements for out real application names and host names. This `WARN` appears only with regard to the failing `host.name`s so i think this is a strong clue on what is causing the issue.

Is there a bug or something preventing all agents to get back to normal monitoring after a networking error occurs? Maybe some idle or timeout configuration do be tuned?

**Comment by davide-parini** [comment]
Adding some info: the agents reporting the error in the "active threads" view are perfectly working with respect to all the other functionalities (scatter diagram, traces, inspector...).

**Comment by koo-taejin** [comment]
Hi @davide-parini 

If possible, please update pinpoint version to 2.3.0.
There are some issues that is related with cluster at version 2.0.x because we changed transport layer to grpc since 2.0.0.

Thanks :)

**Comment by davide-parini** [comment]
Thank you for your feedback @koo-taejin, we are going to upgrade all our applications to the latest release in the next few months.
