### ISSUE TITLE
Pinpoint could collect server info (CPU, Memory) but no trace info.

### ISSUE THREAD

**Issue by dtvn-duytq7** [pinpoint-apm/pinpoint#8293]
- I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v2.2 and hbase v1.8

#### Describe the bug
Like the bug on Jetty web, I install agent pinpoint v2.2 into module webservice wrapper :
- pinpoint could collect server info (CPU, Memory) but no trace info.
- no unusual log (WARN or ERROR level).

#### Logs
- no unusual log (WARN or ERROR level).

#### Additional context
I add the path agent into java wrapper config file to run module service : 
wrapper.java.additional.16=-javaagent:/u01/data_2g/code_ko_xoa/Pinpoint-agent/pinpoint-agent-2.3.0/pinpoint-bootstrap-2.3.0.jar
wrapper.java.additional.17=-Dpinpoint.agentId=Data3G_121-9001
wrapper.java.additional.18=-Dpinpoint.applicationName=Data3G_121-ws_data_9001

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#supported-modules
Please check the support module.
