### ISSUE TITLE
Support to feign?

### ISSUE THREAD

**Issue by maojunling** [pinpoint-apm/pinpoint#8309]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#supported-modules
Please check the supported module.
