### ISSUE TITLE
Support the highest version of hbase

### ISSUE THREAD

**Issue by lin3fei** [pinpoint-apm/pinpoint#8389]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

such as the title, which hbase highest version supported the new version 2.3.1?
i tried 2.4.8, but start pinpoint-collector-boot-2.3.1.jar tip error that:
Caused by: com.navercorp.pinpoint.common.hbase.HBaseAccessException: HBase version compatibility violation HBaseClient:HBaseVersion{supportedVersion=[0.9, 1.]} V1, HBaseServer:2.4.8

so i want to know which new version of hbase to use.

thanks.

**Comment by yjqg6666** [comment]
Try pinpoint-hbase2-****.jar, since you'r using hbase 2.x.  Jars of pinpoint-**.jar are for HBase 1.x. HBase 2.0.x is recommended.
