### ISSUE TITLE
Un sample request keep tracing but not record span and span event and send data

### ISSUE THREAD

**Issue by zlp1992** [pinpoint-apm/pinpoint#8431]
Hi, We find Pinpoint `PtxId` in log file is very useful when find and solve problem. But when no sample, there is no any information.
So is it possible when no sample, Pinpoint doesn't record span and span event and send data, but just keep tracing and set `PtxId` in `MDC`,

**Comment by minwoo-jung** [comment]
I don't know exactly what you mean, but I'll answer based on what I understand.
For non-sampling requests, ptxid is not generated. This is because transactionid cannot be maintained if it is not profiled.

It has nothing to do with pinpoint, but I'll give you some advice.
If you want to classify logs by request, it is recommended that you create a unique ID yourself, record it in the log MDC, and log it.

**Comment by minwoo-jung** [comment]
Additionally, if increasing the pinpoint sampling rate is a burden, it is recommended to set the unnecessary profiling options to false in the pinpoint.config configuration file as much as possible. This will lower resource utilization.

**Comment by zlp1992** [comment]
@minwoo-jung Hi,
Yes, We can create a unique ID, but it can not pass to other applications, so you can not relate requests between different application (just like `PtxId` when sampling). for example:
```
A application has unique ID id1 for request r1.
When B application receives request r1, it creates unique ID id2.
The problem is you can not use a global id to connect request r1 between A and B in that non-sampling case, but if sampling you can use PtxId.
```

What we want to do is relate requests between different application when no sample, so we can use a global id (`PtxId` when sampling ) to search all log in all applications to locate problems.

As for pinpoint, we can create `DisableTrace` with new created `TraceId`, just the same as creating `DefaultTrace` when sampling, also we can modify http(httpclient3, httpclient4...) plugin and thread plugin to pass `DisableTrace` to another application or another thread.

Is that possible or meaningful?

**Comment by emeroad** [comment]
Your requirement as I understand it is below.
Propagate PTxID to the remote node even when tracing is not performed.

This is essentially the same situation as the sampling-rate 100%.
Because in order to propagate the pTxId to every request, we need a stack trace of every call.
Same as the  sample-rate 100%, except that the span propagating to the collector is reduced.

**Comment by zlp1992** [comment]
> Your requirement as I understand it is below. Propagate PTxID to the remote node even when tracing is not performed.
> 
> This is essentially the same situation as the sampling-rate 100%. Because in order to propagate the pTxId to every request, we need a stack trace of every call. Same as the sample-rate 100%, except that the span propagating to the collector is reduced.

Do we really need a stack trace of every call when non-sampling? I find `DisableTrace` source code in pinpoint , there is no call stack. You just need to add `TraceId` to `DisableTrace` and only when sampling we do `traceBlockBegin`, if non-sampling we just bind `DisableTrace` with created `TraceId` to thread, no `Span` and no `SpanEvent` and no storage(send to collector). if http call happenes, we set non-sampling `TraceId` in http header by modifying http related plugin and if async thread call happens, we bind current non-sampling `TraceId `to another thread by modifying thread plugin

**Comment by emeroad** [comment]
It appears that this feature requires significant changes.

The expected change points are as follows.

## Feature title : lightweight tracing specification for distributed log tracing
- Lightweight stack trace for AsyncContext propagation and performance
- Modify interceptor in Remote call library
- Backwards compatibility

At least the above verification is required.
It's hard to know exactly how many additional issues there will be.
If you need this feature, please suggest the relevant specifications.

https://github.com/pinpoint-apm/pinpoint/pull/8217
This issue creates a separate Local-ID for log tracing.
However, distributed log tracing is not supported.

**Comment by zlp1992** [comment]
Yes, it requires a lot changes. I'm not sure its value or is it worth for distributed log tracing when no sampling. But we are trying to do this.

**Comment by yjqg6666** [comment]
@zlp1992 Try #8217 + #8222 the first feature is what you need, a new MDC variable is available. Using the second feature also would be better.

**Comment by zlp1992** [comment]
@yjqg6666 #8217  may work for me
