### ISSUE TITLE
How to modify the log directory for pinpoint collector？

### ISSUE THREAD

**Issue by 1314cc** [pinpoint-apm/pinpoint#8446]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [-] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

Deploying directly with the jar package, configuring log.file.path=/logs does not work

`nohup java -jar pinpoint-collector-boot-2.3.1.jar --spring.config.additional-location=./collector.properties >/dev/null 2>&1 &`

collector. properties: 

```
[root@node2 pinpoint-binary]# cat collector.properties

pinpoint.zookeeper.address=10.11.25.142
logging.file.path=/logs

```

Logs are generated only in the current directory

![image](https://user-images.githubusercontent.com/5126487/144019494-9f5a9d8f-8d98-42a4-a844-45288e85c04b.png)

**Comment by emeroad** [comment]
Use `-Dlogging.file.path` 
  - java `-Dlogging.file.path=$PATH` ~~~~

or 

Modify `profiles/${PROFILE}/log4j2.xml`
   - https://github.com/pinpoint-apm/pinpoint/blob/master/collector/src/main/resources/profiles/release/log4j2.xml#L5

**Comment by 1314cc** [comment]
`logging.file.path` does not take effect in the `spring.config.additional-location` configuration file. 

THX!
