### ISSUE TITLE
New UI: improve navigation; Global Navigation Bar

### ISSUE THREAD

**Issue by BillionaireDY** [pinpoint-apm/pinpoint#8480]
- Remove header and Add global navigation into left side 

![image](https://user-images.githubusercontent.com/14918660/145334748-25b9735e-e5fe-4ea1-9bc8-9389a0caff34.png)

![image](https://user-images.githubusercontent.com/14918660/145334794-c2bf3000-62be-441e-a5e5-707c1707a830.png)

![image](https://user-images.githubusercontent.com/14918660/145334866-8e049e09-5ca5-43eb-96fe-37bbf7278eec.png)

**Comment by yjqg6666** [comment]
I hope/suggest the left-sidebar would take the space as little as possible.

**Comment by yjqg6666** [comment]
What about moving instance dropdown together with application dropdown?

**Comment by binDongKim** [comment]
@yjqg6666 As you can see, user can minimize the left-sidebar.
