### ISSUE TITLE
Inspector heap chart shows wrong memory  size

### ISSUE THREAD

**Issue by xllove-moon** [pinpoint-apm/pinpoint#8589]
- [Y] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

set vm -xmx2G but chart get 2.15G
![image](https://user-images.githubusercontent.com/7285069/148742400-7bd55a9f-a064-4680-a44d-4f22a78220c6.png)

I look through source code,The problem should be at the web js
for example,in this file "web/src/main/angular/src/app/core/components/inspector-chart/agent-jvm-non-heap-chart-container" at 130 line

```
    convertWithUnit(value: number): string {
        const unitList = ['', 'K', 'M', 'G'];

        return [...unitList].reduce((acc: string, curr: string, i: number, arr: string[]) => {
            const v = Number(acc);

            return v >= 1000
                ? (v / 1000).toString()
                : (arr.splice(i + 1), Number.isInteger(v) ? `${v}${curr}` : `${v.toFixed(2)}${curr}`);
        }, value.toString());
    }

```
It should be 1024，not 1000?

**Comment by emeroad** [comment]
Pinpoint uses Memory MXBean API, so there is no problem at all.
- https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryMXBean.html

If you are curious about this, analyze the memory option of the jdk you are using.

**Comment by binDongKim** [comment]
@xllove-moon 
Thanks for the report. I'll look into it.

**Comment by binDongKim** [comment]
@xllove-moon 
'K' could be 1000 or 1024 depends on the context and the unit number should've been 1024 in the memory side. 
I've corrected it through https://github.com/pinpoint-apm/pinpoint/pull/8592
