### ISSUE TITLE
 pinpoint 2.0.4 (quickstart)

### ISSUE THREAD

**Issue by seocho2360** [pinpoint-apm/pinpoint#8594]
Hello.
I am using the PINPOINT 2.0.4 version powered by Quickstart.

Please contact us because we need to take action regarding the recent log4j vulnerability.

The information below is running with quickstart, so please refer to it and reply.

1. About log4j version used in Pinpoint 2.0.4

2. If you are using the log4j vulnerable version, how to update it while running with quickstart

thank you.

**Comment by emeroad** [comment]
2.0.4 is no longer supported.
Please use the latest version.

**Comment by seocho2360** [comment]
I know it's difficult to get support because the service has ended, but can't I just get information on how to check the log4j version information?

**Comment by emeroad** [comment]
Check inside of `quickstart/target/pinpoint-quickstart-testapp-$VERSION.jar`.

**Comment by seocho2360** [comment]
Hello.
Please contact us regarding pinpoint.
Is the quickstart service not provided from pinpoint v2.3.3 where the log4j vulnerability is addressed?
 
There was a path of pinpoint/quickstart/bin , but since v2.0.4, there is no bin directory in that path.
 
Is there a way to experience pinpoint as simple as quickstart?
-----Original Message-----
