### ISSUE TITLE
[Proposal] Support alternative storage engine, such as Cassandra

### ISSUE THREAD

**Issue by yjqg6666** [pinpoint-apm/pinpoint#8650]
**Which module is your feature request related to?**
storage

**Is your feature request related to a problem?**
HBase may not be easy for everyone to try Pinpoint.

**Describe the solution you'd like**
Support alternative storage engines which can be configured. Apache Cassandra which is also a column-family-based DB could be supported as production-ready.  MySQL or H2 can also be supported, just for easy demo.

**Comment by emeroad** [comment]
It seems possible if Dao interface is well designed.
eg)
```java
@Import({HbaseStorageEngine.class or CassandraStorageEngine.class})
public class CollectorApp {
...
}

```

Unfortunately, we do not have time to maintain various storage engines.
It is recommended to separate each storage engine into a different git repository.
 - eg) pinpoint-thrid-patry/pinpoint-cassandra-storage-engine
