### ISSUE TITLE
Apache HTTPD reverse proxy - display client real IP

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint#8655]
Hi,

I have successfully configured my Apache HTTPD reverse proxy to pass the  HTTP headers  and now able to see "PROXY(APACHE)" as  "1m 39s 186ms from now(22:19:07 040), idle: 89%, busy: 10%". I need to pass client real IP to PINPOINT. I tried to override "app" as app=%{X-Forwarded-For}i  and no any luck to log client ip. 

Please let me know how to do this since we need to trace transactions by using real client ip. 
![tp](https://user-images.githubusercontent.com/5483940/153917388-72b19678-53d4-4224-a52e-b129fff63fb5.png)

**Comment by emeroad** [comment]
Take a look at `realipheader` in pinpoint.config.
```
# original IP address header
# https://en.wikipedia.org/wiki/X-Forwarded-For
#profiler.tomcat.realipheader=X-Forwarded-For
# nginx real ip header
#profiler.tomcat.realipheader=X-Real-IP
# optional parameter, If the header value is ${profiler.tomcat.realipemptyvalue}, Ignore header value.
#profiler.tomcat.realipemptyvalue=unknown
```

**Comment by phuc16102001** [comment]
Hi @emeroad, I am having a problem with the X-Real-IP header. Currently, I use a Nginx reverse proxy and forward the request to the Tomcat servlet. However, the `Client IP` always 127.0.0.1 not the real client IP. 

I have tried to edit the `profiler.server.realipheader` params to `X-Real-IP` and it worked. I want to know that **what is the default config** for that params? Because it I see from the default `pinpoint-root.config` file, it is leaved empty.

Here is my Nginx conf:

```
server {
        listen       80;
        server_name  localhost;
        root         /home/vuongphuc/deploy;
        etag         off;

        set_real_ip_from 10.0.0.0/8;
        real_ip_header N-Client-IP;
        
        # Forward to Tomcat
        location / {
            proxy_set_header   Host $host;
            proxy_set_header   Connection "";
            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_headers_hash_max_size 512;
            proxy_headers_hash_bucket_size 128;

            proxy_http_version 1.1;
            proxy_max_temp_file_size 0;
            proxy_redirect off;
            proxy_read_timeout 240s;
            proxy_buffering off;
            proxy_ignore_client_abort on;

            proxy_pass         http://127.0.0.1:8080/;
        }
    }
```

Thank you!
