### ISSUE TITLE
Monitoring a specific Class's Method in Pinpoint

### ISSUE THREAD

**Issue by MoonStruckHorrors** [pinpoint-apm/pinpoint#8669]
- [X] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

With pinpoint we can monitor a specific class by adding it to `profiler.include`. Is it feasible to monitor just a single method from that class instead of everything?

**Comment by jaehong-kim** [comment]
@MoonStruckHorrors 

Use the profiler.entrypoint setting.
~~~
# Needs to be a comma separated list of fully qualified method names. Wild card not supported.
profiler.entrypoint=
# Ex: foo.bar.MyClass.myMethod, foo.bar.MyClass.anotherMethod
~~~

**Comment by MoonStruckHorrors** [comment]
Thanks. @jaehong-kim
