### ISSUE TITLE
Data Export from Hbase / Disable binary encoding

### ISSUE THREAD

**Issue by FaHaas** [pinpoint-apm/pinpoint#8671]
Hi all,

my goal is to easily export the trace data which i gathered with pinpoint.

are there any possibilities to disable the binary encoding of the stored data in the code?
I did read the information in #6423 and also the entry #7499 without a response which was also asking about the export of the performance data.

Thanks in advance for any hints and suggestions for my "problem" :)

Cheers,
Fabian

**Comment by emeroad** [comment]
There is no way to disable the binary format.

Please refer to the decoder below.
https://github.com/pinpoint-apm/pinpoint/tree/master/web/src/main/java/com/navercorp/pinpoint/web/dao/hbase

**Comment by FaHaas** [comment]
Thanks for that.

Would it be possible to provide an example on how to use these decoder/s in hbase?
