### ISSUE TITLE
Is there any way how to improve problem with unnecessary HTTP Method?

### ISSUE THREAD

**Issue by YoongJwe** [pinpoint-apm/pinpoint#8679]
Hello.
I am setting up and testing our APM environment by using version 2.3.3 of pinpoint-web and pinpoint-collector.
The result of a security vulnerability scan shows that there has been unnecessary HTTP Method (OPTIONS, TRACE).
I think maybe this issue caused by imbedded tomcat.
I look forward to hearing your advice on how we can improve it.
I ask for your interest and advice on this matter. Thank you so much.

**Comment by emeroad** [comment]
Refer to spring-boot configuration.
https://stackoverflow.com/questions/57519676/restrict-put-delete-and-options-request-in-springboot
https://stackoverflow.com/questions/35133942/spring-boot-disable-http-methods

Could you give me a PR after fixing this problem?

**Comment by YoongJwe** [comment]
In fact, in order to test a guide that is similar to your advice, I already tried building source code of pinpoint-web and pinpoint-collector before modifying it in the first place.
However, as the result of building the source code, the size of executable file(*.jar) of pinpoint-web and pinpoint-collector was very different from that of the executable file uploaded on the official release note(v2.3.3), and also it did not even run normally.
Please focus on compiled file size as the results.

**> The result of building pinpoint-web**
```
ubuntu@monitoring-inception-dev:~/oyj/pinpoint/web/target$ ll -h
total 26M
drwxrwxr-x 10 ubuntu ubuntu 4.0K Feb 21 04:35 ./
drwxrwxr-x  5 ubuntu ubuntu 4.0K Feb 17 01:12 ../
drwxrwxr-x  2 ubuntu ubuntu 4.0K Feb 17 01:15 archive-tmp/
drwxrwxr-x  7 ubuntu ubuntu 4.0K Feb 17 01:13 classes/
drwxrwxr-x  2 ubuntu ubuntu 4.0K Feb 21 01:19 deploy/
drwxrwxr-x  3 ubuntu ubuntu 4.0K Feb 17 01:12 generated-sources/
drwxrwxr-x  2 ubuntu ubuntu 4.0K Feb 17 01:12 mapper/
drwxrwxr-x  2 ubuntu ubuntu 4.0K Feb 17 01:14 maven-archiver/
drwxrwxr-x  3 ubuntu ubuntu 4.0K Feb 17 01:12 maven-status/
drwxrwxr-x  7 ubuntu ubuntu 4.0K Feb 21 04:35 pinpoint-web/
-rw-rw-r--  1 ubuntu ubuntu 9.4M Feb 21 01:19 pinpoint-web-2.4.0-SNAPSHOT-frontend.jar
-rw-rw-r--  1 ubuntu ubuntu  17M Feb 21 01:19 pinpoint-web-2.4.0-SNAPSHOT.jar
```

**> The result of building pinpoint-collector**
```
ubuntu@monitoring-inception-dev:~/oyj/pinpoint/collector/target$ ll -h
total 648K
drwxrwxr-x 7 ubuntu ubuntu 4.0K Feb 17 01:11 ./
drwxrwxr-x 4 ubuntu ubuntu 4.0K Feb 17 01:11 ../
drwxrwxr-x 5 ubuntu ubuntu 4.0K Feb 17 01:11 classes/
drwxrwxr-x 2 ubuntu ubuntu 4.0K Feb 21 01:17 deploy/
drwxrwxr-x 3 ubuntu ubuntu 4.0K Feb 17 01:11 generated-sources/
drwxrwxr-x 2 ubuntu ubuntu 4.0K Feb 17 01:11 maven-archiver/
drwxrwxr-x 3 ubuntu ubuntu 4.0K Feb 17 01:11 maven-status/
-rw-rw-r-- 1 ubuntu ubuntu 620K Feb 17 01:11 pinpoint-collector-2.4.0-SNAPSHOT.jar
```

The guides I referred to are the following three guides.

1. https://pinpoint-apm.gitbook.io/pinpoint/getting-started/installation
2. http://pinpoint-apm.github.io/pinpoint/installation.html
3. https://github.com/pinpoint-apm/pinpoint/blob/master/BUILD.md

I need help with what's wrong and whether I need more additional build settings.

**Comment by emeroad** [comment]
the binary location is /deploy.
See the /deply directory.
