### ISSUE TITLE
Hbase version

### ISSUE THREAD

**Issue by LIUjinytao** [pinpoint-apm/pinpoint#8680]
I use pinpoint-collector2.3.3.
error:
Invocation of init method failed; nested exception is com.navercorp.pinpoint.common.hbase.HBaseAccessException: HBase version compatibility violation HBaseClient:HBaseVersion{supportedVersion=[0.9, 1.]} V1, HBaseServer:2.3.6.
I can't find any documents for 2.3.3.

**Comment by emeroad** [comment]
You should use `hbase2-module` below.
https://github.com/pinpoint-apm/pinpoint#compatibility
