### ISSUE TITLE
Need to bump java mail library

### ISSUE THREAD

**Issue by eugene70** [pinpoint-apm/pinpoint#8683]
#### What version of Pinpoint are you using?
v.2.3.3

#### Bug Description
SMTP fails in batch v2.3.3.

Recently we upgraded from Pinpoint v2.2.0 to v2.3.3.
It was only then that we realized that the alarm notification feature had been decoupled from the web.
I found some TLS errors on the Office365 email server when setting up the deployment.
We guessed that the problem was a TLS v1.2 issue.
I upgraded to the latest JDK8, but it fails.
Finally, we found that the pinpoint batch uses a very old Java mail library v1.4.7.

After replacing "mail-1.4.7.jar" with "jakarta.mail-1.6.7.jar" this problem was resolved.

**Comment by eugene70** [comment]
## Error Message with jdk8u191:
---
org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 421 4.7.66 TLS 1.0 and 1.1 are not supported. Please upgrade/update your client to support TLS 1.2. Visit https://aka.ms/smtp_auth_tls. [SL2PR01CA0001.apcprd01.prod.exchangelabs.com]
...

**Comment by eugene70** [comment]
I found that this is already applied but not v2.3.3.

https://github.com/pinpoint-apm/pinpoint/commit/77a861e2e4d2a3e2cf2da8f405b8c70349b9cd74

**Comment by eugene70** [comment]
Until the next release, you can do the following proactively:
```
unzip pinpoint-batch-2.3.3.jar
rm BOOT-INF/lib/mail-1.4.7.jar
mv jakarta.mail-1.6.7.jar BOOT-INF/lib/
jar -cvfm0 new-batch.jar META-INF/MANIFEST.MF BOOT-INF/ META-INF/ org/
```

**Comment by minwoo-jung** [comment]
@eugene70 
Thank you for a detailed description.
