### ISSUE TITLE
No database call visible in TOMCAT application

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint#8687]
Currently we are monitoring TOMCAT application server by using PINPOINT APM agent and this TOMCAT instance communicate another four TOMCAT instance which are produced messages over IBM ActiveMQ. We are able to see message flow between each TOMCAT instance but not able to see database call which are pointed to SQLServer. Also, we are not able to see any failed transactions and when we get the TOMCAT error log then we are able to see some failed transactions. 
Below is the corelation diagram for the solution

![image](https://user-images.githubusercontent.com/5483940/156933707-2626b125-afa6-461d-a563-90bc7532a27c.png)

![image](https://user-images.githubusercontent.com/5483940/156933736-cb81adae-5a6c-4e70-9614-f09938774d37.png)

**Comment by dv-morais** [comment]
Set this as your JVM parameters

-Dprofiler.jdbc.mssql=true
-Dprofiler.jdbc.mssql.tracesqlbindvalue=true

you can find these parameters at "pinpoint.config" inside the folder of the profiler that you are using.

**Comment by snmsmanager** [comment]
issue has resolved .. thanks
