### ISSUE TITLE
Servers List not marked invalid or red

### ISSUE THREAD

**Issue by liucx1201** [pinpoint-apm/pinpoint#8696]
pinpoint version ：2.3.3

The historical pod container has been destroyed, but the page is not marked invalid or red

**Comment by liucx1201** [comment]
time one date

**Comment by liucx1201** [comment]
@emeroad help

**Comment by liucx1201** [comment]
![image](https://user-images.githubusercontent.com/40434832/157566801-dfdd66f3-9288-40f2-a6cd-c64b6b50b4b1.png)

**Comment by emeroad** [comment]
If you use `-Dpinpoint.container` option when starting the pinpoint agent, 
you can shorten the life cycle of the server.
