### ISSUE TITLE
why application search input at least 3 characters are required

### ISSUE THREAD

**Issue by lenkaxin** [pinpoint-apm/pinpoint#8802]
The query is not responding when I type two characters
![image](https://user-images.githubusercontent.com/20302561/164590987-b038e86a-4c8d-45a4-b6ba-4b7aca930077.png)

**Comment by minwoo-jung** [comment]
@binDongKim Please answer this question.

**Comment by binDongKim** [comment]
@lenkaxin 
We have set the minimum text length as 3 for the search because the search with lower than 3 characters wouldn't be much useful.
