### ISSUE TITLE
Monitoring IBM ESB (Enterprise Service Bus) database transactions.

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint#8827]
Hello,
I am using PINPOINT latest versions (2.3 and 2.4 release) to monitor IBM ESB server and agents have successfully bound and able to see the application transactions. But not able to see any transactions towards to MSQL and ORACLE databases. Please let me know the procedure to get this work. 

Regards,
Pradeep.

**Comment by emeroad** [comment]
Check the supported plugins and versions in the table below.
https://pinpoint-apm.gitbook.io/pinpoint/main#supported-modules

`$PINPOINT_DIR/profiles/$PROFILE/pinpoint.config`
And in the pinpoint.config setting, check the database setting as well.
