### ISSUE TITLE
Some of transactions are missing in scatter chart

### ISSUE THREAD

**Issue by ujlub** [pinpoint-apm/pinpoint#8863]
#### Prerequisites
- [ yes] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v2.3.2

#### Describe your problem**
A specific request can be checked in the Inspector.
It takes a very long time.(I have attached a screenshot below.)
But I can't see that request in the scatter chart.

The sampling rate is set to 100%.
profiler.sampling.rate=1

When there is a load on the pinpoint collector server, is there a possibility that part of the request will be missed?

#### Screenshots

![pinpoint ssgadm com_inspector_prod-ssg-promotion com@SPRING_BOOT_64m_2022-05-12-16-42-27_67b647b5f8-wwmwf](https://user-images.githubusercontent.com/44011902/168230538-8e513695-cd32-4c1a-b962-c429f2262424.png)
-> I can see very slow request around 15:50. The agent name is 67b647b5f8-wwmwf 

![pinpoint ssgadm com_main_prod-ssg-promotion com@SPRING_BOOT_64m_2022-05-12-16-42-27](https://user-images.githubusercontent.com/44011902/168231140-8acdb878-3022-4702-81c2-eaeec64bcd6f.png)
-> But I cannot see that request in scatter chart. The inquiry time is set the same, and the agent is the same.

![mouseover1](https://user-images.githubusercontent.com/44011902/168231975-16f710e4-81ae-469f-b5b0-767ed455e755.PNG)

![mouseover2](https://user-images.githubusercontent.com/44011902/168231999-0a681259-82a7-4f08-b66c-21529c439748.PNG)

**Comment by emeroad** [comment]
> When there is a load on the pinpoint collector server, is there a possibility that part of the request will be missed?

If hbase or collector capacity is not enough, traces can be discarded.

The sampling rate is determined by the root node, so it may not actually be 100%.
For this information, Rrefer to Transactions Per Second chart in the inspector
