### ISSUE TITLE
How to record controller method when using Spring WebFlux 

### ISSUE THREAD

**Issue by tankilo** [pinpoint-apm/pinpoint#8925]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

Similar Issue: https://github.com/pinpoint-apm/pinpoint/issues/6352

# Steps to run the demo.
I created a demo project based on spring official sample.
1. Clone code
https://github.com/tankilo/gs-reactive-rest-service

2. Edit `pinpoint-agent-2.4.0\profiles\release\pinpoint.config`
```
profiler.sampling.counting.sampling-rate=1

profiler.spring.beans.1.scope=component-scan
profiler.spring.beans.1.base-packages=
profiler.spring.beans.1.name.pattern=
profiler.spring.beans.1.class.pattern=
profiler.spring.beans.1.annotation=org.springframework.stereotype.Controller,org.springframework.stereotype.Service,org.springframework.stereotype.Repository,org.springframework.stereotype.Component

profiler.spring.beans.2.scope=post-processor
profiler.spring.beans.2.base-packages=
profiler.spring.beans.2.name.pattern=
profiler.spring.beans.2.class.pattern=
profiler.spring.beans.2.annotation=org.springframework.stereotype.Controller,org.springframework.stereotype.Service,org.springframework.stereotype.Repository,org.springframework.stereotype.Component
```

3. Run `hello.Application` with vm options as below:
```
-javaagent:C:\Coding\CodingEnv\pinpoint-agent-2.4.0\pinpoint-bootstrap-2.4.0.jar -Dpinpoint.agentId=fluxdemo1 -Dpinpoint.applicationName=fluxdemo1 -Dpinpoint.profiler.profiles.active=release
```

4. Open `http://localhost:8080/grettings` in browser.
![image](https://user-images.githubusercontent.com/10413284/173271136-ecb88b7d-fafd-41e6-a956-7392537ddf1d.png)

I can't found `hello.GreetingController#getGreeting` in the call tree.
![image](https://user-images.githubusercontent.com/10413284/173271044-b0573729-9599-4489-835a-0f44edaa7402.png)

**Comment by JinyangRao** [comment]
@tankilo Hi~! How did you solve this problem in the end?
