### ISSUE TITLE
upgrade pinpoint from v2.0.3 to v2.0.4

### ISSUE THREAD

**Issue by BruceMiao305** [pinpoint-apm/pinpoint#8959]
is there any official introduction for upgrade pinpoint from v2.0.3 to v2.0.4?

**Comment by ga-ram** [comment]
no, just change the jar files you're using to 2.0.4

**Comment by BruceMiao305** [comment]
I use tomcat to deploy v2.0.3, there is nothing about batch jar, should I deploy batch jar?
