### ISSUE TITLE
pinpoint on jdk17 apps

### ISSUE THREAD

**Issue by srchen1987** [pinpoint-apm/pinpoint#8978]
I use pinpoint 2.4.0

error: Error occurred during initialization of boot layer
java.lang.module.FindException: Two versions of module pinpoint.bootstrap found in . (pinpoint-bootstrap.jar and pinpoint-bootstrap-2.4.0.jar)
try to delete pinpoint-bootstrap-2.4.0.jar

error: 06-26 21:27:47.275 WARN  PinpointBootStrap                   : Invalid pinpoint-bootstrap.jar:null

I find code ...
 if (Object.class.getClassLoader()!= PinpointBootStrap.class.getClassLoader()) {
            // TODO bug : location is null
            logger.warn("Invalid pinpoint-bootstrap.jar:" + agentArgs);
            return;
        }
change to  
        if (ClassLoader.getSystemClassLoader() != PinpointBootStrap.class.getClassLoader()) {
            // TODO bug : location is null
            logger.warn("Invalid pinpoint-bootstrap.jar:" + agentArgs);
            return;
        }

......  more  error ...

not support jdk 17 ?

**Comment by emeroad** [comment]
Only one pinpoint-bootstrap*.jar must be set for the agent option. Check your command line.

**Comment by srchen1987** [comment]
> 

thx emeroad  answer,  I have solved this problem and implemented a tomcat10 plug-in. Pinpoint is a great project .

**Comment by srchen1987** [comment]
![dawdler-server](https://user-images.githubusercontent.com/20118859/176628400-8d251fca-f6ea-405f-9faf-d5f6e86f5e31.jpg)
It's work.

**Comment by srchen1987** [comment]
support  tomcat10 

https://github.com/srchen1987/pinpoint-tomcat10-plugin
