### ISSUE TITLE
开发自定义插件时，一直报错 Java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest 

### ISSUE THREAD

**Issue by s17-ok** [pinpoint-apm/pinpoint#9009]
自定义插件监控 http请求然后分析，在1.8.3版本中 agent可以正常使用，但是升级到了2.3.2中一直报错Java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest 

 HttpServletRequest request = (HttpServletRequest)args[0];
            HttpSession session = request.getSession();
            final SpanEventRecorder recorder = trace.currentSpanEventRecorder();

            recorder.recordServiceType(serviceType);
            recorder.recordApi(descriptor);
            recorder.recordException(throwable);

**Comment by zhic0223** [comment]
去看一下两个版本的插件的版本，2.3.2这里面没有找不到以前的那个类估计
