### ISSUE TITLE
Exceptions are marked as error even if they were handled(try... catch...)

### ISSUE THREAD

**Issue by Clapmin** [pinpoint-apm/pinpoint#9055]
In my application some custom exceptions are thrown which handled using "try... catch."

But, pinpoint mark this exception as error.

Is there any ways to exclude handled exceptions?

i'm using Pinpoint 1.8.5

**Comment by Clapmin** [comment]
> In my application some custom exceptions are thrown which handled using "try... catch."
> 
> But, pinpoint mark this exception as error.
> 
> Is there any ways to exclude handled exceptions?
> 
> i'm using Pinpoint 1.8.5

**Comment by Clapmin** [comment]
Done

**Comment by emeroad** [comment]
ignore-error-handler : https://github.com/pinpoint-apm/pinpoint/issues/6958
Take a look at the link above.

**Comment by Clapmin** [comment]
Thank you emeroad!!
I have one more question.

When external API call(with http protocol) response with status 4xx, 5xx marked as failed even it handled.
Is it possible to config or some ways to exclude that not to marked as failed??

![image](https://user-images.githubusercontent.com/19481092/181173508-780184c4-6870-41da-8deb-19cf51479644.png)

**Comment by simon-shi87** [comment]
> ignore-error-handler : #6958 Take a look at the link above.

@emeroad Hi，where is this configured, on the pp server or the pp agent?

**Comment by kojandy** [comment]
@simon-shi87 
Configurations with the prefix `profiler.` is for agents.
