### ISSUE TITLE
applications.pinpoint中application不全，请问怎么排查

### ISSUE THREAD

**Issue by PeiAlan** [pinpoint-apm/pinpoint#9081]
applications.pinpoint中只有部分的application，实际上我很多应用都对pinpoint。agent进行的配置。
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/33126641/181231822-4712e134-5f74-415c-8ead-ae47e0a14d39.png">

列举一个已经配置的应用：
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/33126641/181232011-313a0f85-af09-46d0-9e45-5614f8b81430.png">

**Comment by ga-ram** [comment]
There's not much anyone can know with the information you have provided.
Did your apps successfully run? How about pinpoint agent logs? Is there any error logs when it is starting? 
If it is all fine then is there any collector errors logged?

**Comment by PeiAlan** [comment]
> There's not much anyone can know with the information you have provided. Did your apps successfully run? How about pinpoint agent logs? Is there any error logs when it is starting? If it is all fine then is there any collector errors logged?

My app is running successfully，there is no error logs when it is starting，
But there is collector errors logs，the logs is follow：
`
pinpoint-collector     | 07-28 02:13:21.021 [Agent-Worker-50] WARN  c.n.p.c.h.g.GrpcSqlMetaDataHandler       : Failed to handle sqlMetaData=sqlId: 126473 sql: "select HOUSE_ID ,COUNT(0#) ct  from T_HM_EXPL_PIC where HOUSE_ID in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and STATUS in (\'1$\',\'2$\') AND isHD=3# AND IS_CRUCIAL = \'4$\' GROUP BY HOUSE_ID  "
pinpoint-collector     | com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551
pinpoint-collector     | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:713) ~[pinpoint-commons-hbase-2.2.1.jar!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:296) ~[pinpoint-commons-hbase-2.2.1.jar!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataDao.insert(HbaseSqlMetaDataDao.java:76) ~[classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataDao$$FastClassBySpringCGLIB$$a2e690ca.invoke(<generated>) ~[classes!/:2.2.1]
pinpoint-collector     | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataDao$$EnhancerBySpringCGLIB$$4fd537c0.insert(<generated>) ~[classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.service.SqlMetaDataService.insert(SqlMetaDataService.java:38) ~[classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.handler.grpc.GrpcSqlMetaDataHandler.handleSqlMetaData(GrpcSqlMetaDataHandler.java:75) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.handler.grpc.GrpcSqlMetaDataHandler.handleRequest(GrpcSqlMetaDataHandler.java:55) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.TcpDispatchHandler.dispatchRequestMessage(TcpDispatchHandler.java:85) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchRequestMessage(DelegateDispatchHandler.java:73) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.grpc.service.SimpleRequestHandlerAdaptor.request(SimpleRequestHandlerAdaptor.java:54) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.grpc.service.MetadataService$1.run(MetadataService.java:105) [classes!/:2.2.1]
pinpoint-collector     | 	at io.grpc.Context$1.run(Context.java:579) [grpc-context-1.33.1.jar!/:1.33.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:109) [classes!/:2.2.1]
pinpoint-collector     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
pinpoint-collector     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
pinpoint-collector     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
pinpoint-collector     | Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.makeException(AsyncProcess.java:297) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.access$2300(AsyncProcess.java:273) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.AsyncProcess.waitForAllPreviousOpsAndReset(AsyncProcess.java:1937) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:249) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:212) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1480) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1027) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$7.doInTable(HbaseTemplate2.java:299) ~[pinpoint-commons-hbase-2.2.1.jar!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:704) ~[pinpoint-commons-hbase-2.2.1.jar!/:2.2.1]
pinpoint-collector     | 	... 24 more
pinpoint-collector     | 07-28 02:13:21.021 [gent-Worker-178] WARN  c.n.p.c.h.g.GrpcSqlMetaDataHandler       : Failed to handle sqlMetaData=sqlId: 70353 sql: "select id createBy,REAL_NAME val  from SYS_USER where id in(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "
pinpoint-collector     | com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551
pinpoint-collector     | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:713) ~[pinpoint-commons-hbase-2.2.1.jar!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:296) ~[pinpoint-commons-hbase-2.2.1.jar!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataDao.insert(HbaseSqlMetaDataDao.java:76) ~[classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataDao$$FastClassBySpringCGLIB$$a2e690ca.invoke(<generated>) ~[classes!/:2.2.1]
pinpoint-collector     | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataDao$$EnhancerBySpringCGLIB$$4fd537c0.insert(<generated>) ~[classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.service.SqlMetaDataService.insert(SqlMetaDataService.java:38) ~[classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.handler.grpc.GrpcSqlMetaDataHandler.handleSqlMetaData(GrpcSqlMetaDataHandler.java:75) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.handler.grpc.GrpcSqlMetaDataHandler.handleRequest(GrpcSqlMetaDataHandler.java:55) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.TcpDispatchHandler.dispatchRequestMessage(TcpDispatchHandler.java:85) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchRequestMessage(DelegateDispatchHandler.java:73) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.grpc.service.SimpleRequestHandlerAdaptor.request(SimpleRequestHandlerAdaptor.java:54) [classes!/:2.2.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.receiver.grpc.service.MetadataService$1.run(MetadataService.java:105) [classes!/:2.2.1]
pinpoint-collector     | 	at io.grpc.Context$1.run(Context.java:579) [grpc-context-1.33.1.jar!/:1.33.1]
pinpoint-collector     | 	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:109) [classes!/:2.2.1]
pinpoint-collector     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
pinpoint-collector     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
pinpoint-collector     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
pinpoint-collector     | Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.makeException(AsyncProcess.java:297) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.access$2300(AsyncProcess.java:273) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.AsyncProcess.waitForAllPreviousOpsAndReset(AsyncProcess.java:1937) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:249) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:212) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1480) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
pinpoint-collector     | 	at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1027) ~[hbase-shaded-client-1.4.13.jar!/:1.4.13]
`

**Comment by PeiAlan** [comment]
How to solve this Hbase exception ？

**Comment by ga-ram** [comment]
```
org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551
```
I think this error log is quite self-explanatory.

**Comment by PeiAlan** [comment]
> ```
> org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Operation Timeout: 1 time, servers with issues: 1d9913568bc3,16201,1658918251551
> ```
> 
> I think this error log is quite self-explanatory.

How to handle this Operation Timeout? 
My Apps are deployed with docker-compose.

**Comment by emeroad** [comment]
The hbase-docker image was developed for simple testing.

If you plan to use pinpoint in production, you should deploy a fully-distributed hbase cluster.

**Comment by PeiAlan** [comment]
> The hbase-docker image was developed for simple testing.
> 
> If you plan to use pinpoint in production, you should deploy a fully-distributed hbase cluster.

OK，thanks！
I cleaned all docker containers and redeployed all pinpoint components with docker-compose of version 2.2.2, then i will deploy a fully-distributed hbase cluster

**Comment by PeiAlan** [comment]
The problem has been solved.

**Comment by PeiAlan** [comment]
thanks friends
