### ISSUE TITLE
EJB transaction not visible in my pinpoint WEB

### ISSUE THREAD

**Issue by btsinfo** [pinpoint-apm/pinpoint#9083]
I set up pinpoint APM for the transactional monitoring of my applications deployed on websphere 8.5.5.11 under java 1.6. I am using pinpoint agent version 2.1.2 (the latest version that supports 1.6 JDK). however in applications only http transactions are visible while other applications are full EJB3 does not respond to any transaction. please can someone help me

**Comment by emeroad** [comment]
Unfortunately, we are no longer interested in EJB and RMI technology.

EJB and RMI are already dead. There will be no additional technical support.
https://openjdk.org/jeps/385

To develop plugins yourself, refer to the article below.
https://pinpoint-apm.gitbook.io/pinpoint/documents/plugin-dev-guide

**Comment by btsinfo** [comment]
@emeroad ,thank you for your feedback, please is there a version of the pinpoint agent (old version) that allows the collection of EJB traces
