### ISSUE TITLE
is thre any way to tracing sacala on JVM?

### ISSUE THREAD

**Issue by inchonjjin** [pinpoint-apm/pinpoint#9108]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [v] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

 we use S2Graph applicaiton( scala on JVM ) and want to tracing s2graph application. 
2.3.3  pinpoin can't trace anything. 

would you please give me any advise to trace s2graph application on pinpoint.

**Comment by emeroad** [comment]
There is currently no easy way.
You must specify a Java class name compiled by the Scala compiler in the plugin

Maybe refer to OpenwhiskPlugin and it will be helpful.
https://github.com/pinpoint-apm/pinpoint/blob/master/plugins/openwhisk/src/main/java/com/navercorp/pinpoint/plugin/openwhisk/OpenwhiskPlugin.java

It is a good way for plugins to support Scala's Java compilation rules,
but we're not interested in Sacala.
```java
public class S2GraphPlugin implements ProfilerPlugin, TransformTemplateAware {

    private SacalaTransformTemplate sacalaTransformTemplate;
	
	@Override
    public void setTransformTemplate(TransformTemplate transformTemplate) {
	    // Convert scala class to java class rule
        this.sacalaTransformTemplate = new SacalaTransformTemplate(transformTemplate);
    }
	
	@Override
    public void setup(ProfilerPluginSetupContext context) {
         sacalaTransformTemplate.transform("com.kakao.s2graph.Vertex", VertexTranformcallBack.class)
    }
}
```
