### ISSUE TITLE
 Unable to track more microservices

### ISSUE THREAD

**Issue by dxl727754275** [pinpoint-apm/pinpoint#9114]
Pinpoint is version 2.4.1 and deployed in docker mode

I use pinpoint for monitoring microservices. If I access the sports interface, but the sports application does not collect data

The requested interface can be seen on the gateway, but there are only auth and user services on the link. When viewing the sports service separately, it is found that there is no data, but it is possible to request the sports service separately.

What configuration do I lack?

My system architecture: nginx -> gateway -> nacos -> user | auth | sport | other

I access the corresponding page through nginx
Through the gateway, you can't see the sports service in the topology diagram

**Comment by dxl727754275** [comment]
In the gateway service, you can only see auth and user
![111](https://user-images.githubusercontent.com/40659245/183611932-e531d457-8475-44b2-888f-61f39d65c1c8.jpg)
Look at the URL of the gateway, but you can see the URL to access the sports service
![222](https://user-images.githubusercontent.com/40659245/183613367-078992a0-d559-48d3-8406-12a6524c8bed.jpg)
There is no data when viewing the sports service, but the log shows the interface request
![333](https://user-images.githubusercontent.com/40659245/183613475-5eac6286-10ba-4d9a-bdc6-9db77f4e05e2.jpg)

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#supported-modules
Check the support module.
If you use an unsupported module, it will not be tracked.

**Comment by dxl727754275** [comment]
> https://github.com/pinpoint-apm/pinpoint#supported-modules Check the support module. If you use an unsupported module, it will not be tracked.

I confirm that my application is supported because they are the same set of services
