### ISSUE TITLE
Vert.x4.2.2  (io.vertx.core.http.impl.Http1xClientConnection#createRequest) is not supported

### ISSUE THREAD

**Issue by zhic0223** [pinpoint-apm/pinpoint#9144]
Vert.x 4.2.2 的 io.vertx.core.http.impl.Http1xClientConnection.createRequest(io.vertx.core.http.HttpMethod method, java.lang.String uri, io.vertx.core.MultiMap headerMap, java.lang.String authority, boolean chunked, io.netty.buffer.ByteBuf buf, boolean end) createRequest()需要单独加上，这个方法的传参跟3.7.0不一致，拦截器里面还需要微调

**Comment by emeroad** [comment]
Please use English.
We don't understand Chinese.

**Comment by zhic0223** [comment]
![image](https://user-images.githubusercontent.com/102710484/186633185-a045c2f8-abe5-4b1b-b57e-2bdd2809214e.png)

This place in Vert.x 3.7 createRequestMethod is createRequest(
"io.vertx.core.http.HttpMethod", "java.lang.String", "java.lang.String", "io.vertx.core.MultiMap", "java.lang.String", "boolean"
)
in Vert.x 4.2.2 createRequestMethod is createRequest(
"io.vertx.core.http.HttpMethod", "java.lang.String","io.vertx.core.MultiMap", "java.lang.String", "boolean",
"io.netty.buffer.ByteBuf", "boolean"
) 
they are different. you should add this and add a new class 
 Http1xClientConnectionCreateRequestInterceptor and in this class ,you should Change a little. by the way, your pinpoint is very good! thx

**Comment by jaehong-kim** [comment]
@zhic0223 
We will reflect it in the next patch version.
thank you

**Comment by zhic0223** [comment]
@jaehong-kim You're welcome.

**Comment by jaehong-kim** [comment]
#9164
