### ISSUE TITLE
pinpoint web display invalid agents

### ISSUE THREAD

**Issue by wenyiwener** [pinpoint-apm/pinpoint#9270]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v2.3.0

#### Describe the bug
pinpoint web display invalid agents
![image](https://user-images.githubusercontent.com/33948587/196083363-8ef448f0-bbeb-4410-8634-c328335c9082.png)
There are only four running agents，but the web shows 12 agents
#### What did you do to trigger the bug?
In the method of AgentInfoServerInstanceListDataSource class 
The filterAgentInfos method is as follows. When querying the agent status, agentinfos is used to query and return the agentStatusList of the corresponding size. When filtering the running agent, agentsToCheckStatus is used to compare with the query result agentStatusList. The two lists are inconsistent in size, so the same index cannot be used for comparison. This will lead to comparison errors, because the returned filteredAgentInfos will have more abnormal agents
#### Expected behavior
![image](https://user-images.githubusercontent.com/33948587/196084678-5654dfe6-d7ed-4ad4-869c-a8cf434982c0.png)

The code for bug elimination and modification is as follows
![image](https://user-images.githubusercontent.com/33948587/196084695-72920ce3-64d4-4f3b-9d48-76e630b75cff.png)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by intr3p1d** [comment]
Hello, @wenyiwener.
The commented issue is related to #8967 and the issue is currently working.

Your bug report is reasonable, but some agents will appear in some internal policies (we are working on this to unify the policy)
So I want to notify you that even after we applied your bug hot-fix, some agents can still appear in the server map agents list.

However, it seems the issue is quite major, so I will apply the hotfix.
Thank you for your attention to our project.

**Comment by wenyiwener** [comment]
It's my honor to help Pinpoint a little, and thank the Pinpoint team for continuous optimization to unify the policy
