### ISSUE TITLE
Change Boot Log level from "INFO" to "WARN"

### ISSUE THREAD

**Issue by EYashish** [pinpoint-apm/pinpoint#9422]
Is there any way to change the log level of starting agent of Pinpoint from INFO to WARN ?

For example when agent starts - logs looks like this

11-16 11:38:16.262 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-hikaricp-plugin-2.4.0.jar
11-16 11:38:16.262 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-mybatis-plugin-2.4.0.jar
11-16 11:38:16.263 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-logback-plugin-2.4.0.jar
11-16 11:38:16.264 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-weblogic-plugin-2.4.0.jar
11-16 11:38:16.264 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-netty-plugin-2.4.0.jar
11-16 11:38:16.264 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-jackson-plugin-2.4.0.jar
11-16 11:38:16.265 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-elasticsearch8-plugin-2.4.0.jar
11-16 11:38:16.266 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-hbase-plugin-2.4.0.jar
11-16 11:38:16.266 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-druid-plugin-2.4.0.jar
11-16 11:38:16.267 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-resin-plugin-2.4.0.jar
11-16 11:38:16.267 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-rxjava-plugin-2.4.0.jar
11-16 11:38:16.268 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-commons-dbcp2-plugin-2.4.0.jar
11-16 11:38:16.268 INFO  AgentDirBaseClassPathResolver       : Found plugins:/tmp/pinpoint-agent-2.4.0/plugin/pinpoint-gson-plugin-2.4.0.jar

Purpose is to not want these logs.....so is there any way to change the logs from "INFO" to WARN.

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint/blob/master/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogger.java#L41

`-Dpinpoint.agent.bootlogger.loglevel=WARN`
You can change the log level with -D option.
