### ISSUE TITLE
Export the 'mail.smtp.ssl.enable' in the batch.

### ISSUE THREAD

**Issue by JunRadish** [pinpoint-apm/pinpoint#9424]
**Which module is your feature request related to?**
Batch/.../applicationContext-batch-sender.xml

**Is your feature request related to a problem?**
Cannot use Gmail's SMTP easily cause by default, the sender does not enabled to use 'mail.smtp.ssl.enable' configuration.
Cause a lot of users in pinpoint might using gmail to send mail via pinpoint's batch, this feature will be useful to lots of develpers!

**Describe the solution you'd like**
1. Add the below property between line number 30 and 31 in 'pinpoint/batch/src/main/resources/applicationContext-batch-sender.xml'
`<prop key="mail.smtp.ssl.enable>${alarm.mail.smtp.ssl.enable:false}</prop>
`
2. Update the configuration guide of pinpoint batch with 'Setting the value `alarm.mail.smtp.ssl.enable` if you needed'.

**Describe alternatives you've considered**
Nothing for now

**Additional context**
Thanks for sharing the most useful APM tool for me.
Me and my team always thanks to your team.
추가적으로 문의사항이 있으시다면 junminkim@jobis.co로 연락주시면 감사하겠습니다!

**Comment by emeroad** [comment]
I completely agree with your proposal.
Coud you create a PR?

**Comment by JunRadish** [comment]
@emeroad Sure! I will create a PR for this Issue.
