### ISSUE TITLE
How to modify user password

### ISSUE THREAD

**Issue by dmz-leon** [pinpoint-apm/pinpoint#9430]
What should I do if I want to change my password for login?

**Comment by minwoo-jung** [comment]
Hi @dmz-leon 

Configuration
Declares user:password in pinpoint-web.properties as follows.
(You can declare multiple people using,.)

```
# in pinpoint-web.properties
web.security.auth.user=alice:foo, bob:bar
web.security.auth.admin=eve:baz
```

please ref this issue : https://github.com/pinpoint-apm/pinpoint/issues/7205
