### ISSUE TITLE
please add README.file in kotlin-coroutines plugin

### ISSUE THREAD

**Issue by mayaul** [pinpoint-apm/pinpoint#9444]
**Which module is your feature request related to?**
Plugin/kotlin-coroutines 

**Is your feature request related to a problem?**
My project use kotlin-coroutines. I have a issue pinpoint dashboard. and I resolved that.
The cause I don't setting kotlin-coroutines options

**Describe the solution you'd like**
It would have been easier to find the cause if the readme.md file was added.

**Describe alternatives you've considered**

**Additional context**

**Comment by jaehong-kim** [comment]
@mayaul 
Thank you for your suggestion.
We will proceed with the work for adding README.

**Comment by jaehong-kim** [comment]
@mayaul 
The README file has been added.
#9491
