### ISSUE TITLE
Error when adding webhook

### ISSUE THREAD

**Issue by dv-morais** [pinpoint-apm/pinpoint#9489]
Hello everyone,

I'm trying to add a webhook to use as an alarm and I'm facing errors.

when the webhook URL is bigger than 46 characeters it throws me this error
![image](https://user-images.githubusercontent.com/57958197/206238093-f405c2cf-e275-4c86-a5ee-2a85a3198a86.png)

am I doing something wrong?

thanks in advance

**Comment by minwoo-jung** [comment]
@ga-ram please check this issue

**Comment by ga-ram** [comment]
https://github.com/pinpoint-apm/pinpoint/blob/0eb0596131300c0502bf5c9c6662f716917ffecf/web/src/main/resources/sql/CreateTableStatement-mysql.sql#L69

Current mysql table script initializes the size of alarm url data to 45 characters.
Definitely it is too small for actual uses. I will change `url` and `alias` column to VARCHAR(256) characters shortly.

Meanwhile, please alter your mysql table to store more characters for alarm urls. 
```
ALTER TABLE `webhook` 
CHANGE COLUMN `alias` `alias` VARCHAR(250) NULL DEFAULT NULL ,
CHANGE COLUMN `url` `url` VARCHAR(250) NOT NULL ;
```
