### ISSUE TITLE
In 2.4.2 version pinpoint.applicationName has another 24-character limit

### ISSUE THREAD

**Issue by fumingjian** [pinpoint-apm/pinpoint#9493]
[####] Screenshots
[root@strategy-app agent]# ll
total 31384
drwxr-xr-x 9 root root      225 Nov 29 16:14 pinpoint-agent-2.4.2
-rw-r--r-- 1 root root 32136085 Dec  8 18:29 pinpoint-agent-2.4.2.tgz
[root@strategy-app agent]# 
#### Logs
12-09 09:44:06.188 INFO  AgentDirBaseClassPathResolver       : Found plugins:/var/agent/pinpoint-agent-2.4.2/plugin/pinpoint-kotlin-coroutines-plugin-2.4.2.jar
12-09 09:44:06.302 INFO  PinpointBootStrap                   : appendToBootstrapClassLoader:/var/agent/pinpoint-agent-2.4.2/boot/pinpoint-commons-2.4.2.jar
12-09 09:44:06.303 INFO  PinpointBootStrap                   : appendToBootstrapClassLoader:/var/agent/pinpoint-agent-2.4.2/boot/pinpoint-bootstrap-core-2.4.2.jar
12-09 09:44:06.303 INFO  PinpointBootStrap                   : appendToBootstrapClassLoader:/var/agent/pinpoint-agent-2.4.2/boot/pinpoint-annotations-2.4.2.jar
12-09 09:44:06.304 INFO  PinpointBootStrap                   : appendToBootstrapClassLoader:/var/agent/pinpoint-agent-2.4.2/boot/pinpoint-bootstrap-java8-2.4.2.jar
12-09 09:44:06.305 INFO  PinpointBootStrap                   : appendToBootstrapClassLoader:/var/agent/pinpoint-agent-2.4.2/boot/pinpoint-bootstrap-java9-2.4.2.jar
12-09 09:44:06.305 INFO  PinpointBootStrap                   : appendToBootstrapClassLoader:/var/agent/pinpoint-agent-2.4.2/boot/pinpoint-bootstrap-java9-internal-2.4.2.jar
12-09 09:44:06.306 INFO  PinpointBootStrap                   : parentClassLoader:BootStrapClassLoader:null
12-09 09:44:06.310 INFO  IdValidator                         : check SystemProperties(-D) agentId:compass-strategy-test-2
12-09 09:44:06.311 INFO  AgentIdResolver                     : SystemProperties(-D) pinpoint.agentId=compass-strategy-test-2
12-09 09:44:06.311 INFO  IdValidator                         : check SystemProperties(-D) applicationName:compass-strategy-app-test
12-09 09:44:06.312 INFO  IdValidator                         : invalid Id. SystemProperties(-D) applicationName can only contain [a-zA-Z0-9], '.', '-', '_'. maxLength:24 value:compass-strategy-app-test
12-09 09:44:06.312 WARN  AgentIdResolver                     : Failed to resolve ApplicationName(-Dpinpoint.applicationName)
12-09 09:44:06.313 WARN  PinpointStarter                     : Failed t

**Comment by emeroad** [comment]
AgentId and ApplicationName must be less than 24 characters.
