### ISSUE TITLE
How to Custom Pinpoint batch 

### ISSUE THREAD

**Issue by Junnyjun** [pinpoint-apm/pinpoint#9529]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

## 현재 상황
[Dockerized](https://github.com/pinpoint-apm/pinpoint-docker)로 (2.4.0버전) Pinpoint-web, Pinpoint-batch, Pinpoint-agent, Pinpoint-collector, Pinpoint-hbase, Pinpoint-mysql을 설치

## 문제
새로 작성한 SmsSender를 적용하기 위해서는 Pinpoint-batch에 변경된 jar를 넣고 실행해야 하는데,

pinpoint-batch- Dockerfile 내부에 `curl -SL ${INSTALL_URL} -o /pinpoint/pinpoint-batch.jar`만 새로 빌드된 jar로 Copy후 실행하면 되는지 확인해주세요

혹은 아니라면 어떤 방법을 사용해야 하는지 알려주세요

PS ) 2.4.0버전의 pinpoint-batch를 사용하지 않아도 문제가 되지않나요?

**Comment by ga-ram** [comment]
It would be nice if you can also describe your situation in english for the community.
