### ISSUE TITLE
How do get log latency

### ISSUE THREAD

**Issue by Junnyjun** [pinpoint-apm/pinpoint#9551]
- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

hello!
i used pinpoint-dockerized 2.4.1

Where can I edit the log deletion cycle?
in hbase and Collector, Cant find any configuration

And How can I handle old logs?

**Comment by jonascolling** [comment]
@Junnyjun How did you solve this problem?

**Comment by Junnyjun** [comment]
> @Junnyjun How did you solve this problem?

I removed this issue by creating a script myself 🫥
