### ISSUE TITLE
Cannot find New URL Statistics & Infrastructure Features 

### ISSUE THREAD

**Issue by VidushaZ** [pinpoint-apm/pinpoint#9616]
Hi ,

I've built the latest but I cannot see new features (URL Statistics & Infrastructure Features) in the menu. Do I have to enable them from somewhere? 

Thanx

**Comment by minwoo-jung** [comment]
Hi @VidushaZ 
Please ref this guide : https://pinpoint-apm.gitbook.io/pinpoint/documents/system_metric
