### ISSUE TITLE
does uri_statistics support struts 2

### ISSUE THREAD

**Issue by ZhanChaoHan** [pinpoint-apm/pinpoint#9716]
https://pinpoint-apm.gitbook.io/pinpoint/documents/uri_statistics

support webmvc
support webflux
support vertx

does  support struts2 project??

**Comment by smilu97** [comment]
Current pinpoint agent can't detect URI mapping from struts2 project.

For now, manually setting up `pinpoint.metric.uri-template` in attributes of ServletRequest is the only way.
