### ISSUE TITLE
add Sites using Pinpoint

### ISSUE THREAD

**Issue by Star-ho** [pinpoint-apm/pinpoint#9718]
**Which module is your feature request related to?**
X

**Is your feature request related to a problem?**
X

**Describe the solution you'd like**
Thank you for making Pin Point so well.
we are using Pinpoint for troubleShooting.
i want to add our Site to 'Sites using Pinpoint'.
site is 'THE PIRATES(www.tpirates.com)'.
thank you

**Describe alternatives you've considered**
X
**Additional context**
X

**Comment by emeroad** [comment]
'THE PIRATES' has been added to the Sites using Pinpoint.
Thank you.

**Comment by Star-ho** [comment]
how can i add my site on official homepage(https://pinpoint-apm.gitbook.io/pinpoint/powered-by)?

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint-apm.github.io

Would you please send PR to the site above?

**Comment by Star-ho** [comment]
thank you!
