### ISSUE TITLE
Can't use the proxy-user module to track multiple nginx proxies.

### ISSUE THREAD

**Issue by geministarshine** [pinpoint-apm/pinpoint#9784]
#### Pinpoint Agent Configuration
 **pinpoint.config**
```
1. profiler.proxy.http.header.enable=true
2. profiler.proxy.http.headers=X-Ssl-Terminator-Nginx, X-Reverse-Proxy-Nginx
```
#### Nginx Configuration
**reverse proxy nginx.config**
```
1. set $X-Reverse-Proxy-Nginx "t=$msec";
2. proxy_set_header X-Reverse-Proxy-Nginx $X-Reverse-Proxy-Nginx;
```
**ssl terminator nginx.config**
```
1. set $X-Ssl-Terminator-Nginx "t=$msec";
2. proxy_set_header X-Ssl-Terminator-Nginx $X-Ssl-Terminator-Nginx;
```
#### What version of pinpoint are you using?
master/v2.3.3 etc.

#### Describe your problem**
topology: SSL Terminator -> Reverse-Proxy -> App Server
1. can't use the proxy-nginx module to track multiple nginx proxies.
2. can't use the proxy-user module to track multiple nginx proxies, for the variable "t=$msec" .

#### What have you done?
src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestParser.java:
```
    public long toReceivedTimeMillis(final String value) {
        if (value == null) {
            return 0;
        }

        final int length = value.length();

        final int millisPosition = value.lastIndexOf('.');
        if (millisPosition != -1) {
            if (length - millisPosition != 4) {
                // invalid format.
                return 0;
            }
            String strValue = value.substring(0, millisPosition) + value.substring(millisPosition + 1);
            return NumberUtils.parseLong(strValue, 0);
        }else {
            return NumberUtils.parseLong(value, 0);
        }
    }
```

**Comment by jaehong-kim** [comment]
@geministarshine 
Thank you for the PR.
That sounds like a great idea. By the way, if you add nginx, I think you should consider apache as well.
It's too complicated to use a mix of time units.

We are considering how to use postfix simply.
For example, X-Ssl-Terminator-Nginx is parsed in nginx format, and X-Ssl-Terminator-Apache is parsed in Apache format.
The postfix is not case sensitive.

**Comment by jaehong-kim** [comment]
@geministarshine
Thank you for the PR.
