### ISSUE TITLE
maven compile failed, the cause is maven-enforcer-plugin:3.0.0:enforce

### ISSUE THREAD

**Issue by tangmin823** [pinpoint-apm/pinpoint#9796]
After I clone source code from the master branch  git, I compile it but failed, I tried a lot, just one problem about maven-enforcer-plugin:3.0.0:enforce, I have installed both Java  version 8 and 11, added them to enviroment, but it still failed
![image](https://user-images.githubusercontent.com/13765160/227761209-8b627ac1-0874-4e2f-85c3-e6ae180f56f6.png)
![image](https://user-images.githubusercontent.com/13765160/227761411-51e76fd5-7aa7-42ec-b4dc-8629a45d8591.png)

**Comment by emeroad** [comment]
In general, you should set the environment variable first before starting intellij.
