### ISSUE TITLE
javaagent bean creation exception

### ISSUE THREAD

**Issue by kjb512** [pinpoint-apm/pinpoint#9797]
hello! I'm trying to attatch pinpoint-agent into my Spring Boot Application .

java -jar -javaagent:/pinpoint-agent-2.3.3/pinpoint-bootstrap-2.3.3.jar -Dpinpoint.agentId=test -Dpinpoint.applicationName=toyou -Dpinpoint.config=/pinpoint-agent-2.3.3/pinpoint-root.config -Dspring.profiles.active=prod toYou-0.0.1-SNAPSHOT.jar

But, when I add -javaagent option, a bean creation exception occurs. (pinpoint agent was normally started)

If I only use ,  java - jar toYou-0.0.1-SNAPSHOT.jar, application normally start

spring -boot 2.5.6

openjdk:11

**Comment by ga-ram** [comment]
There's no prod profile provided by us. Did you create it on your own?
Please share full exception logs.

**Comment by kjb512** [comment]
Thank you for your reply. The problem has been resolved now and it was my mistake. There was no prod in the profile but I gave the prod option…

**Comment by kjb512** [comment]
Thank you for your reply. The problem has been resolved now and it was my mistake. There was no prod in the profile but I gave the prod option…
