### ISSUE TITLE
Do you plan to support instrumentation of Rails application?

### ISSUE THREAD

**Issue by donghoon-lee-mrt** [pinpoint-apm/pinpoint#9803]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

I just want to know if you have any plan to support Ruby on rails application. If so, please let me know in detail (schedule of supporting or version roughly)

Thanks.

**Comment by emeroad** [comment]
Unfortunately, there are currently no plans to support the rubys application.

**Comment by donghoon-lee-mrt** [comment]
Thanks for quick response. One more question. Do you have any guide docs to implement custom - 3rd party - agents? If it is possible, I can consider implementing an agent for rails application.

**Comment by emeroad** [comment]
It may be helpful to refer to the plugin development guide for java.
https://pinpoint-apm.gitbook.io/pinpoint/documents/plugin-dev-guide

**Comment by donghoon-lee-mrt** [comment]
Thanks a lot, I think this issue can be closed.
