### ISSUE TITLE
My project doesn't run with pinpoint-bootstrap-2.2.1.jar.

### ISSUE THREAD

**Issue by gar-den** [pinpoint-apm/pinpoint#9827]
#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [v] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

My versions
- JDK: 17
- Pinpoint: 2.2.1
- HBase: 2.4.15

I ran collector and web and it ran fine.
But when I'm trying to run my app, there are some problems.

`java -jar -javaagent:pinpoint-bootstrap-2.2.1.jar -Dpinpoint.agentId=application-1 -Dpinpoint.applicationName=my-app -Dpinpoint.config=pinpoint-root.config my-app.jar`

And this makes some errors.
`java.lang.illegalargumentexception: unsupported class file major version 61`

Do my versions not work each others? I don't know how to solve this problem.

**Comment by emeroad** [comment]
https://github.com/pinpoint-apm/pinpoint#compatibility

Refer to the compatibility table.
