### ISSUE TITLE
URL Statistics not providing the data more than 3 days

### ISSUE THREAD

**Issue by PIYUSHRAJ24** [pinpoint-apm/pinpoint#9875]
Hi,
I have configured pinpoint-apm for my production servers and I am using it for the last 1 month but in URL statistics I was checking the data for the last 7 days it was not showing there for more than 3 days. I have checked log retention in hbase also but I am not able to find any issue with log retention. I am attaching some images for your reference. Please help. It would be very kindful.

Thanks
![Screenshot from 2023-04-17 14-24-48](https://user-images.githubusercontent.com/96586938/232437047-b06b3671-c42e-432f-ac14-1edfc968d8ac.png)
![Screenshot from 2023-04-17 13-46-45](https://user-images.githubusercontent.com/96586938/232437088-a7ec7631-172e-4b73-a757-867523ed03bc.png)

**Comment by ga-ram** [comment]
URI Statistics uses Pinot as its database.
If you are using pinpoint-docker project as your reference, your pinot controller server is on `localhost:9000`.
Check Home > Tables > uriStat_REALTIME > TABLE CONFIG. If retentionTImeValue is enough for you (you can modify it with `Edit Table` menu there).
I may have forgot to add docker volumes for pinot data in docker compose settings that previous data might be wiped out when you `docker-compose ... down`.

**Comment by PIYUSHRAJ24** [comment]
Thank you, now it's working as expected.
