### ISSUE TITLE
Pinpoint not recognize Client IP (proxied by Nginx)

### ISSUE THREAD

**Issue by phuc16102001** [pinpoint-apm/pinpoint#9900]
Hi guys, 

I am having a problem with the X-Real-IP header. Currently, I use a Nginx reverse proxy and forward the request to the Tomcat servlet (integrated with Pinpoint). However, the `Client IP` always 127.0.0.1 not the real client IP. 

I have tried to edit the `profiler.server.realipheader` params to `X-Real-IP` and it worked. I want to know that **what is the default config** for that params? Because it I see from the default `pinpoint-root.config` file, it is leaved empty.

The Pinpoint version I am using is `2.3.2`.

Here is my Nginx conf:

```
server {
        listen       80;
        server_name  localhost;
        root         /home/vuongphuc/deploy;
        etag         off;
        
        # Forward to Tomcat
        location / {
            proxy_set_header   Host $host;
            proxy_set_header   Connection "";
            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_headers_hash_max_size 512;
            proxy_headers_hash_bucket_size 128;

            proxy_http_version 1.1;
            proxy_max_temp_file_size 0;
            proxy_redirect off;
            proxy_read_timeout 240s;
            proxy_buffering off;
            proxy_ignore_client_abort on;

            proxy_pass         http://127.0.0.1:8080/;
        }
    }
```

Thank you!

**Comment by smilu97** [comment]
There is no default value for `profiler.server.realipheader`, but it is just disabled when user does not manually specify it

**Comment by phuc16102001** [comment]
Oh thank you, I have resolved the problem.
It is caused by the catalina configuration. I have added to the `server.xml` in tomcat the Valve:

```
<Valve className="org.apache.catalina.valves.RemoteIpValve" />
```

After that, I restart the tomcat (using `catalina.sh`)
